(function(g){var window=this;/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
var z2=function(a){a.S("cardstatechange",g.CL(a)&&g.DL(a)?1:0)},dua=function(a){if(/-[a-z]/.test("pollChoiceIndex"))return null;
if(g.fk&&a.dataset){if(g.Uc()&&!("pollChoiceIndex"in a.dataset))return null;a=a.dataset.pollChoiceIndex;return void 0===a?null:a}return a.getAttribute("data-"+g.pd("pollChoiceIndex"))},eua=function(a){return Math.pow(a,3)},fua=function(a){return 3*a*a-2*a*a*a},A2=function(a,b){var c=g.Bo("use_default_events_client")?void 0:g.dr;
(0,g.y)(b,function(d){d={csn:a,ve:g.ks(d),eventType:4};var e={bk:g.rs(a),Gj:a};"UNDEFINED_CSN"==a?g.Fs("visualElementShown",d,e):c?g.Yp("visualElementShown",d,c,e):g.er("visualElementShown",d,e)})},B2=function(a,b){var c=g.Bo("use_default_events_client")?void 0:g.dr;
(0,g.y)(b,function(d){var e=void 0;e=void 0===e?!1:e;d={csn:a,ve:g.ks(d),eventType:e?16:8};e={bk:g.rs(a),Gj:a,wF:e};"UNDEFINED_CSN"==a?g.Fs("visualElementHidden",d,e):c?g.Yp("visualElementHidden",d,c,e):g.er("visualElementHidden",d,e)})},E2=function(a){a=g.Qa(a);
delete C2[a];g.Pb(C2)&&D2&&D2.stop()},hua=function(){D2||(D2=new g.I(function(){gua()},20));
var a=D2;a.isActive()||a.start()},gua=function(){var a=(0,g.C)();
g.Cb(C2,function(b){iua(b,a)});
g.Pb(C2)||hua()},F2=function(a,b,c,d){g.Jn.call(this);
if(!Array.isArray(a)||!Array.isArray(b))throw Error("Start and end parameters must be arrays");if(a.length!=b.length)throw Error("Start and end points must be the same length");this.A=a;this.H=b;this.duration=c;this.F=d;this.coords=[];this.progress=this.G=0;this.C=null},iua=function(a,b){b<a.startTime&&(a.endTime=b+a.endTime-a.startTime,a.startTime=b);
a.progress=(b-a.startTime)/(a.endTime-a.startTime);1<a.progress&&(a.progress=1);a.G=1E3/(b-a.C);a.C=b;jua(a,a.progress);1==a.progress?(a.o=0,E2(a),a.Dd(),a.Vm()):a.nb()&&a.Ju()},jua=function(a,b){g.Na(a.F)&&(b=a.F(b));
a.coords=Array(a.A.length);for(var c=0;c<a.A.length;c++)a.coords[c]=(a.H[c]-a.A[c])*b+a.A[c]},kua=function(a,b){g.Pe.call(this,a);
this.coords=b.coords;this.x=b.coords[0];this.y=b.coords[1];this.z=b.coords[2];this.duration=b.duration;this.progress=b.progress;this.fps=b.G;this.state=b.o},G2=function(a,b,c,d,e){F2.call(this,b,c,d,e);
this.element=a},H2=function(a,b,c,d,e){if(2!=b.length||2!=c.length)throw Error("Start and end points must be 2D");
G2.call(this,a,b,c,d,e)},I2=function(a){g.z.call(this);
this.u=a||window;this.o=[]},lua=function(a,b,c,d){c=(0,g.x)(c,d||a.u);
b=g.qp(b,"change",c,"iv-card-poll-choice-input");a.o.push(b)},J2=function(a){return a.baseUrl||null},K2=function(a,b){return(0,g.Be)((0,g.Jc)(a,b,void 0),function(c){return!!c})},mua=function(a,b,c){function d(Vb){var jb=Vb.hovercardButton;
if(!jb)return null;jb=jb.subscribeButtonRenderer;if(!jb)return null;var Pd=f(jb.unsubscribedButtonText),Th=f(jb.subscribedButtonText);if(jb.subscribed){var Uh=f(jb.subscriberCountWithUnsubscribeText);var Jg=f(jb.subscriberCountText)}else Uh=f(jb.subscriberCountText),Jg=f(jb.subscriberCountWithSubscribeText);var uf=null;return Vb.signinEndpoint&&(uf=g.Kb(Vb,"signinEndpoint","webNavigationEndpointData","url"),!uf)?null:Pd&&(Th||uf)?{subscribed:jb.subscribed,subscribeText:Pd,subscribeCount:Uh,unsubscribeText:Th,
unsubscribeCount:Jg,enabled:jb.enabled,signinUrl:uf,classic:Vb.useClassicSubscribeButton}:null}
function e(Vb){if(Vb){var jb=[],Pd=Vb.videoId;Pd&&jb.push("v="+Pd);(Pd=Vb.playlistId)&&jb.push("list="+Pd);(Vb=Vb.startTimeSeconds)&&jb.push("t="+Vb);return"/watch?"+jb.join("&")}}
function f(Vb){if(!Vb)return null;var jb=Vb.simpleText;return jb?jb:Vb.runs?(0,g.Jc)(Vb.runs,function(Pd){return Pd.text}).join(""):null}
b=b.endscreenElementRenderer;if(!b)return null;var k=b.style,l=b.endpoint||{},m=null,n=null,q=null,t=null,u=null,w=null,B=!1,D=null,E=null,F=null,G=null,ba=null;if("VIDEO"==k)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,q=a,t=f(b.videoDuration);else if("PLAYLIST"==k)m=l.urlEndpoint?l.urlEndpoint.url:e(l.watchEndpoint),n=!1,q=a,u=f(b.playlistLength);else if("CHANNEL"==k){if(B=g.Kb(l,"browseEndpoint","browseId"))w=B,m="/channel/"+w;n=!1;q="new";(B=!!b.isSubscribe)?D=d(b):E=f(b.subscribersText)}else"WEBSITE"==
k?((F=g.Kb(l,"urlEndpoint","url"))&&(m=F),n=!0,q="new",F=b.icon.thumbnails[0].url):"CREATOR_MERCHANDISE"==k&&(b.productPrice&&(G=f(b.productPrice)),b.additionalFeesText&&(ba=f(b.additionalFeesText)),(n=g.Kb(l,"urlEndpoint","url"))&&(m=n),n=!0,q="new");a=g.Kb(b,"title","accessibility","accessibilityData","label");var na=b.endpoint?b.endpoint.clickTrackingParams:null,tb="";if(b.metadata){var Za=f(b.metadata);Za&&(tb=Za)}return{id:"element-"+c,type:k,title:f(b.title),metadata:tb,callToAction:f(b.callToAction),
Qx:b.image,iconUrl:F,left:parseFloat(b.left),width:parseFloat(b.width),top:parseFloat(b.top),aspectRatio:parseFloat(b.aspectRatio),startMs:parseInt(b.startMs,10),endMs:parseInt(b.endMs,10),videoDuration:t,playlistLength:u,channelId:w,subscribeButton:D,subscribersText:E,isSubscribe:B,targetUrl:m,SG:n,Zb:{itct:na},XO:q,Ml:a?a:null,WG:b.isPlaceholder,impressionUrls:K2(b.impressionUrls||[],J2),KG:K2(b.hovercardShowUrls||[],J2),clickUrls:K2(l.loggingUrls||[],J2),visualElement:g.js(b.trackingParams),productPrice:G,
additionalFeesText:ba}},L2=function(a,b){var c={};
c.startMs=parseInt(a.startMs,10);c.impressionUrls=K2(a.impressionUrls||[],J2);a.trackingParams&&(c.visualElement=g.js(a.trackingParams));c.elements=K2(a.elements||[],function(d,e){return mua(b,d,e)});
return c},M2=function(a){g.ZL.call(this,a);
this.B=this.u=null;this.o={};this.G={};this.F=this.A=null;this.M=[];a=a.O();this.L=g.Vy(a)||g.Xy(a);this.R=!0;this.H=0;this.C=new g.Ur(this);g.A(this,this.C);this.C.N(this.player,g.qC("creatorendscreen"),this.IH);this.C.N(this.player,"crx_creatorendscreen",this.JH);this.C.N(this.player,"resize",this.Wz);this.C.N(window,"focus",this.RN);this.load();var b=g.ve("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Me(this,function(){g.Ae(b)});
b.sheet&&(b.sheet.insertRule(".ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAIVBMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///91E4wTAAAACXRSTlMArBbpVOtYrReN+x2FAAAAAWJLR0QKaND0VgAAACFJREFUCNdjYCAWzIQAFBaZ6hgVYLKcJnBWGEyWvYGASwCXtBf7m4i3CQAAAABJRU5ErkJggg==) no-repeat center;background-size:18px;width:18px;height:18px}",0),b.sheet.insertRule(".ytp-ce-size-853 .ytp-ce-playlist-icon, .ytp-ce-size-1280 .ytp-ce-playlist-icon, .ytp-ce-size-1920 .ytp-ce-playlist-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJ1BMVEVMaXGzs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7Ozs7P///9RfzIKAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAyBs1FjAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0))},nua=function(a){return a.player.getVideoData().Wb?"current":a.L?"new":"current"},N2=function(a){return"creator-endscreen-editor"===a.player.O().playerStyle},O2=function(a,b,c){c=void 0===c?!0:c;
g.RR(a.player.app,"creatorendscreen",void 0);a.A&&(a.A.dispose(),a.A=null,a.F.dispose(),a.F=null);for(var d in a.o)a.o[d].dispose();a.o={};a.G={};0<a.M.length&&(a.M.forEach(function(l){l.dispose()}),a.M.length=0);
a.H=0;if((a.u=b)&&b.elements){c&&oua(a);c=[];d=new g.nC(b.startMs,0x7ffffffffffff,{id:"ytp-ce-in-endscreen",namespace:"creatorendscreen"});c.push(d);a.player.O().o||(a.A=new g.W({D:"div",I:"ytp-ce-shadow"}),g.NL(a.player,a.A.element,4),a.F=new g.PN(a.A,200));for(d=0;d<b.elements.length;++d){var e=b.elements[d],f=pua(a,e);a.o[e.id]=f;a.G[e.id]=e;g.NL(a.player,f.element,4);var k=new g.nC(e.startMs,e.endMs,{id:"ytp-ce-element-"+e.id,namespace:"creatorendscreen"});c.push(k);qua(a,f,e)}g.JL(a.player,c);
a.Wz()}},oua=function(a){var b=g.os(),c=g.qs();
c&&b&&a.u.visualElement&&g.Ls(c,b,a.u.visualElement)},pua=function(a,b){var c=null;
switch(b.type){case "VIDEO":c={D:"div",X:["ytp-ce-element","ytp-ce-video"],P:{tabindex:"0","aria-label":b.Ml||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-covering-image",P:P2(b)},{D:"div",I:"ytp-ce-covering-shadow-top"},{D:"a",I:"ytp-ce-covering-overlay",P:{href:Q2(a,b.targetUrl),tabindex:"-1"},K:[{D:"div",X:["ytp-ce-video-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],P:{dir:g.Pn(b.title||"")},W:b.title},{D:"div",I:"ytp-ce-video-duration",W:b.videoDuration}]}]};
c=new g.W(c);break;case "PLAYLIST":c={D:"div",X:["ytp-ce-element","ytp-ce-playlist"],P:{tabindex:"0","aria-label":b.Ml||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-covering-image",P:P2(b)},{D:"div",I:"ytp-ce-covering-shadow-top"},{D:"a",I:"ytp-ce-covering-overlay",P:{href:Q2(a,b.targetUrl),tabindex:"-1"},K:[{D:"div",X:["ytp-ce-playlist-title","yt-ui-ellipsis","yt-ui-ellipsis-2"],P:{dir:g.Pn(b.title||"")},W:b.title},{D:"div",I:"ytp-ce-playlist-count",K:[{D:"div",
I:"ytp-ce-playlist-icon"},{D:"div",I:"ytp-ce-playlist-count-text",W:b.playlistLength}]}]}]};c=new g.W(c);break;case "CHANNEL":c={D:"div",X:["ytp-ce-element","ytp-ce-channel",b.isSubscribe?"ytp-ce-channel-this":"ytp-ce-channel-that"],P:{tabindex:"0","aria-label":b.Ml||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-expanding-overlay",K:[{D:"div",I:"ytp-ce-expanding-overlay-hider"},{D:"div",I:"ytp-ce-expanding-overlay-background"},{D:"div",I:"ytp-ce-expanding-overlay-content",
K:[{D:"div",I:"ytp-ce-expanding-overlay-body",K:[{D:"div",I:"ytp-ce-expanding-overlay-body-padding",K:[{D:"a",X:["ytp-ce-channel-title","ytp-ce-link"],P:{href:Q2(a,b.targetUrl),target:"_blank",tabindex:"-1",dir:g.Pn(b.title||"")},W:b.title},b.subscribeButton?{D:"div",I:"ytp-ce-subscribe-container",K:[{D:"div",I:"ytp-ce-channel-subscribe"}]}:"",b.subscribersText?{D:"div",I:"ytp-ce-channel-subscribers-text",W:b.subscribersText}:"",b.metadata?{D:"div",X:["ytp-ce-channel-metadata","yt-ui-ellipsis","yt-ui-ellipsis-3"],
W:b.metadata}:""]}]}]}]},{D:"div",I:"ytp-ce-expanding-image",P:P2(b)}]};c=new g.W(c);var d=g.he(document,"div","ytp-ce-channel-subscribe",c.element)[0];if(b.subscribeButton&&b.channelId){g.J(d,"ytp-ce-subscribe-button");if(a.player.O().o){var e=null;var f=b.Zb.itct}else e="endscreen",f=null;e=new g.vR(b.subscribeButton.subscribeText,b.subscribeButton.subscribeCount,b.subscribeButton.unsubscribeText,b.subscribeButton.unsubscribeCount,b.subscribeButton.enabled,b.subscribeButton.classic,b.channelId,
!!b.subscribeButton.subscribed,e,f,b.subscribeButton.signinUrl,a.player);d.appendChild(e.element);a.M.push(e)}break;case "WEBSITE":c={D:"div",X:["ytp-ce-element","ytp-ce-website"],P:{tabindex:"0","aria-label":b.Ml||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-expanding-overlay",K:[{D:"div",I:"ytp-ce-expanding-overlay-hider"},{D:"div",I:"ytp-ce-expanding-overlay-background"},{D:"div",I:"ytp-ce-expanding-overlay-content",K:[{D:"div",I:"ytp-ce-expanding-overlay-body",
K:[{D:"div",I:"ytp-ce-expanding-overlay-body-padding",K:[{D:"div",I:"ytp-ce-website-title",P:{dir:g.Pn(b.title||"")},W:b.title},{D:"div",I:"ytp-ce-website-metadata",W:b.metadata},{D:"a",X:["ytp-ce-website-goto","ytp-ce-link"],P:{href:Q2(a,b.targetUrl),target:"_blank",tabindex:"-1"},W:b.callToAction}]}]}]}]},{D:"div",I:"ytp-ce-expanding-image",P:P2(b)},{D:"div",I:"ytp-ce-expanding-icon",P:rua(b.iconUrl)}]};c=new g.W(c);break;case "CREATOR_MERCHANDISE":c="",b.productPrice&&(c={D:"div",I:"ytp-ce-merchandise-price-container",
K:[{D:"div",I:"ytp-ce-merchandise-price",W:b.productPrice}]},b.additionalFeesText&&c.K.push({D:"div",I:"ytp-ce-merchandise-additional-fees",W:b.additionalFeesText})),c={D:"div",X:["ytp-ce-element","ytp-ce-merchandise"],P:{tabindex:"0","aria-label":b.Ml||"","aria-hidden":"true"},K:[{D:"div",I:"ytp-ce-element-shadow"},{D:"div",I:"ytp-ce-expanding-overlay",K:[{D:"div",I:"ytp-ce-expanding-overlay-hider"},{D:"div",I:"ytp-ce-expanding-overlay-background"},{D:"div",I:"ytp-ce-expanding-overlay-content",K:[{D:"div",
I:"ytp-ce-expanding-overlay-body",K:[{D:"div",I:"ytp-ce-expanding-overlay-body-padding",K:[{D:"div",I:"ytp-ce-merchandise-title",P:{dir:g.Pn(b.title||"")},W:b.title},c,{D:"div",I:"ytp-ce-merchandise-metadata",W:b.metadata},{D:"a",X:["ytp-ce-merchandise-goto","ytp-ce-link"],P:{href:Q2(a,b.targetUrl),target:"_blank",tabindex:"-1"},W:b.callToAction}]}]}]}]},{D:"div",I:"ytp-ce-expanding-image",P:P2(b)},{D:"div",I:"ytp-ce-merchandise-invideo-cta-container",K:[{D:"div",I:"ytp-ce-merchandise-invideo-cta",
W:b.callToAction}]}]},c=new g.W(c)}b.WG&&g.J(c.element,"ytp-ce-placeholder");return c},P2=function(a){if(a.Qx)var b=a.Qx.thumbnails;
return rua(b?b[b.length-1].url:null)},rua=function(a){return a?{style:"background-image: url("+a+")"}:{}},qua=function(a,b,c){function d(){k(1)}
function e(){k(-1)}
b.na("mouseenter",(0,g.x)(a.cu,a,b,c));b.na("mouseleave",(0,g.x)(a.Ou,a,b,c));a.player.O().o||b.na("click",(0,g.x)(function(l){g.J(l.element,"ytp-ce-element-hover")},a,b));
b.na("click",(0,g.x)(a.rB,a,c));b.na("keypress",(0,g.x)(a.rB,a,c));b.na("focus",(0,g.x)(function(l,m){this.cu(l,m)},a,b,c));
b.na("blur",(0,g.x)(function(l,m){this.Ou(l,m)},a,b,c));
b.na("touchstart",(0,g.x)(a.cu,a,b,c));var f=g.je("ytp-ce-expanding-overlay-hider",b.element);f&&b.N(f,"touchstart",function(l){l=l||window.event;l.cancelBubble=!0;l.stopPropagation&&l.stopPropagation();g.Hn(b.element,"ytp-ce-element-hover");g.Hn(b.element,"ytp-ce-force-expand")});
b.na("keydown",(0,g.x)(function(l,m){this.R=9==m.keyCode&&!m.shiftKey},a,b));
var k=(0,g.x)(function(l,m,n){this.H+=n;0<this.H?(g.J(l.element,"ytp-ce-force-expand"),R2(this,m.id,!0)):(g.Hn(l.element,"ytp-ce-force-expand"),g.Hn(l.element,"ytp-ce-element-hover"),R2(this,m.id,!1))},a,b,c);
c=(0,g.x)(function(l,m){m&&(l.na("blur",g.Ra(function(){"none"!=m.style.display&&a.R&&m.focus()})),l.N(m,"focus",d),l.N(m,"blur",e))},a,b);
c(g.je("ytp-sb-subscribe",b.element));c(g.je("ytp-sb-unsubscribe",b.element));b.na("focus",d);b.na("blur",e)},Q2=function(a,b){var c=a.player.O();
if(b){if(b.startsWith("//"))return c.protocol+":"+b;if(b.startsWith("/"))return g.yz(c)+b}else return"";return b},R2=function(a,b,c){a.A&&(c?a.F.show():a.F.hide());
for(var d in a.o)d!=b&&g.K(a.o[d].element,"ytp-ce-element-shadow-show",c)},S2=function(a,b,c){function d(){f||(e++,e==b.length&&(k.stop(),c&&c()))}
if(!b||0==b.length||N2(a))c&&c();else{b=sua(a,b);var e=0,f=!1,k=new g.I(function(){f=!0;c&&c()},1E3,a);
k.start();for(a=0;a<b.length;a++)g.qr(b[a],d)}},T2=function(a,b,c){S2(a,b.clickUrls,c);
(a=g.qs())&&b.SG&&g.Ms(a,b.visualElement)},sua=function(a,b){var c=a.player.getVideoData().clientPlaybackNonce,d=a.player.getCurrentTime().toFixed(2);
c={CPN:c,AD_CPN:c,MT:d};d=[];for(var e=0;e<b.length;e++)d.push(tua(b[e],c));return d},tua=function(a,b){return a.replace(/%5B[a-zA-Z_:]+%5D|\[[a-zA-Z_:]+\]/g,function(c){var d=unescape(c);
d=d.substring(1,d.length-1);return b[d]?escape(b[d]):c})},uua=function(a){return Array.isArray(a)&&a.length?a[0]:a},U2=function(a){return"string"===typeof a?a:""},V2=function(a,b,c){for(var d in b)if(b[d]==a)return a;
return c},wua=function(a){var b=vua;
if(null==a)return null;if(g.Ma(a)){var c=[];(0,g.y)(a,function(d){(d=b(d))&&c.push(d)});
return c}return(a=b(a))?[a]:[]},xua=function(a){this.externalId=a},yua=function(a,b,c,d){this.value=a;
this.target=b;this.showLinkIcon=c;this.o=d},W2=function(a){if(!a)return null;
var b=g.Dc(U2(a.value));b=g.Ac(b);if(!b)return null;var c=V2(a.target,zua,"current");if(null==c)a=null;else{var d=a.show_link_icon;a=new yua(b,c,"true"==d||"false"==d?"true"==d:!0,null!=a.pause_on_navigation?a.pause_on_navigation:!0)}return a},X2=function(a){return a.value?a.value:null},Aua=function(a,b,c,d){this.type=a;
this.trigger=b;this.url=c;this.subscribeData=d},vua=function(a){if(!a)return null;
var b=V2(a.type,Bua),c=V2(a.trigger,Cua),d=uua(a.url);d=W2(d?d:null);a=uua(a.subscribeData);var e=a?a:null;e?(a=U2(e.external_user_id),e=U2(e.subscription_token),a=a&&e?new xua(a):null):a=null;return b?new Aua(b,c,d,a):null},Y2=function(a,b,c,d,e){this.id=a;
this.type=b;this.style=c;this.o=d||[];this.data=e},Dua=function(a,b){return g.$a(a.o,b,void 0)},Eua=function(a,b){return a.id.replace(/[^a-z0-9-]/gi,"-")+"-"+b.toString()},Fua=function(a,b){this.merchant=a;
this.price=b},Gua=function(a){this.o=a},Hua=function(a,b,c){b&&(c?Z2(a,(0,g.Jc)(b,g.Ra(function(d,e){return g.hn(e,d)},c))):Z2(a,b))},Z2=function(a,b,c,d){var e=1,f=-1;
if(c){var k=!1;var l=function(){e--;e||k||(clearTimeout(f),k=!0,c())};
f=setTimeout(function(){k=!0;c()},1E3)}(0,g.y)(b||[],function(m){e++;
g.qr(m,l)});
d&&(e++,0!=d&&a.o.sendVideoStatsEngageEvent(d,l))},Iua=function(a,b,c,d,e,f,k){this.o=a;
this.A=b;this.B=c;this.videoData=d;this.logger=e;this.J=f;this.u=k},$2=function(a,b){this.o=a;
this.A=b},Lua=function(a,b){var c=[];
(0,g.y)(b.choices,function(k){c.push(Jua(b,k))},a);
var d={D:"ul",P:{role:"radiogroup"},K:c},e={};b.Kj&&(e["aria-label"]=g.KM("$POLL_TITLE - Fa\u00e7a login para votar.",{POLL_TITLE:b.title}));var f=["iv-card","iv-card-poll"];d=[{D:"div",I:"iv-card-content",K:[a3("h2",e,b.title),{D:"form",K:[{D:"fieldset",K:[d]}]}]}];b.Kj&&(f.push("iv-card-unavailable"),d.push({D:"div",X:["iv-card-sign-in"],K:[{D:"h2",W:"Quer votar?"},{D:"a",X:["iv-card-sign-in-button","iv-button"],P:{href:X2(b.Kj)},K:[{D:"span",X:["iv-button-content"],W:"Fazer login"}]}]}));f=new g.W({D:"div",
X:f,K:d});d=f.element;Kua(b,d);lua(a.o.o,d,g.Ra(a.B,b),a);(0,g.y)(g.ie("iv-card-poll-choice-input",d),function(k){this.o.o.na(k,"focus",g.Ra(this.u,!0));this.o.o.na(k,"blur",g.Ra(this.u,!1))},a);
b.Kj&&(d=g.je("iv-card-sign-in-button",d),a.A(d,b.Kj,b.id,b.Zb,b.Uc.click,5));return f},Mua=function(a,b,c){var d=["yt-badge",
"standalone-ypc-badge-renderer-icon",b.mP?"standalone-ypc-badge-renderer-icon-purchased":"standalone-ypc-badge-renderer-icon-available"],e={};d=b.VG&&b.jx?{D:"span",X:d,P:e,W:b.jx}:"";c={D:"div",X:["iv-card",c],K:[{D:"a",I:"iv-click-target",P:{href:X2(b.url)},K:[b3(b.Oj,d?{D:"div",I:"iv-card-image-text",K:[d,b.priceText]}:""),{D:"div",I:"iv-card-content",K:[{D:"h2",I:"iv-card-primary-link",W:b.title},c3(a,b)]}]}]};c=new g.W(c);d3(a,g.ie("iv-click-target",c.element),b,b.url);return c},e3=function(a){return a.customMessage?
a3("div","iv-card-message",a.customMessage):""},b3=function(a,b){var c="background-image: url("+a+");",d=[];
b&&d.push(b);return{D:"div",I:"iv-card-image",P:{style:c},K:d}},c3=function(a,b){if(!b.metaInfo||0==b.metaInfo.length)return"";
var c=[];(0,g.y)(b.metaInfo,function(d){c.push(a3("li","",d))},a);
return{D:"ul",I:"iv-card-meta-info",K:c}},Jua=function(a,b){return{D:"li",
I:Eua(a,b.index),K:[{D:"label",K:[{D:"input",I:"iv-card-poll-choice-input",P:{type:"checkbox",role:"radio",name:a.id.replace(/[^a-z0-9-]/gi,"-")+b.index.toString(),value:b.index.toString(),"data-poll-choice-index":b.index.toString()}},{D:"span",I:"iv-card-poll-choice-text",K:[{D:"span",I:"iv-card-poll-choice-percent"},a3("span",void 0,b.desc)]}]},{D:"div",I:"iv-card-poll-result",K:[{D:"div",I:"iv-card-poll-result-bar"}]}]}},a3=function(a,b,c){b?"string"===typeof b?b={"class":b}:Array.isArray(b)&&
(b={"class":b.join(" ")}):b={};
b.dir=g.Pn(c);return{D:a,P:b,W:c}},Nua=function(a){if(!a.customMessage)return"";
var b=["iv-card-action","iv-card-primary-link"],c={};a.Wn&&(b.push("iv-card-action-icon"),c.style="background-image: url("+a.Wn+");");c.dir=g.Pn(a.customMessage);var d=[{D:"span",W:a.customMessage}];a.showLinkIcon&&(d.push("\u00a0"),d.push({D:"span",I:"iv-card-link-icon"}));return{D:"div",X:b,P:c,K:d}},Kua=function(a,b){var c=0;
(0,g.y)(a.choices,function(m){c+=m.count});
c=c||1;for(var d=0;d<a.choices.length;d++){var e=a.choices[d],f=g.je(Eua(a,e.index),b);e=e.count/c;null==a.Ue&&(e=0);g.K(f.getElementsByTagName("label")[0],"iv-card-poll-choice-checked",a.Ue==d);f.getElementsByTagName("input")[0].checked=a.Ue==d;var k=Math.floor(100*e).toFixed(0),l=g.je("iv-card-poll-choice-percent",f);g.Ee(l,g.KM("$PERCENT%",{PERCENT:k}));f=g.je("iv-card-poll-result-bar",f);g.H(f,"transform","scaleX("+e.toFixed(2)+")")}g.K(b,"iv-card-poll-voted",null!=a.Ue);g.K(b,"iv-card-poll-expanded",
null!=a.Ue&&1<a.choices.length)},d3=function(a,b,c,d){d&&(0,g.y)(b,function(e){this.A(e,d,c.id,c.Zb,c.Uc.click,5)},a)},Oua=function(a){var b;
(b=a)&&!(b=1<a.length?"/"==a.charAt(0)&&"/"!=a.charAt(1):"/"==a)&&(b=a.replace(/^(https?:)?\/\//,""),b=b.split("/",1),b=!b||1>b.length||!b[0]?[]:b[0].toLowerCase().split(".").reverse(),b="com"==b[0]&&"youtube"==b[1]||"be"==b[0]&&"youtu"==b[1]);return b?-1==a.indexOf("/redirect?"):!1},Pua=function(a,b){return b?b:Oua(a)?"current":"new"},f3=function(a,b){g.z.call(this);
var c=this;this.Ma=a;this.context=b;this.gw=!1;this.ra=new Map;this.ma=new Map;this.context.J.addEventListener(g.qC("annotations_module"),function(d){(d=c.ra.get(d))&&d.apply(c)});
this.context.J.addEventListener("crx_annotations_module",function(d){(d=c.ma.get(d))&&d.apply(c)})},Qua=function(a,b,c,d,e){var f=X2(b);
if(f){var k=Pua(f,b.target),l=(0,g.x)(function(){b.o&&this.context.J.pauseVideo();var m=this.context.videoData.Wb||!1,n=g.eq(f||"");m&&n&&(n.v||n.list)?g.UT(this.context.J.app,n.v,c,n.list,!1,void 0):g.hO(f||"","current"==k?"_top":void 0,c)},a);
"new"==k&&(l(),l=null);Z2(a.context.logger,d,l,e);Oua(f)||(a=g.qs(),d=c.itct,a&&d&&g.Ms(a,g.js(d)))}},Rua=function(a){if(a.urlEndpoint&&a.urlEndpoint.url)return a.urlEndpoint.url;
if(a.watchEndpoint&&a.watchEndpoint.videoId){var b="/watch?v="+a.watchEndpoint.videoId;a.watchEndpoint.playlistId&&(b+="&list="+a.watchEndpoint.playlistId);a.watchEndpoint.index&&(b+="&index="+a.watchEndpoint.index);a.watchEndpoint.startTimeSeconds&&(b+="&t="+a.watchEndpoint.startTimeSeconds);return b}return null},g3=function(a,b,c){return{bz:(a.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
click:(c.loggingUrls||[]).map(function(d){return d.baseUrl}),
close:(b.dismissLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
jD:(b.impressionLoggingUrlsV2s||[]).map(function(d){return d.baseUrl}),
Sq:(b.clickLoggingUrlsV2s||[]).map(function(d){return d.baseUrl})}},j3=function(a,b,c){f3.call(this,b,c);
var d=this;this.u=a;this.ga=this.Ga=this.C=this.Ea=!1;this.ea=null;this.aa=new g.I(g.Ja,c.B.ob?4E3:3E3);g.A(this,this.aa);this.za=new g.I(g.Ja);g.A(this,this.za);this.H=new $2(c,(0,g.x)(this.ql,this),(0,g.x)(this.kp,this));this.U=new g.W({D:"div",I:"iv-drawer",P:{id:"iv-drawer"},K:[{D:"div",I:"iv-drawer-header",P:{"aria-role":"heading"},K:[{D:"span",I:"iv-drawer-header-text"},{D:"button",X:["iv-drawer-close-button","ytp-button"],P:{"aria-label":"Ocultar cards",tabindex:"0"}}]},{D:"div",I:"iv-drawer-content"}]});
g.A(this,this.U);this.F=this.U.element;this.ua=new g.PN(this.U,330);g.A(this,this.ua);this.Ca=g.je("iv-drawer-header-text",this.F);this.B=g.je("iv-drawer-content",this.F);this.A=[];this.Aa=this.T=this.G=this.fa=this.o=null;this.Z=[];this.addCueRange(0,1E3*c.videoData.lengthSeconds,"",function(){d.Ga&&h3(d,"YOUTUBE_DRAWER_AUTO_OPEN")},function(){(d.Ga=d.C)&&i3(d)});
this.R=this.M=this.ba=null;this.L=0},Sua=function(a,b){b.data.autoOpenMs&&a.addCueRange(b.data.autoOpenMs,0x8000000000000,"",function(){h3(a,"YOUTUBE_DRAWER_AUTO_OPEN")});
b.data.autoCloseMs&&a.addCueRange(b.data.autoCloseMs,0x8000000000000,"",function(){i3(a)});
var c=b.data.headerText;g.Ee(a.Ca,c);a.T&&a.T.setAttribute("title",c);a.ba=g.js(b.data.trackingParams);a.R=g.js(b.data.closeTrackingParams);a.M=g.js(b.data.iconTrackingParams)},Tua=function(a,b){var c=b.cardId?b.cardId:"cr:"+a.L;
if(b.content.simpleCardContentRenderer){if(!b.cueRanges.length)return;var d=b.content.simpleCardContentRenderer,e=b.teaser.simpleCardTeaserRenderer,f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.L,type:"simple",teaserText:g.S(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Zb:k3(a,c,b,d),sponsored:!1,Uc:g3(d,e,d.command),te:d.trackingParams?g.js(d.trackingParams):null,ne:e.trackingParams?
g.js(e.trackingParams):null,Pd:f&&f.trackingParams?g.js(f.trackingParams):null,imageUrl:l3(d.image.thumbnails,290).url,displayDomain:d.displayDomain?g.S(d.displayDomain):null,showLinkIcon:!!d.showLinkIcon,Wn:null,title:d.title?g.S(d.title):"",customMessage:d.callToAction?g.S(d.callToAction):"",url:d.command.urlEndpoint.url?W2({pause_on_navigation:!a.context.videoData.ya,target:"new",value:d.command.urlEndpoint.url}):null};m3(a,c)}else if(b.content.collaboratorInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.collaboratorInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.L,type:"collaborator",teaserText:g.S(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Zb:k3(a,c,b,d),sponsored:!1,Uc:g3(d,e,d.endpoint),te:d.trackingParams?g.js(d.trackingParams):null,ne:e.trackingParams?g.js(e.trackingParams):null,Pd:f&&f.trackingParams?
g.js(f.trackingParams):null,channelId:d.endpoint.browseEndpoint.browseId,customMessage:d.customText?g.S(d.customText):null,pC:l3(d.channelAvatar.thumbnails,290).url,title:d.channelName?g.S(d.channelName):"",metaInfo:[d.subscriberCountText?g.S(d.subscriberCountText):""],url:W2({pause_on_navigation:!a.context.videoData.ya,target:"new",value:d.endpoint.browseEndpoint.canonicalBaseUrl?d.endpoint.browseEndpoint.canonicalBaseUrl:"/channel/"+d.endpoint.browseEndpoint.browseId})};m3(a,c)}else if(b.content.playlistInfoCardContentRenderer){if(!b.cueRanges.length)return;
d=b.content.playlistInfoCardContentRenderer;e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.L,type:"playlist",teaserText:g.S(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Zb:k3(a,c,b,d),sponsored:!1,Uc:g3(d,e,d.action),te:d.trackingParams?g.js(d.trackingParams):null,ne:e.trackingParams?g.js(e.trackingParams):null,Pd:f&&f.trackingParams?g.js(f.trackingParams):
null,Oj:l3(d.playlistThumbnail.thumbnails,258).url,customMessage:d.customMessage?g.S(d.customMessage):null,playlistVideoCount:g.S(d.playlistVideoCount),title:d.playlistTitle?g.S(d.playlistTitle):"",metaInfo:[d.channelName?g.S(d.channelName):"",d.videoCountText?g.S(d.videoCountText):""],url:W2({pause_on_navigation:!a.context.videoData.ya,target:"new",value:Rua(d.action)})};m3(a,c)}else if(b.content.videoInfoCardContentRenderer){if(!b.cueRanges.length)return;d=b.content.videoInfoCardContentRenderer;
e=b.teaser.simpleCardTeaserRenderer;f=b.icon?b.icon.infoCardIconRenderer:null;c={id:c,timestamp:a.L,type:"video",teaserText:g.S(e.message),teaserDurationMs:parseInt(b.cueRanges[0].teaserDurationMs,10),startMs:parseInt(b.cueRanges[0].startCardActiveMs,10),autoOpen:!!b.autoOpen,Zb:k3(a,c,b,d),sponsored:!1,Uc:g3(d,e,d.action),te:d.trackingParams?g.js(d.trackingParams):null,ne:e.trackingParams?g.js(e.trackingParams):null,Pd:f&&f.trackingParams?g.js(f.trackingParams):null,Oj:l3(d.videoThumbnail.thumbnails,
258).url,videoDuration:d.lengthString?g.S(d.lengthString):null,customMessage:d.customMessage?g.S(d.customMessage):null,title:d.videoTitle?g.S(d.videoTitle):"",metaInfo:[d.channelName?g.S(d.channelName):"",d.viewCountText?g.S(d.viewCountText):""],isLiveNow:!!d.badge,url:W2({pause_on_navigation:!a.context.videoData.ya,target:"new",value:Rua(d.action)})};m3(a,c)}a.L++},l3=function(a,b){for(var c=-1,d=-1,e=0;e<a.length;e++){if(a[e].height==b||290==a[e].width)return a[e];
((a[e].height||0)<b||290>(a[e].width||0))&&(0>c||(a[c].height||0)<(a[e].height||0)||(a[c].width||0)<(a[e].width||0))?c=e:((a[e].height||0)>=b||290<=(a[e].width||0))&&(0>d||(a[d].height||0)>(a[e].height||0)||(a[d].width||0)>(a[e].width||0))&&(d=e)}return a[0<=d?d:c]},k3=function(a,b,c,d){return{feature:c.feature?c.feature:"cards",
src_vid:a.context.videoData.videoId,annotation_id:b,ei:a.context.videoData.eventId,itct:d.trackingParams}},Vua=function(a,b){var c=Uua(a,b);
c&&(c==a.o&&(a.o=null),a.u.removeCueRange(c.card.id),g.Ae(c.Xr),g.gb(a.A,c),a.Zn(),n3(a))},h3=function(a,b,c){if(!a.C){a.ua.show();
a.fa=new g.I(function(){g.J(a.context.J.getRootNode(),g.VM.IV_DRAWER_OPEN)},0);
a.fa.start();a.ea=g.hp(a.B,"mousewheel",(0,g.x)(a.cM,a));a.C=!0;var d=g.qs();d&&a.ba&&a.R&&A2(d,[a.ba,a.R]);var e={TRIGGER_TYPE:b};(0,g.y)(a.A,function(f){f.Cz||(f.Cz=!0,Hua(a.context.logger,f.card.Uc.bz,e));d&&A2(d,[f.card.te])});
z2(a.u);c&&(a.G=new g.I(function(){a.wa=a.T;a.Aa.focus()},330),a.G.start())}},i3=function(a){a.C&&(a.ua.hide(),g.ip(a.ea),a.ea=null,g.Hn(a.context.J.getRootNode(),g.VM.IV_DRAWER_OPEN),a.C=!1,z2(a.u),a.G&&a.G.stop(),a.G=new g.I(function(){a.wa&&(a.wa.focus(),a.wa=null)},330),a.G.start())},Wua=function(a){var b=g.je("iv-drawer-close-button",a.F);
a.context.o.na(b,"click",a.eF,a);a.context.o.na(a.B,"touchend",function(){a.aa.start()});
a.context.o.na(a.B,"scroll",a.rF,a);a.context.u.subscribe("onHideControls",function(){a.ga=!0});
a.context.u.subscribe("onShowControls",function(){a.ga=!1});
a.context.u.subscribe("onVideoAreaChange",function(){a.ga=g.Fn(a.u.getRootNode(),"ytp-autohide")});
a.Z.push(g.So("iv-button-shown",a.cH,a));a.Z.push(g.So("iv-button-hidden",a.bH,a));a.Z.push(g.So("iv-teaser-shown",a.fH,a));a.Z.push(g.So("iv-teaser-hidden",a.eH,a));a.Z.push(g.So("iv-teaser-clicked",a.dH,a))},m3=function(a,b){a.Ea||(g.Gn(a.xa(),[g.VM.STOP_EVENT_PROPAGATION,
"iv-drawer-manager"]),g.NL(a.u,a.F,5),Wua(a),a.T=g.je("ytp-cards-button",a.u.getRootNode()),a.Aa=g.je("iv-drawer-close-button",a.F),a.Ea=!0);Vua(a,b.id);var c=Xua(a,b);if(c){var d={card:b,Xr:c.element,Cz:!1},e=Yua(a,d);g.pb(a.A,e,0,d);c.ca(a.B,e);a.Zn();b.autoOpen?a.addCueRange(b.startMs,0x8000000000000,b.id,g.Ra(a.HO,d)):(c=1E3*a.context.J.getCurrentTime(),5E3>c&&c>b.startMs&&a.VC(d),a.addCueRange(b.startMs,b.startMs+1,b.id,g.Ra(a.VC,d)),n3(a))}},Xua=function(a,b){switch(b.type){case "simple":var c=
a.H;
var d=b.displayDomain?{D:"div",I:"iv-card-image-text",W:b.displayDomain}:"";var e=Nua(b);d={D:"div",X:["iv-card"],K:[{D:"a",I:"iv-click-target",P:{href:X2(b.url)},K:[b3(b.imageUrl,d),{D:"div",I:"iv-card-content",K:[a3("h2",void 0,b.title),e]}]}]};d=new g.W(d);d3(c,g.ie("iv-click-target",d.element),b,b.url);return d;case "collaborator":return c=a.H,d={D:"div",X:["iv-card","iv-card-channel"],K:[{D:"a",X:["iv-click-target"],P:{href:X2(b.url),"data-ytid":b.channelId},K:[b3(b.pC),{D:"div",I:"iv-card-content",
K:[e3(b),{D:"h2",I:"iv-card-primary-link",W:b.title},c3(c,b)]}]}]},d=new g.W(d),d3(c,g.ie("iv-click-target",d.element),b,b.url),d;case "episode":return Mua(a.H,b,"iv-card-episode");case "movie":return Mua(a.H,b,"iv-card-movie");case "playlist":return c=a.H,d={D:"div",X:["iv-card","iv-card-playlist"],K:[{D:"a",I:"iv-click-target",P:{href:X2(b.url)},K:[b3(b.Oj,{D:"div",I:"iv-card-image-overlay",K:[{D:"span",I:"iv-card-playlist-video-count",W:b.playlistVideoCount}]}),{D:"div",I:"iv-card-content",K:[e3(b),
a3("h2","iv-card-primary-link",b.title),c3(c,b)]}]}]},d=new g.W(d),d3(c,g.ie("iv-click-target",d.element),b,b.url),d;case "poll":return Lua(a.H,b);case "productListing":c=a.H;var f=!g.db(b.offers);d=["iv-card"];e="";var k=Nua(b);f&&(d.push("iv-card-product-listing"),e="iv-card-primary-link",f=b.offers[0],k=[],f.price&&k.push({D:"div",I:"iv-card-offer-price",W:f.price}),f.merchant&&k.push({D:"div",I:"iv-card-offer-merchant",W:f.merchant}),k={D:"div",K:k});d={D:"div",X:d,P:{tabindex:"0"},K:[{D:"a",
X:["iv-card-image","iv-click-target"],P:{style:"background-image: url("+b.imageUrl+");",href:X2(b.url),"aria-hidden":"true",tabindex:"-1"}},{D:"div",I:"iv-card-content",K:[b.sponsored?{D:"div",I:"iv-card-sponsored",K:["Patrocinado",{D:"div",I:"iv-ad-info-container",K:[{D:"div",I:"iv-ad-info",W:"{{adInfo}}"},{D:"div",I:"iv-ad-info-icon-container",K:[{D:"div",I:"iv-ad-info-icon"},{D:"div",I:"iv-ad-info-callout"}]}]}]}:"",{D:"a",I:"iv-click-target",P:{href:X2(b.url)},K:[a3("h2",e,b.title),k]}]}]};d=
new g.W(d);e=g.ve("span");g.Ee(e,"Voc\u00ea v\u00ea este produto porque achamos que ele \u00e9 relevante para o v\u00eddeo. O Google pode ser compensado pelo comerciante.");d.xb(e,"adInfo");d3(c,g.ie("iv-click-target",d.element),b,b.url);return d;case "video":return c=a.H,d=b.isLiveNow?{D:"span",X:["yt-badge","yt-badge-live"],W:"AO VIVO AGORA"}:"",d={D:"div",X:["iv-card","iv-card-video"],K:[{D:"a",I:"iv-click-target",P:{href:X2(b.url)},K:[b3(b.Oj,b.videoDuration?{D:"span",I:"iv-card-video-duration",
W:b.videoDuration}:""),{D:"div",I:"iv-card-content",K:[e3(b),a3("h2","iv-card-primary-link",b.title),c3(c,b),d]}]}]},d=new g.W(d),d3(c,g.ie("iv-click-target",d.element),b,b.url),d}return null},Yua=function(a,b){if(0==a.A.length)return 0;
var c=g.ab(a.A,function(d){return b.card.startMs>d.card.startMs||b.card.startMs==d.card.startMs&&b.card.timestamp>=d.card.timestamp?!0:!1});
return-1==c?0:c+1},Zua=function(a){return a.o?"productListing"==a.o.card.type:(0,g.zi)(a.A,function(b){return"productListing"==b.card.type})},n3=function(a){g.K(a.u.getRootNode(),"ytp-cards-shopping-active",Zua(a))},$ua=function(a,b){if(a.U.Ka()){var c=new F2([0,
a.B.scrollTop],[0,b.Xr.offsetTop],600,fua);a.context.A.na(c,"animate",function(d){a.B.scrollTop=d.y});
a.context.A.na(c,"finish",function(d){a.B.scrollTop=d.y});
c.play()}else g.UM(a.U,!0),a.B.scrollTop=b.Xr.offsetTop,g.UM(a.U,!1)},o3=function(a){return a.o&&a.o.card?a.o.card:a.A[0]&&a.A[0].card?a.A[0].card:null},Uua=function(a,b){return g.$a(a.A,function(c){return c.card.id==b})},p3=function(a,b,c){f3.call(this,a,b);
this.annotation=c;this.isActive=!1},ava=function(a){var b=a.annotation.data;
"start_ms"in b&&"end_ms"in b&&a.addCueRange(a.annotation.data.start_ms,a.annotation.data.end_ms,a.annotation.id,function(){a.show()},function(){a.hide()})},q3=function(a,b,c){p3.call(this,a,b,c);
this.u=null;this.G=!1;this.A=null;this.B=!1;this.o=this.F=this.C=null},r3=function(a,b,c){p3.call(this,a,b,c);
this.M=this.C=this.L=!1;this.G=5E3;this.B=null;this.H=g.ue("DIV","iv-promo-contents");this.u=this.A=this.o=null;this.F=new g.I(function(){this.o.setAttribute("aria-hidden",!0);g.Sh(this.A,!1);g.Sh(this.u,!0)},700,this);
g.A(this,this.F)},bva=function(a){var b=a.annotation.data;
if("cta"==a.annotation.style)var c=6;else if("video"==a.annotation.style||"playlist"==a.annotation.style)c=7;a.G=b.collapse_delay_ms||a.G;var d=["iv-promo","iv-promo-inactive"];a.xa().setAttribute("aria-hidden",!0);a.xa().setAttribute("aria-label","Promo\u00e7\u00e3o");a.xa().tabIndex=0;var e=a.annotation.Ac(),f=b.image_url;if(f){var k=g.ue("DIV",["iv-promo-img","iv-click-target"]);f=g.ue("IMG",{src:f,"aria-hidden":"true"});k.appendChild(f);b.video_duration&&!b.is_live?(f=g.ue("SPAN","iv-promo-video-duration",
b.video_duration),k.appendChild(f)):b.playlist_length&&(f=g.ue("SPAN","iv-promo-playlist-length",b.playlist_length.toString()),k.appendChild(f));e&&a.ql(k,e,a.annotation.id,b.session_data,void 0,c)}e?(f=g.ue("A","iv-promo-txt"),g.dd(f,X2(e)),a.o=f):a.o=g.ue("DIV","iv-promo-txt");switch(a.annotation.style){case "cta":case "website":var l=g.ue("P",null,g.ue("STRONG",null,b.text_line_1));var m=g.ue("P",null,g.ue("SPAN","iv-promo-link",b.text_line_2));if(f=b.text_line_3){d.push("iv-promo-website-card-cta-redesign");
g.P(a.context.B.experiments,"web_action_cta_larger_ui")&&d.push("iv-promo-website-card-cta-larger-ui");var n=g.ue("BUTTON",["iv-promo-round-expand-icon","ytp-button"]);f=g.ue("BUTTON",["iv-button","iv-promo-button"],g.ue("SPAN","iv-button-content",f));var q=g.ue("DIV","iv-promo-button-container");q.appendChild(f);e&&a.ql(a.xa(),e,a.annotation.id,b.session_data,void 0,c)}g.J(a.o,"iv-click-target");e&&a.ql(a.o,e,a.annotation.id,b.session_data,void 0,c);break;case "playlist":case "video":l=g.ue("P",
null,g.ue("SPAN",null,b.text_line_1)),m=g.ue("P",null,g.ue("STRONG",null,b.text_line_2)),b.is_live&&(l=m,m=g.ue("SPAN",["yt-badge","iv-promo-badge-live"],"AO VIVO AGORA")),g.J(a.o,"iv-click-target"),e&&a.ql(a.o,e,a.annotation.id,b.session_data,void 0,c),d.push("iv-promo-video")}l&&a.o.appendChild(l);m&&a.o.appendChild(m);a.H.appendChild(a.o);q&&a.H.appendChild(q);c=g.ue("DIV","iv-promo-actions");a.u=g.ue("BUTTON",["iv-promo-expand","ytp-button"]);a.u.title="Expandir";a.context.o.na(a.u,"click",g.Ra(a.nt,
5E3),a);c.appendChild(a.u);g.Sh(a.u,!1);a.context.o.na(a.xa(),"mouseover",a.nG,a);a.context.o.na(a.xa(),"mouseout",a.mG,a);a.context.o.na(a.xa(),"touchend",g.Ra(a.nt,5E3),a);a.A=g.ue("BUTTON",["iv-promo-close","ytp-button"]);a.A.title="Fechar";a.context.o.na(a.A,"click","cta"==a.annotation.style&&b.text_line_3?a.fG:a.eG,a);c.appendChild(a.A);g.Gn(a.xa(),d);k&&(a.xa().appendChild(k),n&&k.appendChild(n));a.xa().appendChild(a.H);a.xa().appendChild(c)},cva=function(a){a.C||a.M||a.B||(g.J(a.xa(),"iv-promo-collapsed"),
a.C=!0,a.F.start())},dva=function(a){a.F.stop();
a.C&&(g.In(a.xa(),["iv-promo-collapsed","iv-promo-collapsed-no-delay"]),a.C=!1,a.o&&a.o.removeAttribute("aria-hidden"),g.Sh(a.u,!1),g.Sh(a.A,!0))},eva=function(a,b){a.B||(a.B=g.$f(function(){s3(this);
cva(this)},b,a))},s3=function(a){a.B&&(g.v.clearTimeout(a.B),a.B=null)},t3=function(a){g.ZL.call(this,a);
this.L=!1;this.M=0;this.G={};this.Z=new Gua(a);this.C=new g.Ur(this);g.A(this,this.C);this.F=this.A=null;this.C.N(this.player,"onVideoAreaChange",(0,g.x)(this.S,this,"onVideoAreaChange"));this.C.N(this.player,"onHideControls",(0,g.x)(this.S,this,"onHideControls"));this.C.N(this.player,"onShowControls",(0,g.x)(this.S,this,"onShowControls"));this.C.N(this.player,"resize",(0,g.x)(this.S,this,"resize"));this.C.N(this.player,"presentingplayerstatechange",(0,g.x)(this.S,this,"presentingplayerstatechange"));
this.subscribe("presentingplayerstatechange",this.xM,this);this.subscribe("resize",this.iq,this);this.player.O().M.subscribe("vast_info_card_add",this.bC,this);this.U=new g.Ur(this);g.A(this,this.U);this.T=g.ue("DIV","video-custom-annotations");this.u=new g.W({D:"div",X:["ytp-player-content","ytp-iv-player-content"]});g.A(this,this.u);g.NL(this.player,this.u.element,4);this.u.hide();this.B=new g.W({D:"div",X:["ytp-iv-video-content"]});g.A(this,this.B);g.xe(this.B.element,g.ue("DIV","video-annotations",
this.T));this.H=this.o=null;this.R=[];fva(this)&&this.load();var b=g.ve("STYLE");(document.getElementsByTagName("HEAD")[0]||document.body).appendChild(b);g.Me(this,function(){g.Ae(b)});
if(a=b.sheet)a.insertRule(".iv-promo .iv-promo-contents .iv-promo-txt .iv-promo-link:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUBAMAAAB/pwA+AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAHlBMVEVMaXH////////////////////////////////////Z6AnKAAAACXRSTlMA+/A2IuI1mJIldm0CAAAAAWJLR0QB/wIt3gAAAEVJREFUCNdjYGCYCQUMBJlACOIzIDElIcyZkwxgojOVWWDMSQauMKYySySUOSnBdSaUOZ0lEsac2YqwYiZ+JhwgM7E5HACgzVCI/YJ59AAAAABJRU5ErkJggg==) no-repeat center;background-size:10px;width:10px;height:10px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-close:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAkAAAAJBAMAAAASvxsjAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAVaQDpaimqQbl5rjXUFUAAAABYktHRAH/Ai3eAAAAPUlEQVQI12MQMmAwEmDwDmaOTmAw39663YCBuXp2MQMDQ+fOBgYG5ujVwQwMptvbgeLaxczVCQwiBgxmAgBkXg1FN5iwiAAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",
0),a.insertRule(".iv-promo .iv-promo-actions .iv-promo-expand:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAQAAAAJBAMAAADnQZCTAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXHMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMzMz////eMKB4AAAAC3RSTlMAOpE7k5Uvj5kpfRaQSaQAAAABYktHRAsf18TAAAAAHklEQVQI12MQYGBQZmBwTWCo0GSo6AKRQDZQRIABADXXA/UkIpvtAAAAAElFTkSuQmCC) no-repeat center;background-size:4px 9px;width:4px;height:9px}",0),a.insertRule(".iv-promo-website-card-cta-redesign .iv-promo-round-expand-icon:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAADAAAAAwCAQAAAD9CzEMAAAAAmJLR0QA/4ePzL8AAAAJcEhZcwAACxMAAAsTAQCanBgAAAAHdElNRQfgCgUUEztsNfqrAAAAXklEQVRYw+3Uuw2AQAwEUUNXfBpDIvBRMhQwJJAScNrA0r4CdiQHjjAzK4NGKucPAFmCnZcmwcTphBNO9CTGH4VB+/Zm6YlYis9fhedXz38FNvFriCCl808iw8ysrBu65gCeuV/CfgAAAABJRU5ErkJggg==) no-repeat center;background-size:18px 18px;width:18px;height:18px}",
0),a.insertRule(".iv-card-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABIAAAASBAMAAACk4JNkAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAGFBMVEVMaXG7u7u7u7u7u7u7u7u7u7u7u7v///+WKTAlAAAABnRSTlMAFdQWbGj9GiOuAAAAAWJLR0QHFmGI6wAAAEhJREFUCNdjYACBNCBgQGMxMKrBWEJJaRAJRjVlKEsoSQDIAqtSZICwgEIQFkgIZBRECMxiBqsCsVjAqsCygQwwFgMeFgQgswBg2xjLrfC4mgAAAABJRU5ErkJggg==) no-repeat center;background-size:9px;width:9px;height:9px}",0),a.insertRule(".iv-card-playlist-video-count:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABgAAAAYBAMAAAASWSDLAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAJFBMVEVMaXH///////////////////////////////////////////9tKdXLAAAAC3RSTlMAvDeyLvxYtDK9Ogx4T1QAAAABYktHRAH/Ai3eAAAAK0lEQVQY02NgoBjshgO8HJoYwKiAMGAD92YHJM7uMCTO9gaEHs4FlPuZAQC8Fj8x/xHjxwAAAABJRU5ErkJggg==) no-repeat center;background-size:24px;width:24px;height:24px}",
0),a.insertRule(".iv-drawer-close-button:after {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAwAAAAMAgMAAAArG7R0AAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAACVBMVEVMaXH////////OZTV/AAAAAnRSTlMAoKBFbtAAAAABYktHRAH/Ai3eAAAAKUlEQVQI12MIYGBlSGGQBMIUBjbHCQyM0xwYGDIZwBjEBomB5EBqgGoBolQGzYuy51cAAAAASUVORK5CYII=) no-repeat center;background-size:12px;width:12px;height:12px}",0),a.insertRule(".iv-ad-info-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAsAAAALCAMAAACecocUAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAVFBMVEVMaXGUlJSYmJiZmZmYmJiXl5eZmZmZmZmWlpaVlZWOjo6ZmZmSkpKXl5eYmJiYmJiZmZmZmZmZmZmZmZmYmJiJiYmXl5eZmZmYmJiWlpaZmZn///+81lbeAAAAGnRSTlMAE5DM80DliTMMEjccWIM5p1UjaTQNgB5cLlr5mgUAAAABYktHRBsCYNSkAAAAVElEQVQI102NRw7AIBADhw7ppIf/PzQLJ/ZgWSNrFlDaWKMVcs6HmGLwTqjEME6CFDrAXBYIGhNh3TJEg02wHydctvFc7sbrvnXZV8/zfs3T+7u/P7CrAso35YfPAAAAAElFTkSuQmCC) no-repeat center;background-size:11px;width:11px;height:11px}",
0),a.insertRule(".annotation-close-button {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABAAAAAQBAMAAADt3eJSAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAALVBMVEVMaXEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/Pz9aWloBAQGZmZlbW1v///+X9wUzAAAACHRSTlMANprf+g6lyRmB9hUAAAABYktHRA5vvTBPAAAAWUlEQVQI12NgYBAycVZkAIKwDiBIZWBgrQAx2gMY2DrAIIFBomPWju6VHY0MGh1rbu891dHEYNGx9+yd2x3NDB4d3XfO7uhoQTDgUnDFcO1wA+FWwC2FOQMAdKg6tUSAFEAAAAAASUVORK5CYII=) no-repeat center}",0),a.insertRule(".annotation-link-icon {background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACIAAAAiCAMAAAANmfvwAAAABGdBTUEAALGPC/xhBQAAACBjSFJNAAB6JgAAgIQAAPoAAACA6AAAdTAAAOpgAAA6mAAAF3CculE8AAAAUVBMVEVMaXH////////////////////////////////////////////////////////////////////////////////////////////////////////JzkR1AAAAGnRSTlMAfXf+c3xsdGdv/GJoXPtXXflSVk5L7DBH9VeFfsQAAAABYktHRAH/Ai3eAAAAgElEQVQ4y93SSQ6AIAwFULSOOOJs739Qf9SF0VA2uNCu+psHaQJK7cVCqY+Rg92PXA++Q84KnCR03UIRJrFEKMEgZYFQhpyzQHSBWJJAdIVUENtJ3SC0mu3EdOh7zXZiBrRdzQLJ0Y1GfOlpVstD3HaZktX9X/gvRCxvxL6FR7IBS1RTM5xIpLoAAAAASUVORK5CYII=) no-repeat center}",
0)},gva=function(){var a=g.ue("DIV",["annotation",
"annotation-type-custom"]);g.Sh(a,!1);return a},hva=function(a){switch(a){case "annotation-editor":case "live-dashboard":return!0}return!1},fva=function(a){var b=a.player.O();
a=a.player.getVideoData();return 1==(b.annotationsLoadPolicy||a.annotationsLoadPolicy)&&!a.QD||b.M.get(a.videoId)||g.QB(a)||g.RB(a)?!0:!1},iva=function(a,b){var c=!b.isCued()&&!g.U(b,1024);
g.UM(a.u,c);g.UM(a.B,c)},jva=function(a,b,c){a.L=!0;
a.F=g.wq(b,c)},kva=function(a,b){for(var c={},d=0;d<b.attributes.length;d++){var e=b.attributes[d];
c[e.name]=e.nodeValue}for(d=0;d<b.childNodes.length;d++)if(e=b.childNodes[d],g.Oa(e)&&1==e.nodeType){if(c[e.tagName])var f=c[e.tagName];else if("data"==e.tagName){0<e.childNodes.length&&(f=e.childNodes[0].nodeValue,c[e.tagName]="string"==typeof f?f.trim():f);continue}else f=[],c[e.tagName]=f;e&&"TEXT"==e.tagName?1==e.childNodes.length&&3==e.childNodes[0].nodeType?f.push(e.childNodes[0].nodeValue):f.push(""):e&&f.push(kva(a,e))}return c},lva=function(a,b,c){return!(a.loaded&&a.M==b&&a.player.getVideoData().videoId==
c)},ova=function(a){var b=a.player.getVideoData();
if(b.re){var c=a.player.O().M.get(b.videoId);if(c){var d={format:"XML",oe:{},method:"POST",withCredentials:!0};d.Dd=(0,g.x)(function(e,f,k){lva(this,e,f)||(e=g.qq(k)&&k.responseXML?k.responseXML:null)&&u3(this,e)},a,a.M,b.videoId);
g.yp()&&(d.Dd=mva(a,d.Dd));d.yb={ic_only:"1"};nva(d,c);a.L=!0;g.wq(b.re,d)}}},nva=function(a,b){a.method="POST";
a.yb=a.yb||{};b.eo&&(a.yb.ic_coll=b.eo);b.fo&&(a.yb.ic_xml=b.fo);b.xn&&(a.yb.ic_track=b.xn)},pva=function(a){var b=new g.W({D:"div"});
g.Sh(b.element,!1);var c=new j3(a.player,b.element,v3(a));g.A(c,b);b.ca(a.u.element);c.kn();return c},v3=function(a){if(!a.H){var b=new I2(a);
g.A(a,b);var c=new g.z1(a);g.A(a,c);a.H=new Iua(b,c,a.player.O(),a.player.getVideoData(),a.Z,a.player,a.si)}return a.H},u3=function(a,b){var c=!1,d=b.getElementsByTagName("annotations");
if(d&&!(1>d.length)&&(d=d[0].getAttribute("itct"))){var e=g.qs();if(e){var f=g.os();f&&g.Gs(g.Bo("use_default_events_client")?void 0:g.dr,e,f,[g.js(d)])}}d=b.getElementsByTagName("annotation");for(e=0;e<d.length;e++){var k=kva(a,d[e]);f=null;try{if(k){var l=k.id,m=/.+/;var n="string"===typeof l&&null!=m&&null!=l&&l.match(m)?l:"";var q=V2(k.type,qva),t=V2(k.style,rva),u=U2(k.data),w=0!=u.length?JSON.parse(u):{},B=wua(k.action);f=n&&q?new Y2(n,q,t,B,w):null}else f=null}catch(ba){}if(f){a:{switch(f.type){case "branding":case "promotion":k=
!0;break a}k=!1}if(k){k=a;m=f;var D=gva(),E=null;switch(m.type){case "branding":if(k.player.O().Ga)break;k.u.element.appendChild(D);E=new q3(D,v3(k),m);break;case "promotion":g.NL(k.player,D,4),E=new r3(D,v3(k),m)}E&&E.kn();if(k=E)g.A(a,k),a.G[f.id]=k}else if("card"==f.type||"drawer"==f.type){a.o||(a.o=pva(a),g.A(a,a.o));if("card"==f.type){if(c=a.o,E=f&&f.data&&f.data.card_type)switch(k=f.data.tracking||{},k={bz:k.impression,click:k.click,close:k.close,jD:k.teaser_impression,Sq:k.teaser_click},m=
f.data.tracking_params||{},D=null,E){case "collaborator":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Zb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Uc:k,te:m.card?g.js(m.card):null,ne:m.teaser?g.js(m.teaser):null,Pd:m.icon?g.js(m.icon):null,channelId:f.data.channel_id,customMessage:f.data.custom_message?f.data.custom_message:null,pC:f.data.image_url,
title:f.data.title,metaInfo:f.data.meta_info,url:W2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};m3(c,f);break;case "episode":case "movie":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Zb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Uc:k,te:m.card?g.js(m.card):null,ne:m.teaser?g.js(m.teaser):null,
Pd:m.icon?g.js(m.icon):null,Oj:f.data.image_url,jx:f.data.badge_symbol||"",priceText:f.data.price_text||"",title:f.data.title,metaInfo:f.data.meta_info,VG:!!f.data.is_paygated,mP:!!f.data.user_has_entitlement,url:W2({target:f.data.target||"new",value:f.data.url})};m3(c,f);break;case "playlist":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Zb:f.data.session_data||
{},sponsored:f.data.sponsored||!1,Uc:k,te:m.card?g.js(m.card):null,ne:m.teaser?g.js(m.teaser):null,Pd:m.icon?g.js(m.icon):null,Oj:f.data.image_url,playlistVideoCount:f.data.playlist_video_count,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,url:W2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};m3(c,f);break;case "poll":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,
teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Zb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Uc:k,te:m.card?g.js(m.card):null,ne:m.teaser?g.js(m.teaser):null,Pd:m.icon?g.js(m.icon):null,title:f.data.title,choices:f.data.choices,Ue:f.data.hasOwnProperty("old_vote")?f.data.old_vote:null,Kj:f.data.signin_url?W2({target:"current",value:f.data.signin_url}):null,xP:f.data.hasOwnProperty("xsrf_token")?f.data.xsrf_token:null};m3(c,f);break;case "productListing":f.data.signin_url&&
(D=W2({target:"current",value:f.data.signin_url}));E=[];for(var F=f.data.offers||[],G=0;G<F.length;G++)E.push(new Fua(g.ld(F[G].merchant),g.ld(F[G].price)));f={CU:!1,id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Zb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Uc:k,te:m.card?g.js(m.card):null,ne:m.teaser?g.js(m.teaser):null,Pd:m.icon?g.js(m.icon):null,
imageUrl:f.data.image_url,displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,Wn:f.data.button_icon_url?f.data.button_icon_url:null,title:f.data.title,customMessage:f.data.custom_message?f.data.custom_message:null,url:W2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url}),Kj:D,aV:f.data.signin_title?f.data.signin_title:null,ZU:f.data.signin_message?f.data.signin_message:null,offers:E};m3(c,f);break;case "simple":f=
{id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Zb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Uc:k,te:m.card?g.js(m.card):null,ne:m.teaser?g.js(m.teaser):null,Pd:m.icon?g.js(m.icon):null,imageUrl:f.data.image_url,displayDomain:f.data.display_domain?f.data.display_domain:null,showLinkIcon:!!f.data.show_link_icon,Wn:f.data.button_icon_url?f.data.button_icon_url:
null,title:f.data.title,customMessage:f.data.custom_message?f.data.custom_message:null,url:W2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})};m3(c,f);break;case "video":f={id:f.id,timestamp:f.data.timestamp||0,type:f.data.card_type,teaserText:f.data.teaser_text,teaserDurationMs:f.data.teaser_duration_ms,startMs:f.data.start_ms,autoOpen:f.data.auto_open||!1,Zb:f.data.session_data||{},sponsored:f.data.sponsored||!1,Uc:k,te:m.card?g.js(m.card):null,ne:m.teaser?
g.js(m.teaser):null,Pd:m.icon?g.js(m.icon):null,Oj:f.data.image_url,videoDuration:f.data.video_duration||null,customMessage:f.data.custom_message?f.data.custom_message:null,title:f.data.title,metaInfo:f.data.meta_info,isLiveNow:!!f.data.is_live_now,url:W2({pause_on_navigation:f.data.pause_on_navigation,target:f.data.target||"new",value:f.data.url})},m3(c,f)}}else Sua(a.o,f);c=!0}}}c&&(z2(a.player),a.iq())},sva=function(a,b){var c=!1;
a.o||(a.o=pva(a),g.A(a,a.o));for(var d=g.p(b.cards||[]),e=d.next();!e.done;e=d.next())Tua(a.o,e.value.cardRenderer),c=!0;c&&(c=a.o,d=b.headerText?g.S(b.headerText):"",g.Ee(c.Ca,d),c.T&&c.T.setAttribute("title",d),c.ba=b.trackingParams?g.js(b.trackingParams):null,c.R=b.closeButton.infoCardIconRenderer.trackingParams?g.js(b.closeButton.infoCardIconRenderer.trackingParams):null,c.M=b.icon.infoCardIconRenderer.trackingParams?g.js(b.icon.infoCardIconRenderer.trackingParams):null,z2(a.player),a.iq())},
tva=function(a,b,c,d,e){if(!a.player.O().Ga){var f=[];
b.navigationEndpoint&&b.navigationEndpoint.browseEndpoint&&b.navigationEndpoint.browseEndpoint.browseId&&f.push(new Aua("openUrl","click",new yua("/channel/"+b.navigationEndpoint.browseEndpoint.browseId,"new",!0,!0),null));var k=b.watermark.thumbnails[0];d={channel_name:b.channelName,end_ms:b.endTimeMs,image_height:k.height,image_type:1,image_url:k.url,image_width:k.width,is_mobile:!1,session_data:{annotation_id:c,ei:e,feature:"iv",itct:b.trackingParams,src_vid:d},start_ms:b.startTimeMs};if(b.subscribeButton&&
b.subscribeButton.subscribeButtonRenderer){d.channel_id=b.subscribeButton.subscribeButtonRenderer.channelId;b=b.subscribeButton.subscribeButtonRenderer;k=e=null;b.subscribed?(b.subscriberCountWithUnsubscribeText&&(e=g.S(b.subscriberCountWithUnsubscribeText)),b.subscriberCountText&&(k=g.S(b.subscriberCountText))):(b.subscriberCountText&&(e=g.S(b.subscriberCountText)),b.subscriberCountWithSubscribeText&&(k=g.S(b.subscriberCountWithSubscribeText)));var l="";b.signInEndpoint&&b.signInEndpoint.webNavigationEndpointData&&
b.signInEndpoint.webNavigationEndpointData.url&&(l=b.signInEndpoint.webNavigationEndpointData.url);b={subscribeText:g.S(b.unsubscribedButtonText),subscribeCount:e,unsubscribeText:g.S(b.subscribedButtonText),unsubscribeCount:k,enabled:b.enabled,classic:!1,subscribed:b.subscribed,feature:"iv",signInUrl:l};d.standalone_subscribe_button_data=b}f=new Y2(c,"branding","branding",f,d);d=gva();a.u.element.appendChild(d);f=new q3(d,v3(a),f);f.kn();g.A(f,f);a.G[c]=f}},mva=function(a,b){return(0,g.x)(function(){if(!this.ha()){var c=
Array.prototype.slice.call(arguments,0);
c.unshift(b);b=g.Ra.apply(window,c);this.R.push(g.wp(b))}},a)},C2={},D2=null;g.Ta(F2,g.Jn);g.h=F2.prototype;g.h.getDuration=function(){return this.duration};
g.h.play=function(a){if(a||0==this.o)this.progress=0,this.coords=this.A;else if(this.nb())return!1;E2(this);this.startTime=a=(0,g.C)();-1==this.o&&(this.startTime-=this.duration*this.progress);this.endTime=this.startTime+this.duration;this.C=this.startTime;this.progress||this.fq();this.Me("play");-1==this.o&&this.Me("resume");this.o=1;var b=g.Qa(this);b in C2||(C2[b]=this);hua();iua(this,a);return!0};
g.h.stop=function(a){E2(this);this.o=0;a&&(this.progress=1);jua(this,this.progress);this.Me("stop");this.Vm()};
g.h.pause=function(){this.nb()&&(E2(this),this.o=-1,this.Me("pause"))};
g.h.Y=function(){0==this.o||this.stop(!1);this.Me("destroy");F2.Tb.Y.call(this)};
g.h.destroy=function(){this.dispose()};
g.h.Ju=function(){this.Me("animate")};
g.h.Me=function(a){this.dispatchEvent(new kua(a,this))};
g.Ta(kua,g.Pe);g.Ta(G2,F2);G2.prototype.B=g.Ja;G2.prototype.Ju=function(){this.B();G2.Tb.Ju.call(this)};
G2.prototype.Vm=function(){this.B();G2.Tb.Vm.call(this)};
G2.prototype.fq=function(){this.B();G2.Tb.fq.call(this)};
g.Ta(H2,G2);H2.prototype.B=function(){this.element.style.left=Math.round(this.coords[0])+"px";this.element.style.top=Math.round(this.coords[1])+"px"};g.r(I2,g.z);I2.prototype.na=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.hp(a,b,c);this.o.push(a);return a};
I2.prototype.Rt=function(a,b,c,d){c=(0,g.x)(c,d||this.u);a=g.rp(a,b,c);this.o.push(a);return a};
I2.prototype.kb=function(a){g.ip(a);g.gb(this.o,a)};
I2.prototype.Y=function(){g.ip(this.o);this.o.length=0;g.z.prototype.Y.call(this)};g.r(M2,g.ZL);g.h=M2.prototype;g.h.load=function(){g.ZL.prototype.load.call(this);if(!N2(this)){var a=g.PB(this.player.getVideoData());if(a)a=L2(a,nua(this)),O2(this,a,!1);else{var b=this.player.getVideoData();a=b.videoId;this.B&&this.B.abort();a={method:"POST",Dd:(0,g.x)(this.qL,this,a),oe:{v:a},withCredentials:!0};this.L&&(a.oe.ptype="embedded");var c=this.player.getVideoData().so;c&&(a.yb={ad_tracking:c});if(b=g.OB(b))if(b=g.Dc(b),b=g.Ac(b))this.B=g.wq(b,a)}}};
g.h.unload=function(){O2(this,null);this.B&&(this.B.abort(),this.B=null);g.ZL.prototype.unload.call(this)};
g.h.fd=function(a,b){if(!N2(this))return null;if("loadCustomEndscreenRenderer"==a){var c=L2(b,"new");O2(this,c);return!0}return null};
g.h.getOptions=function(){return N2(this)?["loadCustomEndscreenRenderer"]:[]};
g.h.qL=function(a,b){var c=this.B=null;if(200==b.status){var d=b.responseText;")]}"==d.substring(0,3)&&(d=d.substring(3),c=JSON.parse(d),c=L2(c,nua(this)))}O2(this,c)};
g.h.Wz=function(){if(this.u&&this.u.elements){var a=this.player.getVideoContentRect();if(a&&0!=a.width&&0!=a.height){var b=this.player.getPlayerSize();if(b&&0!=b.width&&0!=b.height){var c=a.width/a.height;var d=0;for(var e=-1,f=0;f<uva.length;f++){var k=Math.abs(b.width-uva[f]);if(-1==e||d>=k)e=f,d=k}d=vva[e];this.A&&g.H(this.A.element,"outline-width",Math.max(b.width,b.height)+"px");for(b=0;b<this.u.elements.length;++b)if(f=this.u.elements[b].id,e=this.o[f],k=this.G[f],e&&k){var l=k.width*c/k.aspectRatio;
f=Math.round(l*a.height);var m=a.left+Math.round(k.left*a.width),n=a.top+Math.round(k.top*a.height);g.Qh(e.element,Math.round(k.width*a.width),f);g.Gh(e.element,m,n);g.In(e.element,wva);m=k.left+k.width/2;k=k.top+l/2;g.J(e.element,.5>=m&&.5>=k?"ytp-ce-top-left-quad":.5<m&&.5>=k?"ytp-ce-top-right-quad":.5>=m&&.5<k?"ytp-ce-bottom-left-quad":"ytp-ce-bottom-right-quad");g.In(e.element,vva);g.J(e.element,d);(e=g.he(document,"div","ytp-ce-expanding-overlay-body",e.element)[0])&&g.H(e,"height",f+"px")}}}}};
g.h.IH=function(a){if(this.u)if("ytp-ce-in-endscreen"==a.getId())S2(this,this.u.impressionUrls),(a=g.qs())&&this.u.visualElement&&g.Hs(a,this.u.visualElement);else{a=a.getId().substring(15);var b=this.o[a],c=this.G[a];g.J(b.element,"ytp-ce-element-show");b.element.removeAttribute("aria-hidden");b=this.player.getRootNode();g.J(b,"ytp-ce-shown");S2(this,c.impressionUrls);(b=g.qs())&&g.Hs(b,c.visualElement);this.player.O().A&&this.player.sa("endscreenelementshown",a)}};
g.h.JH=function(a){if("ytp-ce-in-endscreen"!=a.getId()){a=a.getId().substring(15);var b=this.o[a];g.Hn(b.element,"ytp-ce-element-show");b.element.setAttribute("aria-hidden",!0);b=this.player.getRootNode();g.Hn(b,"ytp-ce-shown");this.player.O().A&&this.player.sa("endscreenelementhidden",a)}};
g.h.RN=function(a){var b=this;a.target===window&&(new g.I(function(){for(var c in b.o)g.In(b.o[c].element,["ytp-ce-force-expand","ytp-ce-element-hover","ytp-ce-element-shadow-show"])},0)).start()};
g.h.rB=function(a,b){if(a.targetUrl&&(!b||"keypress"!=b.type||13==b.keyCode)){for(var c=b.target;c&&!g.Fn(c,"ytp-ce-element");){g.Fn(c,"subscribe-label")&&T2(this,a);if(g.Fn(c,"ytp-ce-channel-subscribe"))return;c=g.Ce(c)}if(!c||g.Fn(c,"ytp-ce-element-hover")){b.preventDefault();b.stopPropagation();if(c=this.o[a.id])this.Ou(c,a),c.element.blur();b.ctrlKey||b.metaKey||"new"==a.XO?(T2(this,a),this.UC(),this.player.pauseVideo(),c=g.Dc(Q2(this,a.targetUrl)),c=g.Ac(c),g.hO(c,void 0,a.Zb)):(c=this.player.getVideoData().Wb,
c=(0,g.x)(this.PO,this,c,Q2(this,a.targetUrl),a.Zb),c=(0,g.x)(this.UC,this,c),T2(this,a,c))}}};
g.h.PO=function(a,b,c){var d=g.eq(b);a&&d&&(d.v||d.list)?g.UT(this.player.app,d.v,c,d.list,!1,void 0):g.gO(b,c)};
g.h.cu=function(a,b){g.Fn(a.element,"ytp-ce-element-hover")||("VIDEO"==b.type||"PLAYLIST"==b.type?g.J(a.element,"ytp-ce-element-hover"):this.player.O().o?(new g.I(function(){g.J(a.element,"ytp-ce-element-hover")},200)).start():g.J(a.element,"ytp-ce-element-hover"),S2(this,b.KG),R2(this,b.id,!0))};
g.h.Ou=function(a,b){g.Hn(a.element,"ytp-ce-element-hover");g.Hn(a.element,"ytp-ce-force-expand");R2(this,b.id,!1)};
g.h.UC=function(a){this.player.sendVideoStatsEngageEvent(17,a)};
var uva=[346,426,470,506,570,640,853,1280,1920],vva="ytp-ce-size-346 ytp-ce-size-426 ytp-ce-size-470 ytp-ce-size-506 ytp-ce-size-570 ytp-ce-size-640 ytp-ce-size-853 ytp-ce-size-1280 ytp-ce-size-1920".split(" "),wva=["ytp-ce-top-left-quad","ytp-ce-top-right-quad","ytp-ce-bottom-left-quad","ytp-ce-bottom-right-quad"];var zua={OQ:"current",BS:"new"};var Bua={CLOSE:"close",ES:"openUrl",EE:"subscribe"},Cua={DQ:"click",CLOSE:"close",HR:"hidden",qT:"rollOut",rT:"rollOver",xT:"shown"};Y2.prototype.Ac=function(){var a=Dua(this,function(b){return"openUrl"==b.type&&null!=b.url});
return a?a.url:null};
var rva={gQ:"anchored",gE:"branding",CHANNEL:"channel",NQ:"cta",KR:"highlightText",cS:"label",PLAYLIST:"playlist",cT:"popup",DT:"speech",EE:"subscribe",QT:"title",VIDEO:"video",iU:"website"},qva={gE:"branding",uQ:"card",VQ:"drawer",JR:"highlight",nS:"marker",hT:"promotion",TEXT:"text",kU:"widget"};$2.prototype.u=function(a,b){var c=g.Je(b.target,"label");c&&g.K(c,"iv-card-poll-choice-focused",a)};
$2.prototype.B=function(a,b){var c=g.Je(b.target,null,"iv-card-poll",void 0);if(c)if(a.Kj)g.je("iv-card-sign-in-button",c).click();else{var d=parseInt(dua(b.target),10);if(null==a.Ue)a.choices[d].count++,a.Ue=d;else if(a.Ue!=d){var e=a.choices[a.Ue];e.count=Math.max(e.count-1,0);a.choices[d].count++;a.Ue=d}else e=a.choices[a.Ue],e.count=Math.max(e.count-1,0),a.Ue=null;Kua(a,c);g.Aq(this.o.videoData.re,{oe:{action_poll_vote:1},yb:{poll_id:a.id,index:d,session_token:a.xP}});Z2(this.o.logger,a.Uc.click,
void 0,5);(c=g.qs())&&a.te&&g.Ms(c,a.te)}};g.r(f3,g.z);g.h=f3.prototype;g.h.addCueRange=function(a,b,c,d,e){a=new g.nC(a,b,{id:c});a.namespace="annotations_module";d&&this.ra.set(a,d);e&&this.ma.set(a,e);g.JL(this.context.J,[a])};
g.h.kn=function(){this.context.u.subscribe("resize",this.Zn,this)};
g.h.xa=function(){return this.Ma};
g.h.ql=function(a,b,c,d,e,f){this.context.o.na(a,"click",g.Ra(this.kp,b,c,d,e||[],f||0),this);this.context.o.na(a,"touchstart",g.Ra(function(){this.gw=!1}),this);
this.context.o.na(a,"touchmove",g.Ra(function(){this.gw=!0}),this)};
g.h.kp=function(a,b,c,d,e,f){if(this.gw)return!1;f&&(f.stopPropagation(),f.preventDefault());Qua(this,a,c,d,e);return!1};
g.h.show=function(){};
g.h.hide=function(){};
g.h.destroy=function(){g.Ae(this.xa())};
g.h.Zn=function(){};
g.h.Y=function(){this.ra.clear();this.ma.clear();g.z.prototype.Y.call(this)};g.r(j3,f3);g.h=j3.prototype;g.h.isAvailable=function(){var a;if(a=!!this.A.length)(a=this.u.getRootNode())?(a=g.Rh(a),a=173<a.width&&173<a.height):a=!1;return a};
g.h.Zn=function(){var a=this.isAvailable();g.Sh(this.xa(),a);g.K(this.context.J.getRootNode(),g.VM.IV_DRAWER_ENABLED,a);z2(this.u)};
g.h.destroy=function(){var a=g.BL(g.oL(this.u));a&&a.Xt(!1,void 0);try{this.u.getRootNode().removeChild(this.F)}catch(b){}g.To(this.Z);g.ip(this.ea);this.fa&&this.fa.dispose();this.G&&this.G.dispose();f3.prototype.destroy.call(this)};
g.h.cM=function(a){this.aa.start();a.preventDefault();a=a||window.event;var b=0;"MozMousePixelScroll"==a.type?b=0==(a.axis==a.HORIZONTAL_AXIS)?a.detail:0:window.opera?b=a.detail:b=0==a.wheelDelta%120?"WebkitTransform"in document.documentElement.style?window.chrome&&0==navigator.platform.indexOf("Mac")?a.wheelDeltaY/-30:a.wheelDeltaY/-1.2:a.wheelDelta/-1.6:a.wheelDeltaY/-3;if(a=b)this.B.scrollTop+=a};
g.h.VC=function(a){if(!g.Fn(this.u.getRootNode(),"ytp-cards-teaser-shown")){if(this.o!=a){var b=g.qs(),c=this.o?this.o.card.Pd:this.M;b&&c&&B2(b,[c]);this.o=a;n3(this)}if(b="none"!=this.xa().style.display)2==this.context.J.getPresentingPlayerType()?b=1==this.context.J.getAdState():(b=this.context.J.getPlayerState(),c=0==b&&0===this.context.J.getCurrentTime(),b=1==b||3==b||c);b&&a.card.teaserDurationMs&&(b={teaserText:a.card.teaserText,durationMs:a.card.teaserDurationMs},(c=g.BL(g.oL(this.u)))&&c.Xt(!0,
b));this.za.isActive()||((!this.C||!this.aa.isActive()&&this.ga)&&$ua(this,a),this.za.start(910+a.card.teaserDurationMs))}};
g.h.HO=function(a){this.C||(this.o=a,n3(this),$ua(this,a),h3(this,"YOUTUBE_DRAWER_AUTO_OPEN",!1))};
g.h.eF=function(){if(this.C){Z2(this.context.logger,o3(this).Uc.close);var a=g.qs();a&&this.R&&g.Ms(a,this.R);i3(this)}};
g.h.rF=function(){g.K(this.F,"iv-drawer-scrolled",0<this.B.scrollTop)};
g.h.cH=function(){var a=g.qs(),b=o3(this);b=b?b.Pd:this.M;a&&b&&A2(a,[b])};
g.h.bH=function(){var a=g.qs(),b=o3(this);b=b?b.Pd:this.M;a&&b&&B2(a,[b])};
g.h.fH=function(){var a=o3(this);Z2(this.context.logger,a.Uc.jD);var b=g.qs();b&&a&&A2(b,[a.ne,a.Pd])};
g.h.eH=function(){var a=g.qs(),b=o3(this);a&&b&&B2(a,[b.ne])};
g.h.dH=function(a){var b=o3(this),c=g.qs();this.o?a?(a=this.context.logger,Z2(a,b.Uc.Sq),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.ne&&g.Ms(c,b.ne)):(a=this.context.logger,Z2(a,b.Uc.Sq),a.o.sendVideoStatsEngageEvent(4,void 0),c&&b.Pd&&g.Ms(c,b.Pd)):(a=this.context.logger,Z2(a,b.Uc.Sq),a.o.sendVideoStatsEngageEvent(4,void 0),c&&this.M&&g.Ms(c,this.M))};g.r(p3,f3);p3.prototype.kn=function(){f3.prototype.kn.call(this);ava(this)};
p3.prototype.show=function(){f3.prototype.show.call(this);var a=g.qs(),b=this.annotation.data;a&&b&&(b=b.session_data)&&A2(a,[g.js(b.itct)])};
p3.prototype.hide=function(){f3.prototype.hide.call(this);var a=g.qs(),b=this.annotation.data;a&&b&&(b=b.session_data)&&B2(a,[g.js(b.itct)])};g.r(q3,p3);g.h=q3.prototype;g.h.QO=function(a,b,c,d){this.A.stop();if(!this.B){var e=g.Rh(a);this.o||(g.Ph(a,e.width),g.Ph(b,e.width));g.H(c,"top",e.height-Math.max(Math.min(e.height,d)/2+10,20)+"px");g.H(c,"right","1px");this.B=!0;g.Sh(a,!0);this.C=new g.I(function(){g.J(this.xa(),"iv-branding-active")},0,this);
this.C.start()}};
g.h.JG=function(a,b){g.Hn(this.xa(),"iv-branding-active");this.F=new g.I((0,g.x)(function(){g.Sh(a,!1);this.o||g.Ph(b,0)},this),250);
this.F.start();this.B=!1};
g.h.show=function(){if(!this.isActive){p3.prototype.show.call(this);if(!this.G){g.J(this.xa(),"iv-branding");var a=this.annotation.data;this.u=g.ue("IMG",{"aria-label":"Marca-d'\u00e1gua do canal",src:a.image_url,"class":"branding-img iv-click-target",width:a.image_width,height:a.image_height});g.Sh(this.u,!1);var b=g.ue("DIV","branding-img-container",this.u);this.xa().appendChild(b);(b=this.annotation.Ac())&&this.ql(this.u,b,this.annotation.id,a.session_data);if(a.channel_name){var c=g.ue("DIV",
"iv-branding-context-name");g.Ee(c,a.channel_name);var d=g.ue("DIV","iv-branding-context-subscribe");if(b=a.standalone_subscribe_button_data)this.o=new g.vR(b.subscribeText,b.subscribeCount,b.unsubscribeText,b.unsubscribeCount,!!b.enabled,!!b.classic,a.channel_id,!!b.subscribed,b.feature,a.session_data.itct,b.signinUrl,this.context.J),this.o.ca(d);b=g.ue("DIV","iv-branding-context-subscribe-caret");c=g.ue("DIV","branding-context-container-inner",b,c,d);g.Sh(c,!1);d=g.ue("DIV","branding-context-container-outer",
c);g.H(d,"right",a.image_width+"px");this.xa().appendChild(d);this.A=new g.I(g.Ra(this.JG,c,d),500,this);g.A(this,this.A);this.context.o.na(this.xa(),"mouseover",(0,g.x)(this.QO,this,c,d,b,a.image_height));this.context.o.na(this.xa(),"mouseout",(0,g.x)(this.A.start,this.A,void 0))}this.G=!0}g.Sh(this.xa(),!0);this.isActive=!0;if(this.u){a=this.u;var e=void 0===e?0:e;b=g.Kh(a);c=g.Rh(a);b=(new g.wh(b.x,b.y,c.width,c.height)).width;g.Gh(a,b);e=new H2(a,[b,a.offsetTop],[b-b-e,a.offsetTop],200,eua);g.A(this,
e);this.context.A.na(e,"begin",g.Ra(g.Sh,a,!0));e.play()}}};
g.h.hide=function(){this.isActive&&(p3.prototype.hide.call(this),g.Sh(this.xa(),!1),this.isActive=!1)};
g.h.destroy=function(){this.o&&(this.o.dispose(),this.o=null);p3.prototype.destroy.call(this)};g.r(r3,p3);g.h=r3.prototype;g.h.show=function(){this.isActive||(p3.prototype.show.call(this),this.L||(bva(this),this.L=!0),g.Sh(this.xa(),!0),g.$f(function(){g.Hn(this.xa(),"iv-promo-inactive")},100,this),this.xa().removeAttribute("aria-hidden"),this.isActive=!0,s3(this),dva(this),eva(this,this.G))};
g.h.hide=function(){this.isActive&&(g.J(this.xa(),"iv-promo-inactive"),this.isActive=!1,this.xa().setAttribute("aria-hidden",!0))};
g.h.kp=function(a,b,c,d,e,f){return this.C?!1:p3.prototype.kp.call(this,a,b,c,d,e,f)};
g.h.nt=function(a,b){b.stopPropagation();dva(this);eva(this,a);this.o.focus()};
g.h.nG=function(a){this.M=!0;this.nt(500,a)};
g.h.mG=function(){this.M=!1;cva(this)};
g.h.eG=function(a){a.stopPropagation();this.hide()};
g.h.fG=function(a){a.stopPropagation();s3(this);this.C=!0;g.J(this.xa(),"iv-promo-collapsed-no-delay");this.F.start()};
g.h.destroy=function(){this.F.dispose();p3.prototype.destroy.call(this)};g.r(t3,g.ZL);g.h=t3.prototype;g.h.fd=function(a,b){if(!hva(this.player.O().playerStyle))return null;switch(a){case "loadCustomAnnotationsXml":var c=g.y1(b);c&&u3(this,c);return!0;case "removeCustomAnnotationById":return b&&this.o&&(Vua(this.o,b),z2(this.player)),!0}return null};
g.h.getOptions=function(){return hva(this.player.O().playerStyle)?["loadCustomAnnotationsXml","removeCustomAnnotationById"]:[]};
g.h.iq=function(){if(this.B){var a=g.uL(this.player).getVideoContentRect(!0);g.Qh(this.B.element,a.width,a.height);g.Gh(this.B.element,a.left,a.top)}if(this.o){var b=g.EL(this.player);a=this.o;b=b.width;g.K(a.F,"iv-drawer-small",426>=b);g.K(a.F,"iv-drawer-big",1280<=b)}};
g.h.xM=function(a){iva(this,a.state);g.U(a.state,2)&&(this.Fm()&&this.Nz()&&2!=this.player.getPresentingPlayerType()&&this.setCardsVisible(!1),this.Xt(!1))};
g.h.load=function(){g.ZL.prototype.load.call(this);iva(this,g.tL(this.player));this.M++;var a=this.player.getVideoData(),b=a.videoId,c=(0,g.x)(this.sL,this,b,this.M),d=(0,g.x)(function(){this.F=null},this);
g.yp()&&(c=mva(this,c));c={format:"XML",Dd:c,onError:d,oe:{}};a.isPharma&&(c.oe.pharma="1");c.method="POST";c.withCredentials=!0;(b=this.player.O().M.get(b))&&nva(c,b);b=b&&(b.fo||b.eo);if(!a.Sn||b)a.re?jva(this,a.re,c):(this.A=(0,g.x)(this.HH,this,c),this.player.addEventListener("videodatachange",this.A));g.NL(this.player,this.B.element,4);this.iq();(b=g.QB(a))&&sva(this,b);(b=g.RB(a))&&b.featuredChannel&&tva(this,b.featuredChannel,b.annotationId||"branding",a.videoId||null,a.eventId||null)};
g.h.HH=function(a){var b=this.player.getVideoData();b.re&&(this.A&&(this.player.removeEventListener("videodatachange",this.A),this.A=null),jva(this,b.re,a))};
g.h.unload=function(){g.RR(this.player.app,"annotations_module",void 0);g.Cb(this.G,function(a){a.destroy()});
this.H=null;this.o&&(this.o.destroy(),this.o=null,z2(this.player));this.L=!1;this.F&&(this.F.abort(),this.F=null);this.G={};this.u.hide();g.ZL.prototype.unload.call(this);this.B.detach();this.A&&(this.player.removeEventListener("videodatachange",this.A),this.A=null)};
g.h.sL=function(a,b,c){this.F=null;!lva(this,b,a)&&(a=g.qq(c)&&c.responseXML?c.responseXML:null)&&(u3(this,a),g.J(this.player.getRootNode(),"iv-module-loaded"))};
g.h.bC=function(a){a==this.player.getVideoData().videoId&&(this.loaded?ova(this):this.load())};
g.h.Fm=function(){return!!this.o&&this.o.isAvailable()};
g.h.Nz=function(){this.Fm();return!!this.o&&this.o.C};
g.h.setCardsVisible=function(a,b,c){b=void 0===b?!1:b;this.Fm();this.o&&(a?c?h3(this.o,c,b):h3(this.o,"YOUTUBE_DRAWER_AUTO_OPEN",b):i3(this.o))};
g.h.Xt=function(a,b){this.player.S(a?"cardsteasershow":"cardsteaserhide",b)};
g.h.Y=function(){this.player.O().M.unsubscribe("vast_info_card_add",this.bC,this);g.Hn(this.player.getRootNode(),g.VM.IV_DRAWER_OPEN);for(var a=this.R,b=0,c=a.length;b<c;b++)g.zp(a[b]);this.R.length=0;g.ZL.prototype.Y.call(this)};g.nM.annotations_module=t3;g.nM.creatorendscreen=M2;})(_yt_player);
