(function(g){var window=this;var z3=function(a){var b={languageCode:a.languageCode,languageName:a.languageName,displayName:g.at(a),kind:a.kind,name:a.name,id:a.id,is_servable:a.o,is_default:a.isDefault,is_translateable:a.isTranslateable,vss_id:a.vssId};a.translationLanguage&&(b.translationLanguage=a.translationLanguage);return b},A3=function(a){return a.translationLanguage?a.translationLanguage.languageCode:a.languageCode},xva=function(a,b){var c=new g.$s;
c.languageCode=a.languageCode;c.languageName=a.languageName;c.name=a.name;c.kind=a.kind;c.isDefault=!1;c.o=a.o;c.isTranslateable=a.isTranslateable;c.vssId=a.vssId;c.url=a.url;c.translationLanguage=b;return c},yva=function(){this.u=[];
this.o=[]},B3=function(a,b){switch(b.kind){case "asr":zva(b,a.u);
break;default:zva(b,a.o)}},zva=function(a,b){g.$a(b,function(c){return c?a.toString()===c.toString():!1})||b.push(a)},C3=function(){g.z.call(this);
this.u=new yva;this.B=[]},D3=function(a,b,c){C3.call(this,a);
this.audioTrack=c;this.o=null;this.B=b.qx},E3=function(){this.segments=[]},Ava=function(a,b){var c=g.sb(a.segments,b);
0<=c||0>c&&1===(-c-1)%2||(c=-c-1,0<c&&1===b-a.segments[c-1]&&c<a.segments.length&&1===a.segments[c]-b?(g.fb(a.segments,c),g.fb(a.segments,c-1)):0<c&&1===b-a.segments[c-1]?a.segments[c-1]=b:c<a.segments.length&&1===a.segments[c]-b?a.segments[c]=b:(g.pb(a.segments,c,0,b),g.pb(a.segments,c+1,0,b)))},F3=function(a,b,c,d,e,f){g.z.call(this);
this.policy=a;this.player=b;this.L=c;this.F=d;this.C=e;this.H=f;this.M=this.player.O();this.B=new E3;this.u=this.A=this.o=null;this.G=new g.I(this.Bz,1E3,this);this.events=new g.Ur(this);g.A(this,this.G);g.A(this,this.events);this.events.N(b,"SEEK_COMPLETE",this.UB);this.UB();this.Bz()},Bva=function(a,b){var c=g.rx(b,a.policy,{}).Ac(),d={format:"RAW",
withCredentials:!0};a.C&&(d.responseType="arraybuffer");a.u=g.wr(c,d,3,100).then(function(e){a.ha();var f=!(a.C?e.response:e.responseText)||400<=e.status,k=g.Ox(e);k?(e=g.rx(a.A,a.policy,{}),f=a.A,g.nx(f.u,e,k),f.requestId=e.get("req_id"),Bva(a,a.A)):(f||null==a.F||(k=a.A.o[0],a.C?a.F(e.response,1E3*(k.startTime+a.player.Gb())):a.F(e.responseText,1E3*(k.startTime+a.player.Gb()))),a.A=null,a.u=null)});
a.A=b;Ava(a.B,a.A.o[0].u)},G3=function(a,b){C3.call(this,b.O());
this.ka=a;this.J=b;this.o=null;this.A=!1;this.C=g.pz(this.J.O())&&!this.ka.u},Cva=function(a,b){var c=[],d;
for(d in a.ka.o)if(a.ka.o.hasOwnProperty(d)){var e=a.ka.o[d];if(g.$L(e,b||null)){var f="en",k="English",l=".en",m="";if(e=e.info.captionTrack)f=e.languageCode,k=e.displayName,l=e.vssId,m=e.kind;c.push(new g.$s({id:d,languageCode:f,languageName:k,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:l,kind:m}))}}return c},Dva=function(a,b){return null!=b&&b in a.ka.o?a.ka.o[b]:null},Eva=function(a,b,c){var d=[],e;
for(e in a.ka.o)if(a.ka.o.hasOwnProperty(e)){var f=a.ka.o[e];if(g.$L(f,c||null)){var k=f.info.captionTrack;k&&k.languageCode===b&&d.push(f)}}return d.length?d[0]:null},H3=function(a,b,c,d,e){C3.call(this,e||null);
this.videoId=b;this.cz=d;this.C={};this.o=null;b=c||g.eq(a).hl||"";b=b.split("_").join("-");this.A=g.gq(a,{hl:b})},I3=function(a,b,c,d,e,f,k){var l={};
g.Sa(l,b);g.Sa(l,a.params);g.Sa(l,c);var m={};g.Sa(m,b.Hb);a.params.Hb&&g.Sa(m,a.params.Hb);g.Sa(m,c.Hb);l.Hb=m;g.W.call(this,{D:"div",I:"caption-window",P:{id:"caption-window-"+a.id,dir:1===l.o?"rtl":"ltr",tabindex:"0","aria-live":"assertive",lang:l.lang},K:[{D:"span",I:"captions-text",P:{style:"word-wrap: normal; display: block;"}}]});this.C=[];this.T=!1;this.u=a;this.Z=this.U=null;this.playerWidth=e;this.playerHeight=f;this.experiments=k;this.F=null;this.maxWidth=.96*e;this.wa=.96*f;this.o=l;this.Ea=
c;this.B=this.da("captions-text");this.Aa=""!==this.B.style.getPropertyValue("box-decoration-break")||""!==this.B.style.getPropertyValue("-webkit-box-decoration-break");this.aa=d/360*16;this.type=0;this.fa=this.aa*Fva(m);a=new g.$r(this.element,!0);g.A(this,a);a.subscribe("dragstart",this.mL,this);a.subscribe("dragmove",this.lL,this);a.subscribe("dragend",this.jL,this);this.ua=this.ma=0;b="";this.o.windowOpacity&&(a=g.x1(this.o.windowColor),b="rgba("+a[0]+","+a[1]+","+a[2]+","+this.o.windowOpacity+
")");a={"background-color":b,display:!1===this.o.isVisible?"none":"","text-align":Gva[this.o.textAlign]};this.Aa&&(a["border-radius"]=b?this.fa/8+"px":"");if(this.A=2===this.u.params.o||3===this.u.params.o)b=this.element,c="vertical-rl",1===this.o.A&&(c="vertical-lr"),g.oe&&(c="vertical-lr"===c?"tb-lr":"tb-rl"),g.H(b,"-o-writing-mode",c),g.H(b,"-webkit-writing-mode",c),g.H(b,"writing-mode",c),g.H(b,"text-orientation","upright"),g.J(b,"ytp-vertical-caption"),3===this.u.params.o&&(g.H(b,"text-orientation",
""),g.H(b,"transform","rotate(180deg)"));g.H(this.element,a);switch(this.o.cf){case 0:case 1:case 2:g.J(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.J(this.element,"ytp-caption-window-bottom")}},Fva=function(a){var b=1+.25*(a.fontSizeIncrement||0);
if(0===a.offset||2===a.offset)b*=.8;return b},Hva=function(a,b){var c={},d=b.background?b.background:a.o.Hb.background;
if(null!=b.backgroundOpacity||b.background){var e=null!=b.backgroundOpacity?b.backgroundOpacity:a.o.Hb.backgroundOpacity;d=g.x1(d);c.background="rgba("+d[0]+","+d[1]+","+d[2]+","+e+")";a.Aa&&(c["box-decoration-break"]="clone",c["border-radius"]=a.fa/8+"px")}if(null!=b.fontSizeIncrement||null!=b.offset)c["font-size"]=a.aa*Fva(b)+"px";d=1;e=b.color||a.o.Hb.color;if(b.color||null!=b.textOpacity)e=g.x1(e),d=null==b.textOpacity?a.o.Hb.textOpacity:b.textOpacity,e="rgba("+e[0]+","+e[1]+","+e[2]+","+d+")",
c.color=e,c.fill=e;var f=b.charEdgeStyle;0===f&&(f=void 0);if(f){e="rgba(34, 34, 34, "+d+")";var k="rgba(204, 204, 204, "+d+")";b.Zr&&(k=e=b.Zr);var l=a.aa/16/2,m=Math.max(l,1),n=Math.max(2*l,1),q=Math.max(3*l,1),t=Math.max(5*l,1);d=[];switch(f){case 4:for(;q<=t;q+=l)d.push(n+"px "+n+"px "+q+"px "+e);break;case 1:n=2<=window.devicePixelRatio?.5:1;for(f=m;f<=q;f+=n)d.push(f+"px "+f+"px "+e);break;case 2:d.push(m+"px "+m+"px "+k);d.push("-"+m+"px -"+m+"px "+e);break;case 3:for(q=0;5>q;q++)d.push("0 0 "+
n+"px "+e)}c["text-shadow"]=d.join(", ")}e="";switch(b.fontFamily){case 1:e='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:e='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:e='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:e='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:e='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:e=g.kl()?
'"Carrois Gothic SC", sans-serif-smallcaps':'"Arial Unicode Ms", Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:e='"YouTube Noto", Roboto, "Arial Unicode Ms", Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}e&&(c["font-family"]=e);e=b.offset;null==e&&(e=a.o.Hb.offset);switch(e){case 0:c["vertical-align"]="sub";break;case 2:c["vertical-align"]="super"}7===b.fontFamily&&(c["font-variant"]="small-caps");b.bold&&(c["font-weight"]="bold");b.wf&&(c["font-style"]="italic");
b.underline&&(c["text-decoration"]="underline");b.IG&&(c.visibility="hidden");1===b.Zy&&a.A&&(c["text-combine-upright"]="all",c["text-orientation"]="mixed",e=g.sz||g.tz,3===a.u.params.o?c.transform=e?"rotate(90deg)":"rotate(180deg)":e&&(c.transform="rotate(-90deg)"));if(1===b.Nf||2===b.Nf||3===b.Nf||4===b.Nf||5===b.Nf)if(g.sz)c["font-weight"]="bold";else switch(c["text-emphasis-style"]="filled circle",c["text-emphasis-color"]="currentcolor",c["webkit-text-emphasis"]="filled circle",b.Nf){case 4:case 3:c["text-emphasis-position"]=
"under left";c["webkit-text-emphasis-position"]="under left";break;case 5:case 2:c["text-emphasis-position"]="over right",c["webkit-text-emphasis-position"]="over right"}return c},Iva=function(a){a.F=g.ve("SPAN");
g.H(a.F,{display:"block"});g.J(a.F,"caption-visual-line");a.B.appendChild(a.F)},Jva=function(a,b){var c=g.ve("SPAN");
g.H(c,{display:"inline-block","white-space":"pre-wrap"});g.H(c,Hva(a,b));c.classList.add("ytp-caption-segment");a.F.appendChild(c);c.previousElementSibling&&(g.H(c.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.H(c,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return c},Kva=function(a,b,c){a.T=a.T||!!c;
var d={};g.Sa(d,a.o.Hb);g.Sa(d,c||b.o);g.Sa(d,a.Ea.Hb);(c=!a.F)&&Iva(a);for(var e=a.U&&a.Z&&g.Rb(d,a.Z)?a.U:Jva(a,d),f="string"===typeof b.text,k=f?b.text.split("\n"):[b.text],l=0;l<k.length;l++){var m=0<l||!b.append,n=k[l];m&&!c?(Iva(a),e=Jva(a,d)):m&&c&&(c=!1);n&&(e.appendChild(f?g.we(n):n),f||"RUBY"!==n.tagName||4!==n.childElementCount||g.sz||!g.Ch(n.children[2],"text-emphasis")||(m=a.A?"padding-right":"padding-top",g.Ch(n.children[2],"text-emphasis-position")&&(m=a.A?"padding-left":"padding-bottom"),
g.qe?g.H(e,m,"1em"):g.H(e,m,"0.5em")))}a.Z=d;a.U=e;a.C.push(b)},J3=function(a,b,c,d,e,f,k){I3.call(this,a,b,c,d,e,f,k);
this.type=1},K3=function(a,b,c,d,e,f,k){I3.call(this,a,b,c,d,e,f,k);
this.type=2;this.G=[];this.L=this.H=this.ba=0;this.R=NaN;this.za=0;this.Ca=null;this.ea=new g.I(this.YM,433,this);g.J(this.element,"ytp-caption-window-rollup");g.A(this,this.ea);g.H(this.element,"overflow","hidden")},Lva=function(a,b){return(a.A?b.offsetHeight:b.offsetWidth)+1},Mva=function(a){if(isNaN(a.R)){var b=a.o.Ah;
if(b){var c=g.ve("SPAN");g.Ee(c,"\u2013".repeat(b));g.H(c,Hva(a,a.o.Hb));a.B.appendChild(c);a.R=c.offsetWidth;a.B.removeChild(c)}else a.R=0}return a.R},Nva=function(a,b){if(!b)return"";
a.A&&1!==a.u.params.A&&(b*=-1);return"translate"+(a.A?"X":"Y")+"("+b+"px)"},Ova=function(a){a.G=Array.from(document.getElementsByClassName("caption-visual-line"));
for(var b=a.u.params.u,c=0,d=0,e=a.G.length-1;c<b&&-1<e;){var f=a.G[e];d+=a.A?f.offsetWidth:f.offsetHeight;c++;e--}a.G.length<b&&(d*=b/a.G.length);a.H=d;a.L=Math.max(Mva(a),a.za,Lva(a,a.B))},Pva=function(a,b){Ova(a);
var c=a.G.reduce(function(e,f){return(a.A?f.offsetWidth:f.offsetHeight)+e},0);
c=a.H-c;if(c!==a.ba){var d=0<c&&0===a.ba;b||isNaN(c)||d||(g.J(a.element,"ytp-rollup-mode"),a.ea.Za());g.H(a.B,"transform",Nva(a,c));a.ba=c}Ova(a)},L3=function(a,b,c,d,e,f,k){f=void 0===f?!1:f;
k=void 0===k?null:k;g.nC.call(this,a,a+b,{priority:c,namespace:"captions"});this.windowId=d;this.text=e;this.append=f;this.o=k},M3=function(a,b,c,d,e){g.nC.call(this,a,a+b,{priority:c,
namespace:"captions"});this.id=d;this.params=e;this.o=[]},Qva=function(a){var b="_"+N3++;
return new M3(0,0x8000000000000,0,b,a)},Sva=function(a,b,c,d,e,f,k){var l=f[0],m=k[l.getAttribute("p")];
if(1===m.lc){var n=f[1],q=f[2];f=f[3];l.getAttribute("t");n.getAttribute("t");q.getAttribute("t");f.getAttribute("t");l.getAttribute("p");n.getAttribute("p");f.getAttribute("p");k=k[q.getAttribute("p")];l=Rva(l.textContent,n.textContent,q.textContent,f.textContent,k);return new L3(a,b,e,c,l,d,m)}switch(m.lc){case 9:case 10:m.Nf=1;break;case 11:m.Nf=2;break;case 12:m.Nf=3;break;case 13:m.Nf=4;break;case 14:m.Nf=5}return new L3(a,b,e,c,l.textContent||"",d,m)},Rva=function(a,b,c,d,e){var f=g.kl(),k=
f?g.ve("DIV"):g.ve("RUBY"),l=g.ve("SPAN");
l.textContent=a;k.appendChild(l);a=f?g.ve("DIV"):g.ve("RP");a.textContent=b;k.appendChild(a);b=f?g.ve("DIV"):g.ve("RT");b.textContent=c;k.appendChild(b);c=e.lc;if(10===c||11===c||12===c||13===c||14===c)if(g.H(b,"text-emphasis-style","filled circle"),g.H(b,"text-emphasis-color","currentcolor"),g.H(b,"webkit-text-emphasis","filled circle"),11===e.lc||13===e.lc)g.H(b,"webkit-text-emphasis-position","under left"),g.H(b,"text-emphasis-position","under left");c=!0;if(4===e.lc||7===e.lc||12===e.lc||14===
e.lc)g.H(k,"ruby-position","over"),g.H(k,"-webkit-ruby-position","before");else if(5===e.lc||6===e.lc||11===e.lc||13===e.lc)g.H(k,"ruby-position","under"),g.H(k,"-webkit-ruby-position","after"),c=!1;e=f?g.ve("DIV"):g.ve("RP");e.textContent=d;k.appendChild(e);f&&(d=c,g.H(k,{display:"inline-block",position:"relative"}),f=k.firstElementChild.nextElementSibling,g.H(f,"display","none"),f=f.nextElementSibling,g.H(f,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",left:"50%",
transform:"translateX(-50%)",width:"400%"}),g.H(k.lastElementChild,"display","none"),d?(g.H(k,"padding-top","0.6em"),g.H(f,"top","0")):(g.H(k,"padding-bottom","0.6em"),g.H(f,"bottom","0")));return k},O3=function(){g.z.apply(this,arguments)},P3=function(a){O3.call(this);
this.F=a;this.B={};this.M={};this.L={};this.C="_"+N3++;this.H={};this.u=this.o=null;this.G=!0},Q3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return Number(c)},R3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return"1"===c},S3=function(a,b){var c=Q3(a,b);
return void 0!==c?c:null},U3=function(a,b){var c=a.getAttribute(b);
if(null!=c)return T3.test(c),c},Tva=function(a,b){var c={},d=b.getAttribute("ws");
g.Sa(c,d?a.L[d]:a.F);d=S3(b,"mh");null!=d&&(c.Ik=d);d=S3(b,"ju");null!=d&&(c.textAlign=d);d=S3(b,"pd");null!=d&&(c.o=d);d=S3(b,"sd");null!=d&&(c.A=d);d=U3(b,"wfc");null!=d&&(c.windowColor=d);d=Q3(b,"wfo");void 0!==d&&(c.windowOpacity=d/255);return c},Uva=function(a,b){var c={},d=b.getAttribute("wp");
d&&g.Sa(c,a.M[d]);d=S3(b,"ap");null!=d&&(c.cf=d);d=Q3(b,"cc");null!=d&&(c.Ah=d);d=Q3(b,"ah");null!=d&&(c.Ae=d);d=Q3(b,"rc");null!=d&&(c.u=d);d=Q3(b,"av");null!=d&&(c.Pf=d);return c},Vva=function(a,b,c,d){var e={};
g.Sa(e,Uva(a,b));g.Sa(e,Tva(a,b));d?g.Rb(e,a.F)?(d=a.C,e=a.F):d="_"+N3++:d=b.getAttribute("id")||"_"+N3++;a=Q3(b,"t")+c;b=Q3(b,"d")||0x8000000000000;if(2===e.o||3===e.o)c=e.u,e.u=e.Ah,e.Ah=c;return new M3(a,b,0,d,e)},V3=function(a){O3.call(this);
this.F=a;this.o=new Map;this.B=new Map;this.C=new Map;this.u=new Map},W3=function(a){a=g.Ud(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substr(0,7-a.length)+a},Wva=function(a,b,c,d,e){0===d&&(d=0x8000000000000);
var f={};b.wpWinPosId&&Object.assign(f,a.B.get(b.wpWinPosId));b.wsWinStyleId&&Object.assign(f,a.C.get(b.wsWinStyleId));a=b.rcRowCount;void 0!==a&&(f.u=a);b=b.ccColCount;void 0!==b&&(f.Ah=b);if(2===f.o||3===f.o)b=f.u,f.u=f.Ah,f.Ah=b;return new M3(c,d,0,e,f)},Y3=function(){this.A=this.time=this.mode=this.u=0;
this.B=new X3(this);this.C=new X3(this);this.o=[];this.clear()},Yva=function(a,b,c){if(255===a&&255===b||!a&&!b)return{Mi:a,
xh:b,result:0};a=Xva[a];b=Xva[b];if(a&128){var d;if(d=!(b&128))d=b,d=c.isValid()&&c.xh===d;if(d)return{Mi:a,xh:b,result:1}}else if(b&128&&1<=a&&31>=a)return{Mi:a,xh:b,result:2};return{Mi:a,xh:b,result:3}},$va=function(a,b,c,d){255===b&&255===c||!b&&!c?(45===++a.A&&a.reset(),a.B.o.clear(),a.C.o.clear()):(a.A=0,Zva(a.B,b,c,d))},awa=function(a,b){a.o.sort(function(e,f){var k=e.time-f.time;
return 0===k?e.order-f.order:k});
for(var c=g.p(a.o),d=c.next();!d.done;d=c.next())d=d.value,a.time=d.time,0===d.type?$va(a,d.sx,d.tx,b):1===d.type&&a.u&496&&Zva(a.C,d.sx,d.tx,b);a.o.length=0},Z3=function(){this.type=0},$3=function(){this.state=this.xh=this.Mi=0},bwa=function(){this.timestamp=this.o=0},a4=function(a){this.C=a;
this.A=[];this.o=this.u=this.row=0;this.style=new Z3;for(a=this.B=0;15>=a;a++){this.A[a]=[];for(var b=0;32>=b;b++)this.A[a][b]=new bwa}},b4=function(a,b){if(3===a.style.type){for(var c=0,d=0,e=a.C.time+0,f="",k="",l=e,m=1;15>=m;++m){for(var n=!1,q=d?d:1;32>=q;++q){var t=a.A[m][q];
if(0!==t.o){0===c&&(c=m,d=q);n=String.fromCharCode(t.o);var u=t.timestamp;u<e&&(e=u);t.timestamp=l;k&&(f+=k,k="");f+=n;n=!0}if((0===t.o||32===q)&&n){k="\n";break}else if(d&&!n)break}if(c&&!n)break}f&&b.C(c,d,e,l,f)}else for(d=c=0,f=e=a.C.time+0,k=1;15>=k;++k)for(l="",m=1;32>=m;++m)if(q=a.A[k][m],t=q.o,0!==t&&(0===c&&(c=k,d=m),n=String.fromCharCode(t),u=q.timestamp,u<=e&&(e=u),l+=n,q.reset()),32===m||0===t)l&&b.C(c,d,e,f,l),e=f,l="",d=c=0},gwa=function(a,b){switch(a){case 0:return cwa[(b&127)-32];
case 1:return dwa[b&15];case 2:return ewa[b&31];case 3:return fwa[b&31]}return 0},c4=function(a){return a.A[a.row][a.u]},d4=function(a,b,c){2<=b&&1<a.u&&(--a.u,c4(a).o=0);
var d=c4(a);d.timestamp=a.C.time+0;d.o=gwa(b,c);32>a.u&&a.u++},hwa=function(a,b,c,d){for(var e=0;e<d;e++)for(var f=0;32>=f;f++){var k=a.A[b+e][f],l=a.A[c+e][f];
k.o=l.o;k.timestamp=l.timestamp}},e4=function(a,b,c){for(var d=0;d<c;d++)for(var e=0;32>=e;e++)a.A[b+d][e].reset()},f4=function(a){a.row=0<a.o?a.o:1;
a.u=1;e4(a,0,15)},g4=function(a){this.A=a;
this.C=0;this.style=new Z3;this.F=new a4(this.A);this.G=new a4(this.A);this.text=new a4(this.A);this.u=this.F;this.B=this.G;this.o=this.u},h4=function(a,b,c){var d=a.u,e=!1;
switch(a.style.get()){case 4:case 1:case 2:4===a.style.get()&&0<d.o||(b4(d,c),f4(a.u),f4(a.B),d.row=15,d.o=b,e=!0)}a.style.set(3);a.o=d;a.o.style=a.style;a.A.mode=1<<d.B;e?d.u=1:d.o!==b&&(d.o>b?(b4(d,c),e4(d,d.row-d.o,b)):d.row<b&&(b=d.o),d.o=b)},iwa=function(a){a.style.set(1);
a.o=a.B;a.o.o=0;a.o.style=a.style;a.A.mode=1<<a.o.B},jwa=function(a){a.style.set(4);
a.o=a.text;a.o.style=a.style;a.A.mode=1<<a.o.B},X3=function(a){this.u=a;
this.C=0;this.A=new g4(this.u);this.F=new g4(this.u);this.o=new $3;this.B=this.A},Zva=function(a,b,c,d){a.o.update();
b=Yva(b,c,a.o);switch(b.result){case 0:return;case 1:case 2:return}var e=b.Mi;c=b.xh;if(32<=e||!e)a.u.mode&a.u.u&&(b=e,b&128&&(b=127),c&128&&(c=127),a=a.B.o,b&96&&d4(a,0,b),c&96&&d4(a,0,c),0!==b&&0!==c&&3===a.style.type&&b4(a,d));else if(e&16)a:if(!a.o.matches(e,c)&&(b=a.o,b.Mi=e,b.xh=c,b.state=2,b=e&8?a.F:a.A,a.B=b,a.u.mode=1<<(a.C<<2)+(b.C<<1)+(4===b.style.type?1:0),(a.u.mode|1<<(a.C<<2)+(b.C<<1)+(4!==b.style.type?1:0))&a.u.u))if(c&64){d=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(e&7)<<1|c>>5&1];
a=c&16?4*((c&14)>>1):0;c=b.o;switch(b.style.get()){case 4:d=c.row;break;case 3:if(d!==c.row){if(d<c.o&&(d=c.o,d===c.row))break;var f=1+c.row-c.o,k=1+d-c.o;hwa(c,k,f,c.o);b=f;e=c.o;k<f?(f=k+e-f,0<f&&(b+=f,e-=f)):(f=f+e-k,0<f&&(e-=f));e4(c,b,e)}}c.row=d;c.u=a+1}else switch(e&7){case 1:switch(c&112){case 32:d4(b.o,0,32);break a;case 48:57===c?(d=b.o,c4(d).o=0,32>d.u&&d.u++):d4(b.o,1,c&15)}break;case 2:c&32&&d4(b.o,2,c&31);break;case 3:c&32&&d4(b.o,3,c&31);break;case 4:case 5:if(32<=c&&47>=c)switch(c){case 32:iwa(b);
break;case 33:d=b.o;1<d.u&&(--d.u,c4(d).o=0);break;case 36:d=b.o;b=c4(d);for(a=0;15>=a;a++)for(c=0;32>=c;c++)if(d.A[a][c]===b){for(;32>=c;c++)d.A[a][c].reset();break}break;case 37:h4(b,2,d);break;case 38:h4(b,3,d);break;case 39:h4(b,4,d);break;case 40:d4(b.o,0,32);break;case 41:b.style.set(2);b.o=b.u;b.o.o=0;b.o.style=b.style;b.A.mode=1<<b.o.B;break;case 42:d=b.text;d.o=15;d.style.set(4);f4(d);jwa(b);break;case 43:jwa(b);break;case 44:a=b.u;switch(b.style.get()){case 1:case 2:case 3:b4(a,d)}e4(a,
0,15);break;case 45:b:{a=b.o;switch(b.style.get()){default:case 2:case 1:break b;case 4:if(15>a.row){++a.row;a.u=1;break b}case 3:}2>a.o&&(a.o=2,a.row<a.o&&(a.row=a.o));b=a.row-a.o+1;b4(a,d);hwa(a,b,b+1,a.o-1);e4(a,a.row,1)}break;case 46:e4(b.B,0,15);break;case 47:b4(b.u,d),b.B.updateTime(b.A.time+0),d=b.B,b.B=b.u,b.u=d,iwa(b)}break;case 7:switch(c){case 33:case 34:case 35:d=b.o,32<(d.u+=c&3)&&(d.u=32)}}},kwa=function(){},i4=function(a,b,c){this.H=a;
this.G=c;this.version=this.F=this.B=this.o=0;this.u=new DataView(this.H);this.A=[]},j4=function(a){var b=a.o;
a.o+=1;return a.u.getUint8(b)},k4=function(a){var b=a.o;
a.o+=4;return a.u.getUint32(b)},l4=function(a,b){O3.call(this);
this.u=a;this.B=b;this.track="CC3"===this.B.languageName?4:0;this.o=new Y3;this.o.u=1<<this.track},m4=function(a){if("string"===typeof a)return!1;
a=new i4(a,8,0);return lwa(a)},lwa=function(a){if(!(a.o<a.u.byteLength)||1380139777!==k4(a))return!1;
a.version=j4(a);if(1<a.version)return!1;j4(a);j4(a);j4(a);return!0},n4=function(){O3.call(this)},mwa=function(a,b,c,d,e,f,k,l,m){switch(k.tagName){case "b":l.bold=!0;
break;case "i":l.wf=!0;break;case "u":l.underline=!0}for(var n=0;n<k.childNodes.length;n++){var q=k.childNodes[n];if(3===q.nodeType)q=new L3(b,c,d,e.id,q.nodeValue,f||0<n,g.Pb(l)?void 0:l),m.push(q),e.o.push(q);else{var t={};g.Sa(t,l);mwa(a,b,c,d,e,!0,q,t,m)}}},o4=function(a){var b=a.split(":");
a=0;b=g.p(b);for(var c=b.next();!c.done;c=b.next())a=60*a+Number(c.value);return 1E3*a},nwa=function(a,b,c,d){d=Object.assign({Ik:0},d);
return new M3(a,b,c,"_"+N3++,d)},p4=function(a){g.z.call(this);
this.u=a;this.o=null},pwa=function(a){var b={};
if(a=A3(a))b.lang=a,owa.test(a)&&(b.o=1);return b},s4=function(a){g.ZL.call(this,a);
this.J=a;this.A=this.J.O();this.videoData=this.J.getVideoData();this.za=g.uL(this.J);this.B={Hb:{}};this.F={Hb:{}};this.R=[];this.M={};this.ga={};this.U=!1;this.ua=g.aM(this.videoData,this.J);this.Aa=!!this.videoData.captionTracks.length;this.Ca=!!this.videoData.Sl;this.ra="3"===this.A.controlsType;this.u=this.G=this.H=this.ba=this.ma=null;this.fa=new p4(this.A);this.o=null;this.Z=new g.Ur(this);var b=null,c=g.oo("yt-html5-player-modules::subtitlesModuleData");c&&(b=new g.Yn(c));this.ea=b;b=a.app.C;
c=!(!b||!b.sn());this.wa=!(!b||!b.Lj());this.C=this.ra&&c&&!this.ua;this.L=!this.C&&this.ra&&this.wa&&this.ua;g.A(this,this.fa);this.C?this.aa=this.T=null:(this.T=new g.vn(this.BD,void 0,this),g.A(this,this.T),this.aa=new g.I(this.sO,2E3,this),g.A(this,this.aa));g.A(this,this.Z);this.C||this.Z.N(a,"resize",this.Xv);this.Z.N(a,"onPlaybackAudioChange",this.FK);this.Z.N(a,g.qC("captions"),this.ld,this);this.Z.N(a,"crx_captions",this.Ve,this);q4(this,r4(this,"display-settings")||{})},t4=function(a){if(1===
a.A.zh||1===a.videoData.zh||"alwayson"===g.IB(a.videoData,"yt:cc"))return!0;
if(2===a.A.zh){var b=r4(a,"module-enabled");if(null!=b)return!!b}if(a.videoData.captionTracks.length)var c=a.player.getAudioTrack().Wr;return"ON"===c||"on"===g.IB(a.videoData,"yt:cc")},u4=function(a,b){if(a.o&&(void 0===b||!b)||!a.videoData.captionTracks.length)return!1;
var c=a.player.getAudioTrack();return!!c.yo||"FORCED_ON"===c.Wr},w4=function(a,b){if(a.u){if(a.G&&a.G.o)return a.G.o;
var c=b;c||(c=a.Ca?!1:a.Aa?!1:!0);c=a.u.bj(c);for(var d=[a.videoData.captionsLanguagePreference,a.A.captionsLanguagePreference,g.IB(a.videoData,"yt:cc_default_lang")],e=0;e<d.length;e++)for(var f=0;f<c.length;f++)if(A3(c[f])===d[e])return c[f];return a.G&&a.G.us?a.G.us:(d=c.find(function(k){return k.isDefault}))?d:c[0]||v4(a)}return null},v4=function(a){return a.G&&a.G.yo},x4=function(a){var b=v4(a);
return!!b&&a.o===b},qwa=function(a,b){for(var c=a.J.app.C.xa().textTracks,d=a.o.toString(),e=0;e<c.length;e++){var f=c[e];
f.id===d&&(b?"showing"!==f.mode&&(f.mode="showing"):"showing"===f.mode&&(f.mode="disabled"))}},z4=function(a,b,c){a.loaded&&a.unload();
null!=c&&(a.U=c,a.U&&y4(a,"module-enabled",!!b));a.o=b;u4(a)&&(a.o=v4(a));a.load()},rwa=function(a,b){var c=a.za.getVideoContentRect(!0).height;
if(!c)return null;var d=a.o?a.o.languageCode:null;!b.params.o&&d&&owa.test(d)&&(b.params.o=1);d=a.za.getPlayerSize();switch(null!=b.params.Ik?b.params.Ik:1<b.o.length?1:0){case 1:return new J3(b,a.B,a.F,c,d.width,d.height,a.A.experiments);case 2:return new K3(b,a.B,a.F,c,d.width,d.height,a.A.experiments);default:return new I3(b,a.B,a.F,c,d.width,d.height,a.A.experiments)}},q4=function(a,b,c){c=void 0===c?!1:c;
var d=A4.Hb;a.B={};g.Sa(a.B,A4);a.B.Hb={};g.Sa(a.B.Hb,d);a.F={Hb:{}};var e=b.backgroundOverride?a.F:a.B,f=b.background||d.background;T3.test(f);e.Hb.background=f;e=b.colorOverride?a.F:a.B;f=b.color||d.color;T3.test(f);e.Hb.color=f;e=b.windowColorOverride?a.F:a.B;f=b.windowColor||A4.windowColor;T3.test(f);e.windowColor=f;e=b.backgroundOpacityOverride?a.F:a.B;f=b.backgroundOpacity;null==f&&(f=d.backgroundOpacity);e.Hb.backgroundOpacity=f;e=b.fontSizeIncrementOverride?a.F:a.B;f=b.fontSizeIncrement;null==
f&&(f=d.fontSizeIncrement);e.Hb.fontSizeIncrement=f;f=b.fontStyleOverride?a.F:a.B;e=b.fontStyle;null==e&&(e=d.bold&&d.wf?3:d.bold?1:d.wf?2:0);f=f.Hb;switch(e){case 1:f.bold=!0;delete f.wf;break;case 2:delete f.bold;f.wf=!0;break;case 3:f.bold=!0;f.wf=!0;break;default:delete f.bold,delete f.wf}e=b.textOpacityOverride?a.F:a.B;f=b.textOpacity;null==f&&(f=d.textOpacity);e.Hb.textOpacity=f;e=b.windowOpacityOverride?a.F:a.B;f=b.windowOpacity;null==f&&(f=A4.windowOpacity);e.windowOpacity=f;e=b.charEdgeStyleOverride?
a.F:a.B;f=b.charEdgeStyle;null==f&&(f=d.charEdgeStyle);e.Hb.charEdgeStyle=f;e=b.fontFamilyOverride?a.F:a.B;f=b.fontFamily;null==f&&(f=d.fontFamily);e.Hb.fontFamily=f;a.loaded&&a.Xv();c&&y4(a,"display-settings",b)},twa=function(a,b){if(b&&!a.H){var c=Qva({o:0,
lang:"pt-BR"});a.H=[c,new L3(c.start,c.end-c.start,0,c.id,"As legendas ficam assim")];g.JL(a.player,a.H)}else!b&&a.H&&(swa(a,a.H),a.H=null)},swa=function(a,b){g.XT(a.player.app,b,void 0);
(0,g.y)(b,function(c){g.gb(this.R,c)},a);
a.T.Za()},r4=function(a,b){if(!a.ea)return null;
try{var c=a.ea.get(b)}catch(d){a.ea.remove(b)}return c},y4=function(a,b,c){if(a.ea)try{a.ea.set(b,c)}catch(d){}};
g.pM.prototype.Tl=g.da(11,function(){for(var a=g.he(document,"track",void 0,this.o),b=0;b<a.length;b++)g.Ae(a[b])});
g.tM.prototype.Tl=g.da(10,function(){this.o.Tl()});
g.pM.prototype.sn=g.da(9,function(){return!!this.o.textTracks});
g.tM.prototype.sn=g.da(8,function(){return this.o.sn()});
g.pM.prototype.Nl=g.da(7,function(a){for(var b=0;b<a.length;b++)this.o.appendChild(a[b])});
g.tM.prototype.Nl=g.da(6,function(a){this.o.Nl(a)});
g.AC.prototype.Lj=g.da(5,function(){});
g.pM.prototype.Lj=g.da(4,function(){return!(!this.o.textTracks||!this.o.textTracks.addEventListener)});
g.tM.prototype.Lj=g.da(3,function(){return this.o.Lj()});
g.Yu.prototype.Lo=g.da(1,function(a){return(a=this.ag(a))?a.o:0});
g.Jx.prototype.Lo=g.da(0,function(){return 0});
var owa=/^(ar|ckb|dv|he|iw|fa|nqo|ps|sd|ug|ur|yi|.*[-_](Adlm|Arab|Hebr|Nkoo|Rohg|Thaa))(?!.*[-_](Latn|Cyrl)($|-|_))($|-|_)/i;yva.prototype.bj=function(a){return a?this.o.concat(this.u):this.o};
g.r(C3,g.z);g.h=C3.prototype;g.h.bj=function(a){return this.u.bj(a)};
g.h.np=function(){};
g.h.pp=function(){};
g.h.oh=function(){};
g.h.qk=function(){return""};
g.h.oC=function(){return!1};
g.h.Y=function(){this.oh();g.z.prototype.Y.call(this)};
g.r(D3,C3);D3.prototype.np=function(a,b,c){var d=this;this.ha();b=this.qk(a,b);this.oh();this.o=g.wq(b,{format:"RAW",onSuccess:function(e){d.o=null;c(e.responseText,a)},
withCredentials:!0})};
D3.prototype.pp=function(a){if(this.audioTrack)for(var b=g.p(this.audioTrack.captionTracks),c=b.next();!c.done;c=b.next())B3(this.u,c.value);a()};
D3.prototype.qk=function(a,b){var c=a.Ac(),d={fmt:b};if("srv3"===b||"3"===b||"json3"===b)g.kl()?Object.assign(d,{xorb:2,xobt:1,xovt:1}):Object.assign(d,{xorb:2,xobt:3,xovt:3});a.translationLanguage&&(d.tlang=A3(a));return g.gq(c,d)};
D3.prototype.oh=function(){this.o&&this.o.abort()};
E3.prototype.contains=function(a){a=g.sb(this.segments,a);return 0<=a||0>a&&1===(-a-1)%2};
E3.prototype.length=function(){return this.segments.length/2};
g.r(F3,g.z);g.h=F3.prototype;g.h.Y=function(){g.z.prototype.Y.call(this);this.u&&this.u.cancel()};
g.h.UB=function(){this.seekTo(this.player.getCurrentTime())};
g.h.seekTo=function(a){a-=this.player.Gb();var b=this.o;this.o=g.Xa(this.L.Ug(a).o);b!==this.o&&this.H&&this.H()};
g.h.reset=function(){this.B=new E3;this.u&&(this.u.cancel(),this.u=null)};
g.h.Bz=function(){this.ha();var a;if(a=null!=this.o)a=this.o,a=a.o.ih(a);!a||this.u||this.o&&30<this.o.startTime-this.player.getCurrentTime()||(a=this.o.Kh(),a.o[0].duration?(this.B.contains(a.o[0].u)||Bva(this,a),this.o=g.Xa(a.o)):!g.P(this.M.experiments,"force_caption_seek_for_live_killswitch")&&this.o&&this.o.F&&this.o.F+this.player.Gb()<this.player.getCurrentTime()&&this.seekTo(this.player.getCurrentTime()));this.G.start()};
g.r(G3,C3);g.h=G3.prototype;g.h.np=function(a,b,c){var d=this;this.oh();b=Dva(this,a.getId());b||(b=a.languageCode,b=this.ka.u?Eva(this,b,"386"):Eva(this,b));if(b){var e=1E3*(b.index.Lo(b.index.sf())-b.index.Cd(b.index.sf()));this.o=new F3(new g.Jw,this.J,b,function(f,k){c(f,a,k,e)},this.C||g.ot(b.info),function(){d.o&&d.o.reset();
d.A=!0})}};
g.h.oC=function(){var a=this.A;this.A=!1;return a};
g.h.pp=function(a){var b;this.C?b=[new g.$s({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.$s({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]:b=this.ka.u?Cva(this,"386"):Cva(this);b=g.p(b);for(var c=b.next();!c.done;c=b.next())B3(this.u,c.value);a()};
g.h.oh=function(){this.o&&(this.o.dispose(),this.o=null)};
g.h.qk=function(){return""};
g.r(H3,C3);H3.prototype.np=function(a,b,c){var d=this;this.ha();b=this.qk(a,b);this.oh();this.o=g.wq(b,{format:"RAW",onSuccess:function(e){d.o=null;c(e.responseText,a)},
withCredentials:!0})};
H3.prototype.pp=function(a){var b=this,c=this.A,d={type:"list",tlangs:1,v:this.videoId,vssids:1};this.cz&&(d.asrs=1);c=g.gq(c,d);this.oh();this.o=g.wq(c,{format:"RAW",onSuccess:function(e){b.o=null;if((e=e.responseXML)&&e.firstChild){for(var f=e.getElementsByTagName("track"),k=0;k<f.length;k++){var l=f[k],m=l.getAttribute("lang_code"),n=l.getAttribute("lang_translated"),q=l.getAttribute("name"),t=l.getAttribute("kind"),u=l.getAttribute("id"),w="true"===l.getAttribute("lang_default"),B="true"===l.getAttribute("cantran");
l=l.getAttribute("vss_id");B3(b.u,new g.$s({languageCode:m,languageName:n,name:q,kind:t,id:u,is_servable:!0,is_translateable:B,vss_id:l,is_default:w}))}e=e.getElementsByTagName("target");f=e.length;for(k=0;k<f;k++)m={languageCode:e[k].getAttribute("lang_code"),languageName:e[k].getAttribute("lang_translated"),languageOriginal:e[k].getAttribute("lang_original"),id:e[k].getAttribute("id"),isDefault:"true"===e[k].getAttribute("lang_default")},b.C[m.languageCode]=m.languageName,b.B.push(m)}a()},
withCredentials:!0})};
H3.prototype.qk=function(a,b){var c=this.A,d={v:this.videoId,type:"track",lang:a.languageCode,name:a.getName(),kind:a.kind,fmt:b};a.translationLanguage&&(d.tlang=A3(a));return c=g.gq(c,d)};
H3.prototype.oh=function(){this.o&&this.o.abort()};
var T3=/^#(?:[0-9a-f]{3}){1,2}$/i;var Gva=["left","right","center","justify"];g.r(I3,g.W);g.h=I3.prototype;g.h.mL=function(a,b){var c=g.Oh(this.element,this.element.parentElement);this.ma=a-c.x;this.ua=b-c.y;g.J(this.element,"ytp-dragging")};
g.h.lL=function(a,b){var c=g.Rh(this.element),d=a-this.ma-.02*this.playerWidth,e=b-this.ua-.02*this.playerHeight,f=(d+c.width/2)/this.maxWidth*3;f=Math.floor(g.Ud(f,0,2));var k=(e+c.height/2)/this.wa*3;k=Math.floor(g.Ud(k,0,2));var l=f+3*k;d=(d+f/2*c.width)/this.maxWidth;d=100*g.Ud(d,0,1);c=(e+k/2*c.height)/this.wa;c=100*g.Ud(c,0,1);this.u.params.cf=l;this.u.params.Pf=c;this.u.params.Ae=d;this.o.cf=l;this.o.Pf=c;this.o.Ae=d;this.PC()};
g.h.jL=function(){g.Hn(this.element,"ytp-dragging")};
g.h.PC=function(){this.Jj(this.C)};
g.h.Jj=function(a){var b=Math.min(this.ry(),this.maxWidth),c=this.qy(),d="";3===this.u.params.o&&(d="rotate(180deg)");g.H(this.element,{top:0,left:0,right:"",bottom:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"96%","max-height":"96%",margin:"",transform:""});this.Qr(a);a={transform:d,top:"",left:"",width:b?b+"px":"",height:c?c+"px":"","max-width":"","max-height":""};var e=.96*this.o.Ae+2;d=this.o.cf;switch(d){case 0:case 3:case 6:b=this.o.Hb.fontSizeIncrement;!g.P(this.experiments,"web_player_ignore_left_percentage_for_large_font_killswitch")&&
b&&2<b&&2!==this.o.o&&3!==this.o.o&&(e=2);a.left=e+"%";break;case 1:case 4:case 7:a.left=e+"%";e=this.B.offsetWidth;b||e?(b=b||e+1,a.width=b+"px",a["margin-left"]=b/-2+"px"):a.transform+=" translateX(-50%)";break;case 2:case 5:case 8:a.right=100-e+"%"}b=.96*this.o.Pf+2;switch(d){case 0:case 1:case 2:a.top=b+"%";break;case 3:case 4:case 5:a.top=b+"%";(c=c||this.element.clientHeight)?(a.height=c+"px",a["margin-top"]=c/-2+"px"):a.transform+=" translateY(-50%)";break;case 6:case 7:case 8:a.bottom=100-
b+"%"}g.H(this.element,a)};
g.h.Qr=function(a){var b;for(b=0;b<a.length&&a[b]===this.C[b];b++);if(this.T||this.C.length>b)b=0,this.T=!1,this.C=[],this.F=this.Z=this.U=null,g.ye(this.B);for(;b<a.length;b++)Kva(this,a[b])};
g.h.ry=function(){return 0};
g.h.qy=function(){return 0};
g.h.toString=function(){return g.W.prototype.toString.call(this)};g.r(J3,I3);J3.prototype.Qr=function(a){var b=this.u.o;I3.prototype.Qr.call(this,a);for(a=a.length;a<b.length;a++){var c=b[a];if(f&&c.o===e)var d=f;else{d={};g.Sa(d,c.o);g.Sa(d,uwa);var e=c.o;var f=d}Kva(this,c,d)}};
var uwa={IG:!0};g.r(K3,I3);g.h=K3.prototype;g.h.PC=function(){g.yn(this.ea)};
g.h.YM=function(){g.Hn(this.element,"ytp-rollup-mode");this.Jj(this.Ca,!0)};
g.h.qy=function(){return this.A?this.L:this.H};
g.h.ry=function(){return this.A?this.H:this.L};
g.h.Jj=function(a,b){this.Ca=a;if(this.u.params.u){for(var c=0,d=0;d<this.C.length&&c<a.length;d++)this.C[d]===a[c]&&c++;0<c&&c<a.length&&(a=this.C.concat(a.slice(c)));this.za=this.L;this.H=this.L=0;I3.prototype.Jj.call(this,a);Pva(this,b);I3.prototype.Jj.call(this,a)}else I3.prototype.Jj.call(this,a)};g.r(L3,g.nC);L3.prototype.toString=function(){return g.nC.prototype.toString.call(this)};g.r(M3,g.nC);M3.prototype.toString=function(){return g.nC.prototype.toString.call(this)};
var N3=0;g.r(O3,g.z);O3.prototype.A=function(){return[]};
O3.prototype.reset=function(){};g.r(P3,O3);P3.prototype.reset=function(){this.H={};this.u=this.o=null;this.G=!0};
P3.prototype.A=function(a,b){var c=a.firstChild;c.getAttribute("format");b=b||0;Number.isFinite(b);c=Array.from(c.childNodes);c=g.p(c);for(var d=c.next();!d.done;d=c.next())if(d=d.value,1===d.nodeType)switch(d.tagName){case "head":var e=d;break;case "body":var f=d}if(e)for(e=Array.from(e.childNodes),e=g.p(e),c=e.next();!c.done;c=e.next())if(c=c.value,1===c.nodeType)switch(c.tagName){case "pen":d=c.getAttribute("id");var k=this.B,l={},m=c.getAttribute("p");m&&g.Sa(l,this.B[m]);m=R3(c,"b");null!=m&&
(l.bold=m);m=R3(c,"i");null!=m&&(l.wf=m);m=R3(c,"u");null!=m&&(l.underline=m);m=S3(c,"et");null!=m&&(l.charEdgeStyle=m);m=S3(c,"of");null!=m&&(l.offset=m);m=U3(c,"bc");null!=m&&(l.background=m);m=U3(c,"ec");null!=m&&(l.Zr=m);m=U3(c,"fc");null!=m&&(l.color=m);m=S3(c,"fs");null!=m&&0!==m&&(l.fontFamily=m);m=Q3(c,"sz");void 0!==m&&(l.fontSizeIncrement=m/100-1);m=Q3(c,"bo");void 0!==m&&(l.backgroundOpacity=m/255);m=Q3(c,"fo");void 0!==m&&(l.textOpacity=m/255);m=S3(c,"rb");null!=m&&10!==m&&0!==m&&(l.lc=
10<m?m-1:m);c=S3(c,"hg");null!=c&&(l.Zy=c);k[d]=l;break;case "ws":d=c.getAttribute("id");this.L[d]=Tva(this,c);break;case "wp":d=c.getAttribute("id"),this.M[d]=Uva(this,c)}if(f){e=b;c=[];f=Array.from(f.childNodes);f=g.p(f);for(d=f.next();!d.done;d=f.next())if(d=d.value,1===d.nodeType)switch(d.tagName){case "w":this.o=Vva(this,d,e,!1);(d=this.H[this.o.id])&&d.end>this.o.start&&(d.end=this.o.start);this.H[this.o.id]=this.o;c.push(this.o);break;case "p":var n=e;k=[];l=d.getAttribute("w")||this.C;m=!!R3(d,
"a");n=(Q3(d,"t")||0)+n;var q=Q3(d,"d")||5E3;m||(!this.G&&this.u&&this.u.windowId===l&&this.u.end>n&&(this.u.end=n),this.u&&"\n"===this.u.text&&(this.u.text=""));var t=m?6:5,u=d.getAttribute("p");u=u?this.B[u]:null;var w=Array.from(d.childNodes);w.length&&(this.G=null!=d.getAttribute("d"));for(var B=0;B<w.length;B++){var D=w[B],E=void 0;0<B&&(m=!0);var F=void 0;1===D.nodeType&&(F=D);if(F&&"s"===F.tagName){if((D=(D=F.getAttribute("p"))?this.B[D]:null)&&D.lc&&(1===D.lc?(D=w.slice(B,B+4),4===D.length&&
(E=Sva(n,q,l,m,t,D,this.B),B+=3)):E=Sva(n,q,l,m,t,[F],this.B)),!E){var G=F;E=n;F=q;D=l;var ba=m,na=t,tb=G.textContent?G.textContent:"",Za=G.getAttribute("p");Za=Za?this.B[Za]:null;G=Q3(G,"t")||0;E=new L3(E+G,F-G,na,D,tb,ba,Za)}}else E=new L3(n,q,t,l,D.textContent||"",m,u);k.push(E);this.u=E}if(0<k.length)for(k[0].windowId===this.C&&(this.o=Vva(this,d,e,!0),c.push(this.o)),d=g.p(k),k=d.next();!k.done;k=d.next())k=k.value,k.windowId=this.o.id,this.o.o.push(k),c.push(k)}e=c}else e=[];return e};var vwa=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.r(V3,O3);V3.prototype.reset=function(){this.u.clear()};
V3.prototype.A=function(a,b){var c=JSON.parse(a);if(!c)return[];if(c.pens)for(var d=0,e=g.p(c.pens),f=e.next();!f.done;f=e.next()){f=f.value;var k={},l=f.pParentId;l&&Object.assign(k,this.o.get(l));f.bAttr&&(k.bold=!0);f.iAttr&&(k.wf=!0);f.uAttr&&(k.underline=!0);l=f.ofOffset;null!=l&&(k.offset=l);void 0!==f.szPenSize&&(k.fontSizeIncrement=f.szPenSize/100-1);l=f.etEdgeType;null!=l&&(k.charEdgeStyle=l);void 0!==f.ecEdgeColor&&(k.Zr=W3(f.ecEdgeColor));l=f.fsFontStyle;null!=l&&0!==l&&(k.fontFamily=l);
void 0!==f.fcForeColor&&(k.color=W3(f.fcForeColor));void 0!==f.foForeAlpha&&(k.textOpacity=f.foForeAlpha/255);void 0!==f.bcBackColor&&(k.background=W3(f.bcBackColor));void 0!==f.boBackAlpha&&(k.backgroundOpacity=f.boBackAlpha/255);(l=f.rbRuby)&&10!==l&&(k.lc=10<l?l-1:l,k.Nf=vwa.get(k.lc));f.hgHorizGroup&&(k.Zy=f.hgHorizGroup);this.o.set(d++,k)}if(c.wsWinStyles)for(d=0,e=g.p(c.wsWinStyles),f=e.next();!f.done;f=e.next())f=f.value,k={},(l=f.wsParentId)?Object.assign(k,this.C.get(l)):Object.assign(k,
this.F),void 0!==f.mhModeHint&&(k.Ik=f.mhModeHint),void 0!==f.juJustifCode&&(k.textAlign=f.juJustifCode),void 0!==f.pdPrintDir&&(k.o=f.pdPrintDir),void 0!==f.sdScrollDir&&(k.A=f.sdScrollDir),void 0!==f.wfcWinFillColor&&(k.windowColor=W3(f.wfcWinFillColor)),void 0!==f.wfoWinFillAlpha&&(k.windowOpacity=f.wfoWinFillAlpha/255),this.C.set(d++,k);if(c.wpWinPositions)for(d=0,e=g.p(c.wpWinPositions),f=e.next();!f.done;f=e.next())f=f.value,k={},(l=f.wpParentId)&&Object.assign(k,this.B.get(l)),void 0!==f.ahHorPos&&
(k.Ae=f.ahHorPos),void 0!==f.apPoint&&(k.cf=f.apPoint),void 0!==f.avVerPos&&(k.Pf=f.avVerPos),void 0!==f.ccCols&&(k.Ah=f.ccCols),void 0!==f.rcRows&&(k.u=f.rcRows),this.B.set(d++,k);if(c.events)for(d=[],c=g.p(c.events),e=c.next();!e.done;e=c.next()){var m=e.value;e=(m.tStartMs||0)+b;f=m.dDurationMs||0;if(m.id)k=String(m.id),e=Wva(this,m,e,f,k),d.push(e),this.u.set(k,e);else{m.wWinId?k=m.wWinId.toString():(k="_"+N3++,l=Wva(this,m,e,f,k),d.push(l),this.u.set(k,l));0===f&&(f=5E3);l=this.u.get(k);var n=
!!m.aAppend,q=n?6:5,t=m.segs,u=null;m.pPenId&&(u=this.o.get(m.pPenId));for(m=0;m<t.length;m++){var w=t[m],B=w.utf8;if(B){var D=w.tOffsetMs||0,E=null;w.pPenId&&(E=this.o.get(w.pPenId));if(2===(null!=l.params.Ik?l.params.Ik:1<l.o.length?1:0)&&n&&"\n"===B)continue;if(w=E&&1===E.lc)if(w=m,w+3>=t.length||!t[w+1].pPenId||!t[w+2].pPenId||!t[w+3].pPenId)w=!1;else{var F=t[w+1].pPenId;(F=this.o.get(F))&&F.lc&&2===F.lc?(F=t[w+2].pPenId,F=this.o.get(F),!F||!F.lc||3>F.lc?w=!1:(F=t[w+3].pPenId,w=(F=this.o.get(F))&&
F.lc&&2===F.lc?!0:!1)):w=!1}if(w){D=t[m+1].utf8;w=t[m+3].utf8;F=t[m+2].utf8;var G=this.o.get(t[m+2].pPenId);B=Rva(B,D,F,w,G);n=new L3(e,f,q,k,B,n,E);m+=3}else n=new L3(e+D,f-D,q,l.id,B,n,E||u);n&&(d.push(n),l.o.push(n))}n=!0}}}else d=[];return d};Y3.prototype.clear=function(){this.A=this.time=this.mode=0;this.o=[];this.reset()};
Y3.prototype.reset=function(){this.mode=0;this.B.reset(0);this.C.reset(1)};
var Xva=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];Z3.prototype.set=function(a){this.type=a};
Z3.prototype.get=function(){return this.type};
$3.prototype.clear=function(){this.state=0};
$3.prototype.update=function(){this.state=2===this.state?1:0};
$3.prototype.isValid=function(){return 0!==this.state};
$3.prototype.matches=function(a,b){return this.isValid()&&a===this.Mi&&b===this.xh};
bwa.prototype.reset=function(){this.timestamp=this.o=0};
a4.prototype.updateTime=function(a){for(var b=1;15>=b;++b)for(var c=1;32>=c;++c)this.A[b][c].timestamp=a};
a4.prototype.debugString=function(){for(var a="\n",b=1;15>=b;++b){for(var c=1;32>=c;++c){var d=this.A[b][c];a=0===d.o?a+"_":a+String.fromCharCode(d.o)}a+="\n"}return a};
a4.prototype.reset=function(a){for(var b=0;15>=b;b++)for(var c=0;32>=c;c++)this.A[b][c].reset();this.B=a;this.o=0;this.u=this.row=1};
var cwa=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],dwa=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],ewa=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],fwa=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];g4.prototype.reset=function(a,b){this.C=b;this.style.set(2);this.u=this.F;this.B=this.G;this.o=this.u;var c=(a<<2)+(b<<1);this.F.reset(c);this.G.reset(c);this.text.reset((a<<2)+(b<<1)+1)};
X3.prototype.reset=function(a){this.C=a;this.o.clear();this.B=this.A;this.A.reset(a,0);this.F.reset(a,1)};kwa.prototype.C=function(){};g.r(i4,kwa);i4.prototype.C=function(a,b,c,d,e){if(c<d){var f="_"+N3++;c=c/1E3-this.G;d=d/1E3-this.G;a=new M3(c,d-c,5,f,{textAlign:0,cf:0,Ae:2.5*b,Pf:5.33*a});e=new L3(c,d-c,5,f,e);this.A.push(a);this.A.push(e)}};
g.r(l4,O3);l4.prototype.A=function(a){a=new i4(a,a.byteLength,this.u);if(lwa(a)){for(;a.o<a.u.byteLength;)for(0===a.version?a.B=k4(a)*(1E3/45):1===a.version&&(a.B=4294967296*k4(a)+k4(a)),a.F=j4(a);0<a.F;a.F--){var b=j4(a),c=j4(a),d=j4(a);b&4&&(b&3)===this.track&&(0===this.track||1===this.track)&&(b=this.o,b.o.push({time:a.B,type:this.track,sx:c,tx:d,order:b.o.length}))}awa(this.o,a);return a.A}return[]};
l4.prototype.reset=function(){this.o.clear()};g.r(n4,O3);
n4.prototype.A=function(a,b){for(var c=[],d=a.split(wwa),e=1;e<d.length;e++){var f=d[e],k=b;if(""!==f&&!xwa.test(f)){var l=B4.exec(f);if(l&&4<=l.length){var m=o4(l[1]),n=o4(l[2])-m;m+=k;var q=(l=l[3])?l.split(" "):[];l={};var t=null,u="",w=null,B="";l.textAlign=2;q=g.p(q);for(var D=q.next();!D.done;D=q.next())if(D=D.value.split(":"),2===D.length){var E=D[1];switch(D[0]){case "line":D=E.split(",");D[0].endsWith("%")&&(t=D[0],l.Pf=Number.parseInt(t,10),2===D.length&&(u=D[1].trim()));break;case "position":D=
E.split(",");w=D[0];l.Ae=Number.parseInt(w,10);2===D.length&&(B=D[1].trim());break;case "align":switch(E){case "start":l.textAlign=0;break;case "middle":l.textAlign=2;break;case "end":l.textAlign=1}}}t||(l.Pf=100,u||(u="end"));if(!w)switch(l.textAlign){case 0:l.Ae=0;break;case 1:l.Ae=100;break;default:l.Ae=50}t=0;switch(u){case "center":t+=3;break;case "end":t+=6;break;default:t+=0}switch(B){case "line-left":t+=0;break;case "center":t+=1;break;case "line-right":t+=2;break;default:switch(l.textAlign){case 0:t+=
0;break;case 2:t+=1;break;case 1:t+=2}}l.cf=0>t||8<t?7:t;f=f.substring(B4.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");B=l;l=f;f={};if(0>l.indexOf("<")&&0>l.indexOf("&"))k=nwa(m,n,5,B),n=new L3(m,n,5,k.id,l,!1,g.Pb(f)?void 0:f),c.push(k),c.push(n),k.o.push(n);else for(u=l.split(ywa),1===u.length?(l=5,B=nwa(m,n,l,B)):(t=l=6,B=Object.assign({Ah:32},B),B=new M3(m,n,t,"_"+N3++,B)),c.push(B),t=m,w=0;w<u.length;w++)q=u[w],0===w%2?(D=g.y1("<html>"+q+"</html>"),D.getElementsByTagName("parsererror").length?
(E=D.createElement("span"),E.appendChild(D.createTextNode(q))):E=D.firstChild,mwa(this,t,n-(t-m),l,B,0<w,E,f,c)):t=o4(q)+k}B4.lastIndex=0}}return c};
var xwa=/^NOTE/,wwa=/(?:\r\n|\r|\n){2,}/,B4=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),ywa=/<((?:[\d]{2}:)?[\d]{2}:[\d]{2}\.[\d]{3})>/;g.r(p4,g.z);p4.prototype.clear=function(){this.o&&this.o.dispose();this.o=null};
p4.prototype.reset=function(){this.o&&this.o.reset()};
p4.prototype.Y=function(){g.z.prototype.Y.call(this);this.clear()};var A4={windowColor:"#080808",windowOpacity:0,textAlign:2,cf:7,Ae:50,Pf:100,Hb:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.r(s4,g.ZL);g.h=s4.prototype;g.h.Y=function(){if(this.C||this.L){var a=this.J.app.C;a&&!a.ha()&&a.Tl()}else twa(this,!1);g.ZL.prototype.Y.call(this)};
g.h.load=function(){var a=this;g.ZL.prototype.load.call(this);var b=!g.P(this.A.experiments,"web_player_captions_track_list_changed_killswitch");this.G=this.player.getAudioTrack();if(this.u)this.o&&(this.fa.clear(),this.C?qwa(this,!0):3!==this.player.getPresentingPlayerType()&&this.u.np(this.o,"json3",function(d,e,f,k){if(d){a.u.oC()&&(a.R=[],g.RR(a.J.app,"captions",void 0),a.T.Za(),a.fa.reset());var l=a.fa;f=f||0;k=k||0;if(l.u.ia("html5_disable_rawcc_killswitch")){if("string"!==typeof d){var m=new DataView(d);
8<=m.byteLength&&1718909296===m.getUint32(4)&&(m=g.nv(m,0,1835295092),d=d.slice(m.dataOffset,m.dataOffset+m.size),m4(d)||(d=g.eg(new Uint8Array(d))))}}else"string"===typeof d||m4(d)||(m=new DataView(d),d=8>=m.byteLength||1718909296!==m.getUint32(4)?"":(m=g.nv(m,0,1835295092))&&m.size?g.eg(new Uint8Array(d.slice(m.dataOffset,m.dataOffset+m.size))):"");if(d)try{if("string"!==typeof d){var n=d,q=f,t=k;if(!m4(n))throw Error("Invalid binary caption track data");l.o||(l.o=new l4(t,e));var u=l.o.A(n,q)}else{if("WEBVTT"===
d.substring(0,6))e=d,t=f,l.o||(l.o=new n4),q=l.o.A(e,t),.01>Math.random()&&g.gr(Error("Deprecated subtitles format in web player: WebVTT")),n=q;else b:{q=d;if("{"===q[0])try{l.o||(l.o=new V3(pwa(e)));n=l.o.A(q,f);break b}catch(G){g.fr(G);n=[];break b}t=g.y1(q);if(!t||!t.firstChild){var w=Error("Invalid caption track data");w.params=q;throw w;}if("timedtext"===t.firstChild.tagName){if(3===Number(t.firstChild.getAttribute("format"))){l.o||(l.o=new P3(pwa(e),l.u));n=l.o.A(t,f);break b}var B=Error("Unsupported subtitles format in web player (Format2)");
B.params=q;throw B;}if("transcript"===t.firstChild.tagName){var D=Error("Unsupported subtitles format in web player (Format1)");D.params=q;throw D;}var E=Error("Invalid caption track data");E.params=q;throw E;}u=n}var F=u}catch(G){g.fr(G),l.clear(),F=[]}else F=[];g.JL(a.player,F);!a.U||a.L||x4(a)||g.dz(a.A)||g.ez(a.A)||(a.aa.qf(),F=Qva({cf:0,Ae:5,Pf:5,u:2,textAlign:0,o:0,lang:"pt-BR"}),a.ba=[F],l=["Clique em "," para configura\u00e7\u00f5es"],a.ma||(u=new g.RM(g.EN()),g.A(a,u),a.ma=u.element),u=F.end-
F.start,(e=g.at(a.o))&&a.ba.push(new L3(F.start,u,0,F.id,e)),a.ba.push(new L3(F.start,u,0,F.id,l[0]),new L3(F.start,u,0,F.id,a.ma,!0),new L3(F.start,u,0,F.id,l[1],!0)),g.JL(a.player,a.ba),a.aa.Za());!a.U||a.L||x4(a)||(y4(a,"module-enabled",!0),a.G&&(a.G.o=a.o),(F=g.V(a.player.app))&&g.RI(F.C));a.U=!1}}),!b||this.C||this.L||x4(this)||this.player.sa("captionschanged",z3(this.o))),b||(this.o&&!x4(this)?this.player.sa("captionschanged",z3(this.o)):this.player.sa("onCaptionsTrackListChanged"));
else{var c;this.ua?c=new G3(this.videoData.ka,this.player):this.Aa?c=new D3(this.A,this.videoData,this.player.getAudioTrack()):c=new H3(this.videoData.Sl,this.videoData.videoId,this.videoData.captionsLanguagePreference||this.A.captionsLanguagePreference||g.IB(this.videoData,"yt:cc_default_lang")||this.A.Zc,this.videoData.Vr,this.A);this.u=c;g.A(this,this.u);c.pp(function(){var d;a.U||t4(a)?d=w4(a,a.U):u4(a)&&(d=v4(a));if(a.C||a.L){for(var e=a.u.bj(!0),f=[],k=0;k<e.length;k++){var l=e[k],m=g.ue("TRACK");
m.setAttribute("kind","subtitles");m.setAttribute("label",g.at(l));m.setAttribute("srclang",A3(l));m.setAttribute("id",l.toString());a.L||m.setAttribute("src",a.u.qk(l,"vtt"));l===d&&m.setAttribute("default","1");f.push(m)}d=a.J.app.C;d.Nl(f);f=d.xa();a.wa&&a.Z.N(f.textTracks,"change",a.AN)}else!a.o&&d&&z4(a,d),a.player.sa("onCaptionsTrackListChanged"),a.player.sa("onApiChange")})}};
g.h.unload=function(){this.C&&this.o?qwa(this,!1):(this.aa&&this.aa.qf(),g.RR(this.player.app,"captions",void 0),this.R=[],this.u&&this.u.oh(),this.fa.clear(),this.H&&g.JL(this.player,this.H),this.Xv());g.ZL.prototype.unload.call(this);var a=g.V(this.player.app);a&&g.RI(a.C);this.player.sa("captionschanged",{})};
g.h.create=function(){(this.ra?this.C||this.L:u4(this)||t4(this))&&this.load()};
g.h.getTrackById=function(a){for(var b=this.u.bj(!0),c=0;c<b.length;c++)if(b[c].toString()===a)return b[c];return null};
g.h.AN=function(){for(var a=this.J.app.C.xa().textTracks,b=null,c=0;c<a.length;c++)"showing"===a[c].mode&&(b=this.getTrackById(a[c].id));(this.loaded?this.o:null)!==b&&z4(this,b,!0)};
g.h.fP=function(){!this.o&&this.C||this.unload()};
g.h.ld=function(a){this.R.push(a);this.T.Za()};
g.h.Ve=function(a){g.gb(this.R,a);this.u instanceof G3&&this.u.C&&g.XT(this.player.app,[a],void 0);this.T.Za()};
g.h.mO=function(a){if(a instanceof M3){var b=this.M[a.id];b&&b.u!==a&&(b.dispose(),delete this.M[a.id],b=null);b||(b=rwa(this,a))&&(this.M[a.id]=b)}else b=a.windowId,this.ga[b]||(this.ga[b]=[]),this.ga[b].push(a)};
g.h.sO=function(){swa(this,this.ba);this.ba=null};
g.h.BD=function(){var a=this;this.T.stop();g.Qb(this.ga);this.R.sort(g.pC);var b=this.R;if(this.H){var c=(0,g.Be)(b,function(d){return-1===this.H.indexOf(d)},this);
c.length&&(b=c)}(0,g.y)(b,this.mO,this);g.Cb(this.M,function(d,e){a.ga[e]?(d.element.parentNode||(d instanceof K3||d instanceof J3||g.Fb(a.M,function(f,k){k!==e&&f.u.params.cf===d.u.params.cf&&f.u.params.Ae===d.u.params.Ae&&f.u.params.Pf===d.u.params.Pf&&(f.dispose(),delete a.M[k]);return k===e},a),g.NL(a.player,d.element,4)),d.Jj(a.ga[e])):(d.dispose(),delete a.M[e])},this)};
g.h.zO=function(){q4(this,{},!0);g.P(this.A.experiments,"web_player_disable_publish_captions_settings_changed_on_reset")||this.player.sa("captionssettingschanged")};
g.h.YF=function(){var a=A4.Hb;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.wf?3:a.bold?1:a.wf?2:0,textOpacity:a.textOpacity,windowColor:A4.windowColor,windowOpacity:A4.windowOpacity};var b=r4(this,"display-settings")||{};null!=b.background&&(a.background=b.background);null!=b.backgroundOverride&&(a.backgroundOverride=b.backgroundOverride);null!=b.backgroundOpacity&&
(a.backgroundOpacity=b.backgroundOpacity);null!=b.backgroundOpacityOverride&&(a.backgroundOpacityOverride=b.backgroundOpacityOverride);null!=b.charEdgeStyle&&(a.charEdgeStyle=b.charEdgeStyle);null!=b.charEdgeStyleOverride&&(a.charEdgeStyleOverride=b.charEdgeStyleOverride);null!=b.color&&(a.color=b.color);null!=b.colorOverride&&(a.colorOverride=b.colorOverride);null!=b.fontFamily&&(a.fontFamily=b.fontFamily);null!=b.fontFamilyOverride&&(a.fontFamilyOverride=b.fontFamilyOverride);null!=b.fontSizeIncrement&&
(a.fontSizeIncrement=b.fontSizeIncrement);null!=b.fontSizeIncrementOverride&&(a.fontSizeIncrementOverride=b.fontSizeIncrementOverride);null!=b.fontStyle&&(a.fontStyle=b.fontStyle);null!=b.fontStyleOverride&&(a.fontStyleOverride=b.fontStyleOverride);null!=b.textOpacity&&(a.textOpacity=b.textOpacity);null!=b.textOpacityOverride&&(a.textOpacityOverride=b.textOpacityOverride);null!=b.windowColor&&(a.windowColor=b.windowColor);null!=b.windowColorOverride&&(a.windowColorOverride=b.windowColorOverride);
null!=b.windowOpacity&&(a.windowOpacity=b.windowOpacity);null!=b.windowOpacityOverride&&(a.windowOpacityOverride=b.windowOpacityOverride);return a};
g.h.JD=function(a,b){var c={};g.Sa(c,r4(this,"display-settings"));g.Sa(c,a);q4(this,c,b);this.player.sa("captionssettingschanged")};
g.h.Xv=function(){!this.C&&this.loaded&&(g.Cb(this.M,function(a,b){a.dispose();delete this.M[b]},this),this.BD())};
g.h.fd=function(a,b){switch(a){case "fontSize":if(isNaN(b))break;var c=g.Ud(b,-2,4);this.JD({fontSizeIncrement:c});return c;case "reload":b&&!this.C&&z4(this,this.o,!0);break;case "stickyLoading":void 0!==b&&this.A.A&&y4(this,"module-enabled",!!b);break;case "track":if(!this.u)return{};if(b){if(this.C)break;if(!g.Oa(b))break;if(g.Pb(b)){z4(this,null,!0);break}for(var d=this.u.bj(!0),e=0;e<d.length;e++){var f=d[e];f.languageCode!==b.languageCode||c&&f.languageName!==b.languageName||(c=b.translationLanguage?
xva(f,b.translationLanguage):f)}!c||c===this.o&&this.loaded||z4(this,c,!0)}else return this.loaded&&this.o&&!x4(this)?z3(this.o):{};return"";case "tracklist":return this.u?(0,g.Jc)(this.u.bj(!(!b||!b.includeAsr)),function(k){return z3(k)}):[];
case "translationLanguages":return this.u?this.u.B.map(function(k){return Object.assign({},k)}):[];
case "sampleSubtitles":this.C||void 0===b||twa(this,!!b)}};
g.h.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.A.A&&a.push("stickyLoading");return a};
g.h.qH=function(){var a=this.o;return a?{cc:a.vssId}:{}};
g.h.bP=function(){this.loaded&&this.o&&!x4(this)?(y4(this,"module-enabled",!1),this.unload(),u4(this,!0)&&z4(this,v4(this),!1)):z4(this,x4(this)||!this.o?w4(this,!0):this.o,!0)};
g.h.FK=function(){var a=x4(this);u4(this,a)?z4(this,this.player.getAudioTrack().yo,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),(this.ra?this.C||this.L:u4(this)||t4(this))&&(a?z4(this,w4(this),!1):this.load()))};g.nM.captions=s4;})(_yt_player);
