(function(g){var window=this;var Pwa=function(a,b){a.sa("onAutonavCoundownStarted",b)},R4=function(a,b,c){var d=b.Da();
g.K(a.element,"ytp-suggestion-set",!!d.videoId);var e=b.getPlaylistId();c=b.Ec(c?c:"mqdefault.jpg");var f=b instanceof g.fB&&b.lengthSeconds?g.LM(b.lengthSeconds):null,k=!!e;e=k&&"RD"===(new g.rC(e.substr(0,2),e.substr(2))).type;var l=b instanceof g.fB?b.ya:null;d={title:b.title,author:b.author,author_and_views:d.shortViewCount?b.author+" \u2022 "+d.shortViewCount:b.author,aria_label:b.Ol||g.KM("Assistir a $TITLE",{TITLE:b.title}),duration:f,url:b.Nh(),is_live:l,is_list:k,is_mix:e,background:c?"background-image: url("+
c+")":""};b instanceof g.sC&&(d.playlist_length=b.getLength());a.update(d)},S4=function(a,b){g.W.call(this,{D:"div",
X:["html5-endscreen","ytp-player-content",b||"base-endscreen"]});this.created=!1;this.player=a},U4=function(a){g.W.call(this,{D:"div",
X:["ytp-upnext","ytp-player-content"],P:{"aria-label":"{{aria_label}}"},K:[{D:"div",I:"ytp-cued-thumbnail-overlay-image",P:{style:"{{background}}"}},{D:"span",I:"ytp-upnext-top",K:[{D:"span",I:"ytp-upnext-header",W:"Pr\u00f3ximo"},{D:"span",I:"ytp-upnext-title",W:"{{title}}"},{D:"span",I:"ytp-upnext-author",W:"{{author}}"}]},{D:"a",I:"ytp-upnext-autoplay-icon",P:{role:"button",href:"{{url}}","aria-label":"Reproduzir pr\u00f3ximo v\u00eddeo"},K:[{D:"svg",P:{height:"100%",version:"1.1",viewBox:"0 0 72 72",
width:"100%"},K:[{D:"circle",I:"ytp-svg-autoplay-circle",P:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{D:"circle",I:"ytp-svg-autoplay-ring",P:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{D:"path",I:"ytp-svg-fill",P:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{D:"span",I:"ytp-upnext-bottom",K:[{D:"span",I:"ytp-upnext-cancel"},{D:"span",I:"ytp-upnext-paused",
W:"Reprodu\u00e7\u00e3o autom\u00e1tica pausada"}]}]});this.api=a;this.cancelButton=null;this.C=this.da("ytp-svg-autoplay-ring");this.u=this.notification=this.o=this.suggestion=null;this.A=new g.I(this.lo,5E3,this);this.B=0;var b=this.da("ytp-upnext-cancel");this.cancelButton=new g.W({D:"button",X:["ytp-upnext-cancel-button","ytp-button"],P:{tabindex:"0","aria-label":"Cancelar reprodu\u00e7\u00e3o autom\u00e1tica"},W:"Cancelar"});g.A(this,this.cancelButton);this.cancelButton.na("click",this.JI,this);
this.cancelButton.ca(b);g.A(this,this.A);g.PL(this.api,this.element,this,18788);b=this.da("ytp-upnext-autoplay-icon");this.N(b,"click",this.sM);this.fB();this.N(a,"autonavvisibility",this.fB);this.N(a,"mdxnowautoplaying",this.NL);this.N(a,"mdxautoplaycanceled",this.OL);this.N(a,"mdxautoplayupnext",this.ID);T4(this)&&(a=(a=g.vL(g.oL(this.api)))?a.WF():null)&&this.ID(a);g.K(this.element,"ytp-upnext-mobile",this.api.O().o)},W4=function(a,b){a.o||(g.Uo("a11y-announce","Pr\u00f3ximo "+a.suggestion.title),
a.B=(0,g.N)(),a.o=new g.I(function(){V4(a,b)},25),V4(a,b),Pwa(a.api,b||g.Q(a.api.O().experiments,"autoplay_time")||1E4));
g.Hn(a.element,"ytp-upnext-autoplay-paused")},T4=function(a){return 3===a.api.getPresentingPlayerType()},V4=function(a,b){var c=b||g.Q(a.api.O().experiments,"autoplay_time")||1E4,d=Math.min(Qwa(a),c);
c=Math.min(d/c,1);a.C.setAttribute("stroke-dashoffset",""+-211*(c+1));1<=c&&!T4(a)?a.select(!0):a.o&&a.o.start()},Qwa=function(a){return(0,g.N)()-a.B},Y4=function(a){X4(a);
a.B=(0,g.N)();V4(a);g.J(a.element,"ytp-upnext-autoplay-paused")},X4=function(a){a.o&&(a.o.dispose(),a.o=null)},Rwa=function(a){S4.call(this,a,"subscribecard-endscreen");
var b=a.getVideoData();this.o=new g.W({D:"div",I:"ytp-subscribe-card",K:[{D:"img",I:"ytp-author-image",P:{src:b.je}},{D:"div",I:"ytp-subscribe-card-right",K:[{D:"div",I:"ytp-author-name",W:b.author},{D:"div",I:"html5-subscribe-button-container"}]}]});g.A(this,this.o);this.o.ca(this.element);this.subscribeButton=new g.vR("Inscreva-se",null,"Cancelar assinatura",null,!0,!1,b.qh,b.subscribed,"trailer-endscreen",null,null,a);g.A(this,this.subscribeButton);this.subscribeButton.ca(this.o.da("html5-subscribe-button-container"));
this.hide()},Z4=function(a){var b=a.O(),c=g.Nt||g.Bh?{style:"will-change: opacity"}:void 0,d=b.u,e=["ytp-videowall-still"];
b.o&&e.push("ytp-videowall-show-text");g.W.call(this,{D:"a",X:e,P:{href:"{{url}}",target:d?b.F:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},K:[{D:"div",I:"ytp-videowall-still-image",P:{style:"{{background}}"}},{D:"span",I:"ytp-videowall-still-info",K:[{D:"span",I:"ytp-videowall-still-info-bg",K:[{D:"span",I:"ytp-videowall-still-info-content",P:c,K:[{D:"span",I:"ytp-videowall-still-info-title",W:"{{title}}"},{D:"span",I:"ytp-videowall-still-info-author",
W:"{{author_and_views}}"},{D:"span",I:"ytp-videowall-still-info-live",W:"Ao vivo"},{D:"span",I:"ytp-videowall-still-info-duration",W:"{{duration}}"}]}]}]},{D:"span",X:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],K:[{D:"span",I:"ytp-videowall-still-listlabel-icon"},"Playlist",{D:"span",I:"ytp-videowall-still-listlabel-length",K:[" (",{D:"span",W:"{{playlist_length}}"},")"]}]},{D:"span",X:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],K:[{D:"span",
I:"ytp-videowall-still-listlabel-mix-icon"},"Mix",{D:"span",I:"ytp-videowall-still-listlabel-length",W:" (50+)"}]}]});this.suggestion=null;this.o=d;this.api=a;this.u=new g.Ur(this);g.A(this,this.u);this.na("click",this.onClick);this.na("keypress",this.A);this.u.N(a,"videodatachange",this.ab);g.QL(a,this.element,this);this.ab()},$4=function(a){S4.call(this,a,"videowall-endscreen");
var b=this;this.J=a;this.A=0;this.stills=[];this.B=this.videoData=this.suggestions=null;this.C=this.H=!1;this.G=null;this.u=new g.aR(this);g.A(this,this.u);this.F=new g.I(function(){g.J(b.element,"ytp-show-tiles")},0);
g.A(this,this.F);var c=new g.W({D:"button",X:["ytp-button","ytp-endscreen-previous"],P:{"aria-label":"Anterior"},K:[g.kN()]});g.A(this,c);c.ca(this.element);c.na("click",this.eI,this);this.table=new g.RM({D:"div",I:"ytp-endscreen-content"});g.A(this,this.table);this.table.ca(this.element);c=new g.W({D:"button",X:["ytp-button","ytp-endscreen-next"],P:{"aria-label":"Pr\u00f3ximo"},K:[g.lN()]});g.A(this,c);c.ca(this.element);c.na("click",this.dI,this);this.o=new U4(a);g.A(this,this.o);g.NL(this.player,
this.o.element,4);this.hide()},a5=function(a){return g.OL(a.player)&&a.hx()&&!a.B},Swa=function(a,b){return(0,g.Jc)(b.suggestions,function(c){c=g.NM(a.J.O(),c);
g.A(a,c);return c})},b5=function(a){var b=a.fu();
b!==a.H&&(a.H=b,a.player.S("autonavvisibility"))},c5=function(a){g.ZL.call(this,a);
this.endScreen=null;this.listeners=new g.Ur(this);g.A(this,this.listeners);this.o=a.O();Twa(a)?this.endScreen=new $4(this.player):this.o.fb?this.endScreen=new Rwa(this.player):this.endScreen=new S4(this.player);g.A(this,this.endScreen);g.NL(this.player,this.endScreen.element,4);this.OC();this.listeners.N(a,"videodatachange",this.OC,this);this.listeners.N(a,g.qC("endscreen"),this.ld,this);this.listeners.N(a,"crx_endscreen",this.Ve,this)},Twa=function(a){a=a.O();
return a.Ea&&!a.fb};
g.r(S4,g.W);g.h=S4.prototype;g.h.create=function(){this.created=!0};
g.h.destroy=function(){this.created=!1};
g.h.hx=function(){return!1};
g.h.fu=function(){return!1};
g.h.pz=function(){return!1};g.r(U4,g.W);g.h=U4.prototype;g.h.lo=function(){this.notification&&(this.A.stop(),this.kb(this.u),this.u=null,this.notification.close(),this.notification=null)};
g.h.fB=function(){g.UM(this,g.pL(this.api));g.TL(this.api,this.element,g.pL(this.api))};
g.h.jM=function(){window.focus();this.lo()};
g.h.hide=function(){g.W.prototype.hide.call(this)};
g.h.select=function(a){a=void 0===a?!1:a;if(g.P(this.api.O().experiments,"autonav_notifications")&&a&&window.Notification&&document.hasFocus){var b=Notification.permission;"default"===b?Notification.requestPermission():"granted"!==b||document.hasFocus()||(b=this.suggestion.Da(),this.lo(),this.notification=new Notification("Pr\u00f3ximo",{body:b.title,icon:b.Ec()}),this.u=this.N(this.notification,"click",this.jM),this.A.start())}X4(this);this.api.nextVideo(!1,a)};
g.h.sM=function(a){!g.De(this.cancelButton.element,g.jp(a))&&g.jO(a,this.api)&&this.select()};
g.h.JI=function(){g.rL(this.api,!0)};
g.h.NL=function(a){T4(this);this.show();W4(this,a)};
g.h.ID=function(a){T4(this);this.suggestion&&this.suggestion.Da().videoId===a.Da().videoId||(this.suggestion=a,R4(this,a,"hqdefault.jpg"))};
g.h.OL=function(){T4(this);X4(this);this.hide()};
g.h.Y=function(){X4(this);this.lo();g.W.prototype.Y.call(this)};g.r(Rwa,S4);g.r(Z4,g.W);Z4.prototype.select=function(){var a=this.suggestion.Da().videoId,b=this.suggestion.getPlaylistId();(g.UT(this.api.app,a,this.suggestion.Zb,b,void 0,void 0)||this.api.ia("web_player_endscreen_double_log_fix_killswitch"))&&g.SL(this.api,this.element)};
Z4.prototype.onClick=function(a){g.jO(a,this.api,this.o,this.suggestion.Zb||void 0)&&this.select()};
Z4.prototype.A=function(a){switch(a.keyCode){case 13:case 32:g.op(a)||(this.select(),g.np(a))}};
Z4.prototype.ab=function(){var a=this.api.getVideoData(),b=this.api.O();this.o=a.Wb?!1:b.u};g.r($4,S4);g.h=$4.prototype;g.h.create=function(){S4.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.suggestions=Swa(this,a),this.videoData=a);this.lh();this.u.N(this.player,"appresize",this.lh);this.u.N(this.player,"onVideoAreaChange",this.lh);this.u.N(this.player,"videodatachange",this.ab);this.u.N(this.player,"autonavchange",this.gu);this.u.N(this.player,"autonavcancel",this.cI);a=this.videoData.autonavState;a!==this.G&&this.gu(a);this.u.N(this.element,"transitionend",this.BN)};
g.h.destroy=function(){g.Wr(this.u);g.Oe(this.stills);this.stills=[];this.suggestions=null;S4.prototype.destroy.call(this);g.Hn(this.element,"ytp-show-tiles");this.F.stop();this.G=this.videoData.autonavState};
g.h.hx=function(){return 1!==this.videoData.autonavState};
g.h.show=function(){S4.prototype.show.call(this);g.Hn(this.element,"ytp-show-tiles");this.player.O().o?g.yn(this.F):this.F.start();(this.C||this.B&&this.B!==this.videoData.clientPlaybackNonce)&&g.rL(this.player,!1);a5(this)?(b5(this),2===this.videoData.autonavState?this.player.O().ia("fast_autonav_in_background")&&3===this.player.getVisibilityState()?this.o.select(!0):W4(this.o):3===this.videoData.autonavState&&Y4(this.o)):(g.rL(this.player,!0),b5(this))};
g.h.hide=function(){S4.prototype.hide.call(this);Y4(this.o);b5(this)};
g.h.BN=function(a){g.jp(a)===this.element&&this.lh()};
g.h.lh=function(){if(this.suggestions&&this.suggestions.length){g.J(this.element,"ytp-endscreen-paginate");var a=g.EL(this.J,!0,this.J.isFullscreen()),b=g.jC(this.J);b&&(b=b.Lc()?48:32,a.width-=2*b);var c=a.width/a.height,d=96/54,e=b=2,f=Math.max(a.width/96,2),k=Math.max(a.height/54,2),l=this.suggestions.length,m=Math.pow(2,2);var n=l*m+(Math.pow(2,2)-m);n+=Math.pow(2,2)-m;for(n-=m;0<n&&(b<f||e<k);){var q=b/2,t=e/2,u=b<=f-2&&n>=t*m,w=e<=k-2&&n>=q*m;if((q+1)/t*d/c>c/(q/(t+1)*d)&&w)n-=q*m,e+=2;else if(u)n-=
t*m,b+=2;else if(w)n-=q*m,e+=2;else break}d=!1;n>=3*m&&6>=l*m-n&&(4<=e||4<=b)&&(d=!0);m=96*b;n=54*e;c=m/n<c?a.height/n:a.width/m;c=Math.min(c,2);m*=c;n*=c;c=this.player.O().ia("web_player_no_endscreen_crop")?1:1.21;m*=g.Ud(a.width/m||1,1,c);n*=g.Ud(a.height/n||1,1,c);m=Math.floor(Math.min(a.width,m));n=Math.floor(Math.min(a.height,n));a=this.table.element;g.Qh(a,m,n);g.H(a,{marginLeft:m/-2+"px",marginTop:n/-2+"px"});c=this.o;f=this.suggestions[0];c.suggestion=f;R4(c,f,"hqdefault.jpg");g.K(this.element,
"ytp-endscreen-takeover",a5(this));b5(this);m+=4;n+=4;for(f=c=0;f<b;f++)for(k=0;k<e;k++)if(q=c,t=0,d&&f>=b-2&&k>=e-2?t=1:0===k%2&&0===f%2&&(2>k&&2>f?0===k&&0===f&&(t=2):t=2),q=g.Vd(q+this.A,l),0!==t){u=this.stills[c];u||(u=new Z4(this.player),this.stills[c]=u,a.appendChild(u.element));w=Math.floor(n*k/e);var B=Math.floor(m*f/b),D=Math.floor(n*(k+t)/e)-w-4,E=Math.floor(m*(f+t)/b)-B-4;g.Gh(u.element,B,w);g.Qh(u.element,E,D);g.H(u.element,"transitionDelay",(k+f)/20+"s");g.K(u.element,"ytp-videowall-still-mini",
1===t);g.K(u.element,"ytp-videowall-still-large",2<t);t=u;q=this.suggestions[q];t.suggestion!==q&&(t.suggestion=q,u=t.api.O(),w=g.Fn(t.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",R4(t,q,w),g.Py(u)&&(u=q.Nh(),u=g.Ed(u,g.DI({},"emb_rel_end")),t.oa("url",u)),(q=(q=q.Zb)&&q.itct)&&g.RL(t.api,t.element,q));c++}g.K(this.element,"ytp-endscreen-paginate",c<l);for(b=this.stills.length-1;b>=c;b--)e=this.stills[b],g.Ae(e.element),g.Ne(e);this.stills.length=c}};
g.h.ab=function(){var a=this.player.getVideoData();this.videoData!==a&&(this.A=0,this.suggestions=Swa(this,a),this.videoData=a,this.lh())};
g.h.dI=function(){this.A+=this.stills.length;this.lh()};
g.h.eI=function(){this.A-=this.stills.length;this.lh()};
g.h.pz=function(){return!!this.o.o};
g.h.gu=function(a){1===a?(this.C=!1,this.B=this.videoData.clientPlaybackNonce,X4(this.o),this.Ka()&&this.lh()):(this.C=!0,this.Ka()&&a5(this)&&(2===a?W4(this.o):3===a&&Y4(this.o)))};
g.h.cI=function(a){if(a){for(a=0;a<this.stills.length;a++)g.TL(this.J,this.stills[a].element,!0);this.gu(1)}else this.B=null,this.C=!1;this.lh()};
g.h.fu=function(){return this.Ka()&&a5(this)};g.r(c5,g.ZL);g.h=c5.prototype;g.h.Pz=function(){var a=this.player.getVideoData(),b=!!(a&&a.suggestions&&a.suggestions.length);b=!Twa(this.player)||b;var c=a.Rj||g.Yy(a.Va),d=g.nT(this.player.app);a=a.mutedAutoplay;return b&&!c&&!d&&!a};
g.h.Oz=function(){return this.endScreen.fu()};
g.h.QG=function(){return this.Oz()?this.endScreen.pz():!1};
g.h.Y=function(){g.RR(this.player.app,"endscreen",void 0);g.ZL.prototype.Y.call(this)};
g.h.load=function(){g.ZL.prototype.load.call(this);this.endScreen.show()};
g.h.unload=function(){g.ZL.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.h.ld=function(a){this.Pz()&&(this.endScreen.created||this.endScreen.create(),"load"===a.getId()&&this.load())};
g.h.Ve=function(a){"load"===a.getId()&&this.loaded&&this.unload()};
g.h.OC=function(){g.RR(this.player.app,"endscreen",void 0);var a=this.player.getVideoData();a=new g.nC(Math.max(1E3*(a.lengthSeconds-10),0),0x8000000000000,{id:"preload",namespace:"endscreen"});var b=new g.nC(0x8000000000000,0x8000000000000,{id:"load",priority:6,namespace:"endscreen"});g.JL(this.player,[a,b])};g.nM.endscreen=c5;})(_yt_player);
