(function(g){var window=this;var Nxa=function(a,b){return g.Mb(a,b)},Y5=function(a,b,c){a.A.set(b,c)},Z5=function(a){Y5(a,"zx",Math.floor(2147483648*Math.random()).toString(36)+Math.abs(Math.floor(2147483648*Math.random())^(0,g.C)()).toString(36));
return a},$5=function(a,b,c){Array.isArray(c)||(c=[String(c)]);
g.en(a.A,b,c)},Oxa=function(a,b){var c=[];
g.nk(b,function(d){try{var e=g.eo.prototype.u.call(this,d,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}void 0===e?c.push(d):g.co(e)&&c.push(d)},a);
return c},Pxa=function(a,b){var c=Oxa(a,b);
(0,g.y)(c,function(d){g.eo.prototype.remove.call(this,d)},a)},Qxa=function(a){if(a.Wc){if(a.Wc.locationOverrideToken)return{locationOverrideToken:a.Wc.locationOverrideToken};
if(null!=a.Wc.latitudeE7&&null!=a.Wc.longitudeE7)return{latitudeE7:a.Wc.latitudeE7,longitudeE7:a.Wc.longitudeE7}}return null},Rxa=function(a,b){g.cb(a,b)||a.push(b)},a6=function(a){var b=0,c;
for(c in a)b++;return b},Sxa=function(a,b){var c=b instanceof g.zc?b:g.Ec(b,/^data:image\//i.test(b));
a.src=g.Ac(c)},b6=function(){},Txa=function(a){try{return g.v.JSON.parse(a)}catch(b){}a=String(a);
if(/^\s*$/.test(a)?0:/^[\],:{}\s\u2028\u2029]*$/.test(a.replace(/\\["\\\/bfnrtu]/g,"@").replace(/(?:"[^"\\\n\r\u2028\u2029\x00-\x08\x0a-\x1f]*"|true|false|null|-?\d+(?:\.\d*)?(?:[eE][+\-]?\d+)?)[\s\u2028\u2029]*(?=:|,|]|}|$)/g,"]").replace(/(?:^|:|,)(?:[\s\u2028\u2029]*\[)+/g,"")))try{return eval("("+a+")")}catch(b){}throw Error("Invalid JSON string: "+a);},Uxa=function(a){if(a.Yd&&"function"==typeof a.Yd)return a.Yd();
if("string"===typeof a)return a.split("");if(g.Ma(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Ib(a)},Vxa=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Ma(a)||"string"===typeof a)(0,g.y)(a,b,void 0);else{if(a.Oe&&"function"==typeof a.Oe)var c=a.Oe();else if(a.Yd&&"function"==typeof a.Yd)c=void 0;else if(g.Ma(a)||"string"===typeof a){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.Jb(a);d=Uxa(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},Wxa=function(a,b,c,d){var e=new g.Tm(null,void 0);
a&&g.Um(e,a);b&&g.Vm(e,b);c&&g.Wm(e,c);d&&(e.u=d);return e},c6=function(a,b){g.Qo[a]=!0;
var c=g.Oo();c&&c.publish.apply(c,arguments);g.Qo[a]=!1},d6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.capabilities=new Set;this.experiments=new Set;this.theme="u";new g.Qm;a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",Xxa(this,a.capabilities||""),Yxa(this,a.experiments||""))},Xxa=function(a,b){a.capabilities.clear();
(0,g.Be)(b.split(","),g.Ra(Nxa,Zxa)).forEach(function(c){a.capabilities.add(c)})},Yxa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(c){a.experiments.add(c)})},e6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},f6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},$xa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},aya=function(a){return new e6(a)},bya=function(a){return Array.isArray(a)?(0,g.Jc)(a,aya):[]},g6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},h6=function(a){return Array.isArray(a)?"["+(0,g.Jc)(a,g6).join(",")+"]":"null"},i6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|
0;
return("x"==a?b:b&3|8).toString(16)})},cya=function(a){return(0,g.Jc)(a,function(b){return{key:b.id,
name:b.name}})},j6=function(a,b){return g.$a(a,function(c){return c||b?!c!=!b?!1:c.id==b.id:!0})},k6=function(a,b){return g.$a(a,function(c){return f6(c,b)})},dya=function(){var a=(0,g.Os)();
a&&Pxa(a,a.o.Gg(!0))},l6=function(){var a=g.Rs("yt-remote-connected-devices")||[];
g.vb(a);return a},eya=function(a){if(g.db(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.Jc)(a,function(d,e){return 0==e?d:d.substring(c.length)})},fya=function(a){g.Qs("yt-remote-connected-devices",a,86400)},n6=function(){if(m6)return m6;
var a=g.Rs("yt-remote-device-id");a||(a=i6(),g.Qs("yt-remote-device-id",a,31536E3));for(var b=l6(),c=1,d=a;g.cb(b,d);)c++,d=a+"#"+c;return m6=d},o6=function(){var a=l6(),b=n6();
g.cb(a,b);g.Ts()&&g.xb(a,b);a=eya(a);if(g.db(a))try{g.Fq("remote_sid")}catch(c){}else try{g.Dq("remote_sid",a.join(","),-1)}catch(c){}},gya=function(){return g.Rs("yt-remote-session-browser-channel")},hya=function(){return g.Rs("yt-remote-local-screens")||[]},iya=function(){g.Qs("yt-remote-lounge-token-expiration",!0,86400)},jya=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.Jc)(hya(),function(d){return d.loungeToken}),c=(0,g.Jc)(a,function(d){return d.loungeToken});
(0,g.zi)(c,function(d){return!g.cb(b,d)})&&iya();
g.Qs("yt-remote-local-screens",a,31536E3)},kya=function(a,b){g.Qs("yt-remote-session-browser-channel",a);
g.Qs("yt-remote-session-screen-id",b);var c=l6(),d=n6();g.cb(c,d)||c.push(d);fya(c);o6()},p6=function(a){a||(g.Ss("yt-remote-session-screen-id"),g.Ss("yt-remote-session-video-id"));
o6();a=l6();g.gb(a,n6());fya(a)},lya=function(){if(!q6){var a=g.oo();
a&&(q6=new g.Yn(a))}return q6?!!q6.get("yt-remote-use-staging-server"):!1},mya=function(a){return!!document.currentScript&&(-1!=document.currentScript.src.indexOf("?"+a)||-1!=document.currentScript.src.indexOf("&"+a))},nya=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},r6=function(a){a.length?oya(a.shift(),function(){r6(a)}):s6()},pya=function(a){return"chrome-extension://"+a+"/cast_sender.js"},oya=function(a,b,c){var d=document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(document.head||document.documentElement).appendChild(d)},s6=function(){var a=nya();
a&&a(!1,"No cast extension found")},rya=function(){if(qya){var a=2,b=nya(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;oya("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",s6,c)}},sya=function(){rya();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);r6(["//www.gstatic.com/eureka/clank/"+(a?parseInt(a[1],10):0)+"/cast_sender.js","//www.gstatic.com/eureka/clank/cast_sender.js"])},t6=function(a,b,c){g.z.call(this);
this.F=null!=c?(0,g.x)(a,c):a;this.Rd=b;this.C=(0,g.x)(this.bG,this);this.o=!1;this.u=0;this.A=this.Ja=null;this.B=[]},u6=function(a,b,c){g.z.call(this);
this.B=null!=c?a.bind(c):a;this.Rd=b;this.A=null;this.o=!1;this.u=0;this.Ja=null},v6=function(a){a.Ja=g.$f(function(){a.Ja=null;
a.o&&!a.u&&(a.o=!1,v6(a))},a.Rd);
var b=a.A;a.A=null;a.B.apply(null,b)},w6=function(a){if(g.v.JSON)try{return g.v.JSON.parse(a)}catch(b){}return Txa(a)},x6=function(){},y6=function(){},tya=function(){},vya=function(a){return(a=uya(a))?new ActiveXObject(a):new XMLHttpRequest},uya=function(a){if(!a.u&&"undefined"==typeof XMLHttpRequest&&"undefined"!=typeof ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new ActiveXObject(d),a.u=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.u},z6=function(a,b,c,d){this.o=a;
this.A=b;this.H=c;this.G=d||1;this.C=45E3;this.B=new g.z1(this);this.u=new g.Zf;this.u.setInterval(250)},xya=function(a,b,c){a.vl=1;
a.yh=Z5(b.clone());a.Dj=c;a.F=!0;wya(a,null)},A6=function(a,b,c,d,e){a.vl=1;
a.yh=Z5(b.clone());a.Dj=null;a.F=c;e&&(a.TC=!1);wya(a,d)},wya=function(a,b){a.pl=(0,g.C)();
B6(a);a.vi=a.yh.clone();$5(a.vi,"t",a.G);a.Bn=0;a.bd=a.o.ts(a.o.on()?b:null);0<a.kt&&(a.wq=new u6((0,g.x)(a.TD,a,a.bd),a.kt));a.B.na(a.bd,"readystatechange",a.oO);var c=a.dj?g.Sb(a.dj):{};a.Dj?(a.dr="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.bd.send(a.vi,a.dr,a.Dj,c)):(a.dr="GET",a.TC&&!g.qe&&(c.Connection="close"),a.bd.send(a.vi,a.dr,null,c));a.o.Gf(1)},Aya=function(a,b,c){for(var d=!0;!a.Ni&&a.Bn<c.length;){var e=yya(a,c);
if(e==C6){4==b&&(a.Oh=4,D6(15),d=!1);break}else if(e==zya){a.Oh=4;D6(16);d=!1;break}else E6(a,e)}4==b&&0==c.length&&(a.Oh=1,D6(17),d=!1);a.Mf=a.Mf&&d;d||(F6(a),G6(a))},yya=function(a,b){var c=a.Bn,d=b.indexOf("\n",c);
if(-1==d)return C6;c=Number(b.substring(c,d));if(isNaN(c))return zya;d+=1;if(d+c>b.length)return C6;var e=b.substr(d,c);a.Bn=d+c;return e},Cya=function(a,b){a.pl=(0,g.C)();
B6(a);var c=b?window.location.hostname:"";a.vi=a.yh.clone();Y5(a.vi,"DOMAIN",c);Y5(a.vi,"t",a.G);try{a.Qf=new ActiveXObject("htmlfile")}catch(n){F6(a);a.Oh=7;D6(22);G6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in H6)k=H6[l];else if(l in Bya)k=H6[l]=Bya[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
H6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}c=g.bd(g.dc("b/12014412"),d+"</body></html>");a.Qf.open();a.Qf.write(g.Xc(c));a.Qf.close();a.Qf.parentWindow.m=(0,g.x)(a.EN,a);a.Qf.parentWindow.d=(0,g.x)(a.aC,a,!0);a.Qf.parentWindow.rpcClose=(0,g.x)(a.aC,a,!1);c=a.Qf.createElement("DIV");a.Qf.parentWindow.document.body.appendChild(c);d=g.Dc(a.vi.toString());d=g.jd(g.Ac(d));d=g.bd(g.dc("b/12014412"),'<iframe src="'+d+'"></iframe>');g.cd(c,d);a.o.Gf(1)},B6=function(a){a.hw=(0,g.C)()+a.C;
Dya(a,a.C)},Dya=function(a,b){if(null!=a.Cl)throw Error("WatchDog timer not null");
a.Cl=I6((0,g.x)(a.MN,a),b)},J6=function(a){a.Cl&&(g.v.clearTimeout(a.Cl),a.Cl=null)},G6=function(a){a.o.Ly()||a.Ni||a.o.Oo(a)},F6=function(a){J6(a);
g.Ne(a.wq);a.wq=null;a.u.stop();g.ysa(a.B);if(a.bd){var b=a.bd;a.bd=null;b.abort();b.dispose()}a.Qf&&(a.Qf=null)},E6=function(a,b){try{a.o.SB(a,b),a.o.Gf(4)}catch(c){}},Fya=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;Eya(a,b,function(k){k?c(!0):g.v.setTimeout(function(){Fya(a,b,c,d,f)},f)})}},Eya=function(a,b,c){var d=new Image;
d.onload=function(){try{K6(d),c(!0)}catch(e){}};
d.onerror=function(){try{K6(d),c(!1)}catch(e){}};
d.onabort=function(){try{K6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{K6(d),c(!1)}catch(e){}};
g.v.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
Sxa(d,a)},K6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},Gya=function(a){this.o=a;
this.u=new x6},Hya=function(a){var b=L6(a.o,a.Ql,"/mail/images/cleardot.gif");
Z5(b);Fya(b.toString(),5E3,(0,g.x)(a.aF,a),3,2E3);a.Gf(1)},N6=function(a){var b=a.o.M;
if(null!=b)D6(5),b?(D6(11),M6(a.o,a,!1)):(D6(12),M6(a.o,a,!0));else if(a.ke=new z6(a,void 0,void 0,void 0),a.ke.dj=a.it,b=a.o,b=L6(b,b.on()?a.nm:null,a.jt),D6(5),!g.oe||g.Td(10))$5(b,"TYPE","xmlhttp"),A6(a.ke,b,!1,a.nm,!1);else{$5(b,"TYPE","html");var c=a.ke;a=!!a.nm;c.vl=3;c.yh=Z5(b.clone());Cya(c,a)}},O6=function(a){g.nf.call(this);
this.headers=new g.Qm;this.U=a||null;this.A=!1;this.T=this.o=null;this.ea=this.M="";this.F=0;this.B="";this.C=this.ba=this.H=this.Z=!1;this.G=0;this.L=null;this.fa="";this.R=this.aa=!1},Iya=function(a){return g.oe&&g.Sd(9)&&"number"===typeof a.timeout&&void 0!==a.ontimeout},Jya=function(a){return"content-type"==a.toLowerCase()},Lya=function(a,b){a.A=!1;
a.o&&(a.C=!0,a.o.abort(),a.C=!1);a.B=b;a.F=5;Kya(a);P6(a)},Kya=function(a){a.Z||(a.Z=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},Nya=function(a){if(a.A&&"undefined"!=typeof g.E1)if(a.T[1]&&4==Q6(a)&&2==a.getStatus())R6(a,"Local request error detected and ignored");
else if(a.H&&4==Q6(a))g.$f(a.OB,0,a);else if(a.dispatchEvent("readystatechange"),4==Q6(a)){R6(a,"Request complete");a.A=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.td(1,String(a.M));if(!f&&g.v.self&&g.v.self.location){var k=g.v.self.location.protocol;f=k.substr(0,k.length-1)}e=!Mya.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.F=6;try{var l=2<Q6(a)?a.o.statusText:""}catch(m){l=""}a.B=l+" ["+a.getStatus()+"]";Kya(a)}}finally{P6(a)}}},P6=function(a,b){if(a.o){Oya(a);
var c=a.o,d=a.T[0]?g.Ja:null;a.o=null;a.T=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},Oya=function(a){a.o&&a.R&&(a.o.ontimeout=null);
a.L&&(g.v.clearTimeout(a.L),a.L=null)},Q6=function(a){return a.o?a.o.readyState:0},S6=function(a){try{return a.o?a.o.responseText:""}catch(b){return""}},R6=function(a,b){return b+" ["+a.ea+" "+a.M+" "+a.getStatus()+"]"},T6=function(a,b,c){this.o=1;
this.u=[];this.B=[];this.C=new x6;this.H=a||null;this.M=null!=b?b:null;this.F=c||!1},Pya=function(a,b){this.o=a;
this.map=b;this.context=null},Qya=function(a){g.Pe.call(this,"statevent",a)},Rya=function(a,b){g.Pe.call(this,"timingevent",a);
this.size=b},Sya=function(a){g.Pe.call(this,"serverreachability",a)},Vya=function(a){Tya(a);
if(3==a.o){var b=a.Sm++,c=a.Ao.clone();Y5(c,"SID",a.A);Y5(c,"RID",b);Y5(c,"TYPE","terminate");U6(a,c);b=new z6(a,a.A,b,void 0);b.vl=2;b.yh=Z5(c.clone());Sxa(new Image,b.yh.toString());b.pl=(0,g.C)();B6(b)}Uya(a)},Wya=function(a){a.xF(1,0);
a.Ao=L6(a,null,a.ht);V6(a)},Tya=function(a){a.Bh&&(a.Bh.abort(),a.Bh=null);
a.yc&&(a.yc.cancel(),a.yc=null);a.Hg&&(g.v.clearTimeout(a.Hg),a.Hg=null);W6(a);a.ce&&(a.ce.cancel(),a.ce=null);a.Gh&&(g.v.clearTimeout(a.Gh),a.Gh=null)},Xya=function(a,b){if(0==a.o)throw Error("Invalid operation: sending map when state is closed");
a.u.push(new Pya(a.gK++,b));2!=a.o&&3!=a.o||V6(a)},V6=function(a){a.ce||a.Gh||(a.Gh=I6((0,g.x)(a.ZB,a),0),a.jk=0)},Zya=function(a,b){if(1==a.o){if(!b){a.Sm=Math.floor(1E5*Math.random());
var c=a.Sm++,d=new z6(a,"",c,void 0);d.dj=null;var e=X6(a),f=a.Ao.clone();Y5(f,"RID",c);Y5(f,"CVER","1");U6(a,f);xya(d,f,e);a.ce=d;a.o=2}}else 3==a.o&&(b?Yya(a,b):0==a.u.length||a.ce||Yya(a))},Yya=function(a,b){if(b)if(6<a.Oi){a.u=a.B.concat(a.u);
a.B.length=0;var c=a.Sm-1;var d=X6(a)}else c=b.H,d=b.Dj;else c=a.Sm++,d=X6(a);var e=a.Ao.clone();Y5(e,"SID",a.A);Y5(e,"RID",c);Y5(e,"AID",a.Dk);U6(a,e);c=new z6(a,a.A,c,a.jk+1);c.dj=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.ce=c;xya(c,e,d)},U6=function(a,b){if(a.Nd){var c=a.Nd.iy();
c&&g.Cb(c,function(d,e){Y5(b,e,d)})}},X6=function(a){var b=Math.min(a.u.length,1E3),c=["count="+b];
if(6<a.Oi&&0<b){var d=a.u[0].o;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.u[e].o,k=a.u[e].map;f=6>=a.Oi?e:f-d;try{g.Cb(k,function(l,m){c.push("req"+f+"_"+m+"="+encodeURIComponent(l))})}catch(l){c.push("req"+f+"_type="+encodeURIComponent("_badmap"))}}a.B=a.B.concat(a.u.splice(0,b));
return c.join("&")},$ya=function(a){a.yc||a.Hg||(a.G=1,a.Hg=I6((0,g.x)(a.YB,a),0),a.Wj=0)},Y6=function(a){if(a.yc||a.Hg||3<=a.Wj)return!1;
a.G++;a.Hg=I6((0,g.x)(a.YB,a),aza(a,a.Wj));a.Wj++;return!0},M6=function(a,b,c){a.Zq=c;
a.dg=b.Wg;a.F||Wya(a)},W6=function(a){null!=a.Ti&&(g.v.clearTimeout(a.Ti),a.Ti=null)},aza=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},Z6=function(a,b){if(2==b||9==b){var c=null;
a.Nd&&(c=null);var d=(0,g.x)(a.ZO,a);c||(c=new g.Tm("//www.google.com/images/cleardot.gif"),Z5(c));Eya(c.toString(),1E4,d)}else D6(2);bza(a,b)},bza=function(a,b){a.o=0;
a.Nd&&a.Nd.wx(b);Uya(a);Tya(a)},Uya=function(a){a.o=0;
a.dg=-1;if(a.Nd)if(0==a.B.length&&0==a.u.length)a.Nd.Yr();else{g.lb(a.B);var b=g.lb(a.u);a.B.length=0;a.u.length=0;a.Nd.Yr(b)}},L6=function(a,b,c){var d=g.an(c);
if(""!=d.o)b&&g.Vm(d,b+"."+d.o),g.Wm(d,d.B);else{var e=window.location;d=Wxa(e.protocol,b?b+"."+e.hostname:e.hostname,+e.port,c)}a.fm&&g.Cb(a.fm,function(f,k){Y5(d,k,f)});
Y5(d,"VER",a.Oi);U6(a,d);return d},I6=function(a,b){if(!g.Na(a))throw Error("Fn must not be null and must be a function");
return g.v.setTimeout(function(){a()},b)},D6=function(a){$6.dispatchEvent(new Qya($6,a))},cza=function(){},dza=function(){this.o=[];
this.u=[]},eza=function(a,b){this.action=a;
this.params=b||{}},a7=function(a,b){g.z.call(this);
this.o=new g.I(this.xN,0,this);g.A(this,this.o);this.Rd=5E3;this.u=0;if(g.Na(a))b&&(a=(0,g.x)(a,b));else if(a&&g.Na(a.handleEvent))a=(0,g.x)(a.handleEvent,a);else throw Error("Invalid listener argument");this.A=a},b7=function(a,b,c){this.L=a;
this.F=b;this.A=new g.Xn;this.u=new a7(this.BO,this);this.o=null;this.Lb=!1;this.C=null;this.M="";this.H=this.B=0;this.G=[];this.R=c||!1},fza=function(a){return{firstTestResults:[""],
secondTestResults:!a.o.Zq,sessionId:a.o.A,arrayId:a.o.Dk}},gza=function(a,b){a.H=b||0;
a.u.stop();a.o&&(3==a.o.o&&Zya(a.o),Vya(a.o));a.H=0},c7=function(a){return!!a.o&&3==a.o.o},hza=function(a,b){(a.F.loungeIdToken=b)||a.u.stop()},d7=function(a){this.port=this.domain="";
this.o="/api/lounge";this.u=!0;a=a||document.location.href;var b=Number(g.td(4,a))||"";b&&(this.port=":"+b);this.domain=g.ud(a)||"";a=g.Pc;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.wc(a,"10.0")&&(this.u=!1))},e7=function(a,b){var c=a.o;
a.u&&(c="https://"+a.domain+a.port+a.o);return g.Ed(c+b,{})},f7=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,onSuccess:g.Ra(a.B,d,!0),onError:g.Ra(a.A,e),Ge:g.Ra(a.C,e)};c&&(a.yb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.wq(b,a)},lza=function(){var a=iza;
jza();g7.push(a);kza(g7)},h7=function(a,b){jza();
var c=g7,d=mza(a,String(b));g.db(c)?nza(d):(kza(c),(0,g.y)(c,function(e){e(d)}))},jza=function(){g7||(g7=g.Ia("yt.mdx.remote.debug.handlers_")||[],g.Ga("yt.mdx.remote.debug.handlers_",g7,void 0))},nza=function(a){var b=(i7+1)%50;
i7=b;j7[b]=a;k7||(k7=49==b)},kza=function(a){var b=j7;
if(b[0]){var c=i7,d=k7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.y)(a,function(f){f(e)})}while(d!=c);
j7=Array(50);i7=-1;k7=!1}},mza=function(a,b){var c=((0,g.C)()-oza)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},l7=function(a){g.O.call(this);
this.F=a;this.screens=[]},pza=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.screens.push(b);return!0},qza=function(a,b){var c=a.screens.length!=b.length;
a.screens=(0,g.Be)(a.screens,function(f){return!!j6(b,f)});
for(var d=0,e=b.length;d<e;d++)c=pza(a,b[d])||c;return c},rza=function(a,b){var c=a.screens.length;
a.screens=(0,g.Be)(a.screens,function(d){return!(d||b?!d!=!b?0:d.id==b.id:1)});
return a.screens.length<c},m7=function(a,b,c,d){g.O.call(this);
this.F=a;this.B=b;this.C=c;this.A=d;this.u=0;this.o=null;this.Ja=NaN},o7=function(a){l7.call(this,"LocalScreenService");
this.u=a;this.o=NaN;n7(this);this.info("Initializing with "+h6(this.screens))},sza=function(a){if(a.screens.length){var b=(0,g.Jc)(a.screens,function(d){return d.id}),c=e7(a.u,"/pairing/get_lounge_token_batch");
f7(a.u,c,{screen_ids:b.join(",")},(0,g.x)(a.lG,a),(0,g.x)(a.kG,a))}},n7=function(a){var b=bya(hya());
b=(0,g.Be)(b,function(c){return!c.uuid});
return qza(a,b)},p7=function(a,b){jya((0,g.Jc)(a.screens,$xa));
b&&iya()},r7=function(a,b){g.O.call(this);
this.F=b;var c=g.Rs("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.F(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.cb(c,l)}this.o=d;this.C=a;this.A=this.B=NaN;this.u=null;q7("Initialized with "+g.Pk(this.o))},tza=function(a,b,c){var d=e7(a.C,"/pairing/get_screen_availability");
f7(a.C,d,{lounge_token:b.token},(0,g.x)(function(e){e=e.screens||[];for(var f=0,k=e.length;f<k;++f)if(e[f].loungeToken==b.token){c("online"==e[f].status);return}c(!1)},a),(0,g.x)(function(){c(!1)},a))},s7=function(a,b){a:if(a6(b)!=a6(a.o))var c=!1;
else{c=g.Jb(b);for(var d=0,e=c.length;d<e;++d)if(!a.o[c[d]]){c=!1;break a}c=!0}c||(q7("Updated online screens: "+g.Pk(a.o)),a.o=b,a.S("screenChange"));uza(a)},t7=function(a){isNaN(a.A)||g.No(a.A);
a.A=g.Lo((0,g.x)(a.kv,a),0<a.B&&a.B<(0,g.C)()?2E4:1E4)},q7=function(a){h7("OnlineScreenService",a)},vza=function(a){var b={};
(0,g.y)(a.F(),function(c){c.token?b[c.token]=c.id:this.pc("Requesting availability of screen w/o lounge token.")});
return b},uza=function(a){a=g.Jb(g.Db(a.o,function(b){return b}));
g.vb(a);a.length?g.Qs("yt-remote-online-screen-ids",a.join(","),60):g.Ss("yt-remote-online-screen-ids")},u7=function(a){l7.call(this,"ScreenService");
this.C=a;this.o=this.u=null;this.A=[];this.B={};wza(this)},yza=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.ye();if(k=(c?k6(k,c):null)||k6(k,b)){k.uuid=b;var l=v7(a,k);tza(a.o,l,function(m){e(m?l:null)})}else c?xza(a,c,(0,g.x)(function(m){var n=v7(this,new e6({name:d,
screenId:c,loungeToken:m,dialId:b||""}));tza(this.o,n,function(q){e(q?n:null)})},a),f):e(null)},zza=function(a,b){for(var c=0,d=a.screens.length;c<d;++c)if(a.screens[c].name==b)return a.screens[c];
return null},xza=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={yb:{screen_ids:b},method:"POST",context:a,onSuccess:function(f,k){var l=k&&k.screens||[];l[0]&&l[0].screenId==b?c(l[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.wq(e7(a.C,"/pairing/get_lounge_token_batch"),e)},Aza=function(a){a.screens=a.u.ye();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.screens.length;b<d;++b){var e=a.screens[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+h6(a.screens))},wza=function(a){w7(a);
a.u=new o7(a.C);a.u.subscribe("screenChange",(0,g.x)(a.tG,a));Aza(a);a.A=bya(g.Rs("yt-remote-automatic-screen-cache")||[]);w7(a);a.info("Initializing automatic screens: "+h6(a.A));a.o=new r7(a.C,(0,g.x)(a.ye,a,!0));a.o.subscribe("screenChange",(0,g.x)(function(){this.S("onlineScreenChange")},a))},v7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=k6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.Qs("yt-remote-automatic-screen-cache",(0,g.Jc)(a.A,$xa)));w7(a);a.B[b.uuid]=b.id;g.Qs("yt-remote-device-id-map",a.B,31536E3);return b},w7=function(a){a.B=g.Rs("yt-remote-device-id-map")||{}},x7=function(a,b,c){g.O.call(this);
this.T=c;this.M=a;this.u=b;this.H=null},y7=function(a,b){h7(a.T,b)},z7=function(a,b){x7.call(this,a,b,"CastSession");
this.o=null;this.A=0;this.C=(0,g.x)(this.FP,this);this.B=(0,g.x)(this.UN,this);this.A=g.Lo((0,g.x)(function(){Bza(this,null)},this),12E4)},Cza=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Pk(void 0));
var b={type:"getMdxSessionStatus"};a.o?a.o.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.Ja,(0,g.x)(function(){y7(this,"Failed to send message: getMdxSessionStatus.")},a)):y7(a,"Sending yt message without session: "+g.Pk(b))},Bza=function(a,b){g.No(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.getScreen()||a.getScreen().id!=b){var c=(0,g.x)(a.jq,a),d=(0,g.x)(a.Fe,a);a.Dy(b,c,d,5)}}else a.Fe(Error("Waiting for session status timed out."))},A7=function(a,b,c){x7.call(this,a,b,"DialSession");
this.A=this.G=null;this.L="";this.U=c;this.B=null;this.F=g.Ja;this.C=NaN;this.R=(0,g.x)(this.IP,this);this.o=g.Ja},Dza=function(a){a.o=a.M.ZD(a.L,a.u.label,a.u.friendlyName,(0,g.x)(function(b){this.o=g.Ja;
this.jq(b)},a),(0,g.x)(function(b){this.o=g.Ja;
this.Fe(b)},a))},Eza=function(a){var b={};
b.pairingCode=a.L;b.theme=a.U;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}lya()&&(b.env_useStageMdx=1);return g.Cd(b)},B7=function(a,b){x7.call(this,a,b,"ManualSession");
this.o=g.Lo((0,g.x)(this.Ek,this,null),150)},C7=function(a,b,c,d){g.O.call(this);
this.u=a;this.G=b||"233637DE";this.F=c||"cl";this.H=d||!1;this.o=null;this.C=!1;this.A=[];this.B=(0,g.x)(this.LM,this)},Fza=function(a,b){return b?g.$a(a.A,function(c){return f6(b,c.label)},a):null},D7=function(a){h7("Controller",a)},iza=function(a){window.chrome&&chrome.cast&&chrome.cast.logMessage&&chrome.cast.logMessage(a)},E7=function(a){return a.C||!!a.A.length||!!a.o},F7=function(a,b,c){b!=a.o&&(g.Ne(a.o),(a.o=b)?(c?a.S("yt-remote-cast2-receiver-resumed",b.u):a.S("yt-remote-cast2-receiver-selected",
b.u),b.subscribe("sessionScreen",(0,g.x)(a.XB,a,b)),b.getScreen()?a.S("yt-remote-cast2-session-change",b.getScreen()):c&&a.o.Ek(null)):a.S("yt-remote-cast2-session-change",null))},Gza=function(a){var b=a.u.YD(),c=a.o&&a.o.u;
a=(0,g.Jc)(b,function(d){c&&f6(d,c.label)&&(c=null);var e=d.uuid?d.uuid:d.id,f=Fza(this,d);f?(f.label=e,f.friendlyName=d.name):(f=new chrome.cast.Receiver(e,d.name),f.receiverType=chrome.cast.ReceiverType.CUSTOM);return f},a);
c&&(c.receiverType!=chrome.cast.ReceiverType.CUSTOM&&(c=new chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},Mza=function(a,b,c,d,e,f,k){Hza()?Iza(b,e,f,k)&&(H7(!0),window.chrome&&chrome.cast&&chrome.cast.isAvailable?Jza(a,c):(window.__onGCastApiAvailable=function(l,m){l?Jza(a,c):(I7("Failed to load cast API: "+m),J7(!1),H7(!1),g.Ss("yt-remote-cast-available"),g.Ss("yt-remote-cast-receiver"),Kza(),c(!1))},d?g.Xo("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"):
0<=window.navigator.userAgent.indexOf("Android")&&0<=window.navigator.userAgent.indexOf("Chrome/")&&window.navigator.presentation?sya():!window.chrome||!window.navigator.presentation||0<=window.navigator.userAgent.indexOf("Edge")?s6():(rya(),r6(Lza.map(pya))))):G7("Cannot initialize because not running Chrome")},Kza=function(){G7("dispose");
var a=K7();a&&a.dispose();g.Ga("yt.mdx.remote.cloudview.instance_",null,void 0);Nza(!1);g.To(L7);L7.length=0},M7=function(){return!!g.Rs("yt-remote-cast-installed")},Oza=function(){var a=g.Rs("yt-remote-cast-receiver");
return a?a.friendlyName:null},Pza=function(){G7("clearCurrentReceiver");
g.Ss("yt-remote-cast-receiver")},Qza=function(){return M7()?K7()?K7().getCastSession():(I7("getCastSelector: Cast is not initialized."),null):(I7("getCastSelector: Cast API is not installed!"),null)},O7=function(){M7()?K7()?N7()?(G7("Requesting cast selector."),K7().requestSession()):(G7("Wait for cast API to be ready to request the session."),L7.push(g.So("yt-remote-cast2-api-ready",O7))):I7("requestCastSelector: Cast is not initialized."):I7("requestCastSelector: Cast API is not installed!")},P7=
function(a,b){N7()?K7().setConnectedScreenStatus(a,b):I7("setConnectedScreenStatus called before ready.")},Hza=function(){var a=0<=g.Pc.search(/ (CrMo|Chrome|CriOS)\//);
return g.Nt||a},Rza=function(a,b){K7().init(a,b)},Iza=function(a,b,c,d){var e=!1;
K7()||(a=new C7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(f){g.Qs("yt-remote-cast-available",f);c6("yt-remote-cast2-availability-change",f)}),a.subscribe("yt-remote-cast2-receiver-selected",function(f){G7("onReceiverSelected: "+f.friendlyName);
g.Qs("yt-remote-cast-receiver",f);c6("yt-remote-cast2-receiver-selected",f)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(f){G7("onReceiverResumed: "+f.friendlyName);
g.Qs("yt-remote-cast-receiver",f)}),a.subscribe("yt-remote-cast2-session-change",function(f){G7("onSessionChange: "+g6(f));
f||g.Ss("yt-remote-cast-receiver");c6("yt-remote-cast2-session-change",f)}),g.Ga("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
G7("cloudview.createSingleton_: "+e);return e},K7=function(){return g.Ia("yt.mdx.remote.cloudview.instance_")},Jza=function(a,b){J7(!0);
H7(!1);Rza(a,function(c){c?(Nza(!0),g.Uo("yt-remote-cast2-api-ready")):(I7("Failed to initialize cast API."),J7(!1),g.Ss("yt-remote-cast-available"),g.Ss("yt-remote-cast-receiver"),Kza());b(c)})},G7=function(a){h7("cloudview",a)},I7=function(a){h7("cloudview",a)},J7=function(a){G7("setCastInstalled_ "+a);
g.Qs("yt-remote-cast-installed",a)},N7=function(){return!!g.Ia("yt.mdx.remote.cloudview.apiReady_")},Nza=function(a){G7("setApiReady_ "+a);
g.Ga("yt.mdx.remote.cloudview.apiReady_",a,void 0)},H7=function(a){g.Ga("yt.mdx.remote.cloudview.initializing_",a,void 0)},Q7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.playerState=-1;this.muted=!1;this.audioTrackId=null;this.F=this.G=0;this.o=null;this.hasNext=this.eg=!1;this.M=this.H=this.u=this.C=0;this.B=NaN;this.A=!1;this.reset(a)},R7=function(a){a.audioTrackId=null;
a.o=null;a.playerState=-1;a.eg=!1;a.hasNext=!1;a.G=0;a.F=(0,g.C)();a.C=0;a.u=0;a.H=0;a.M=0;a.B=NaN;a.A=!1},S7=function(a){return a.nb()?((0,g.C)()-a.F)/1E3:0},T7=function(a,b){a.G=b;
a.F=(0,g.C)()},U7=function(a){switch(a.playerState){case 1:case 1081:return((0,g.C)()-a.F)/1E3+a.G;
case -1E3:return 0}return a.G},V7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&R7(a)},W7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.playerState;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.Tb(a.o);b.hasPrevious=a.eg;b.hasNext=a.hasNext;b.playerTime=a.G;b.playerTimeAt=a.F;b.seekableStart=a.C;b.seekableEnd=a.u;b.duration=a.H;b.loadedTime=a.M;b.liveIngestionTime=a.B;return b},Y7=function(a,b){g.O.call(this);
this.o=0;this.B=a;this.F=[];this.C=new dza;this.A=this.u=null;this.M=(0,g.x)(this.NK,this);this.G=(0,g.x)(this.Tm,this);this.H=(0,g.x)(this.MK,this);this.L=(0,g.x)(this.XK,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.kw,this),Sza(this))):c=3;0!=c&&(b?this.kw(c):g.Lo((0,g.x)(function(){this.kw(c)},this),0));
var d=Qza();d&&X7(this,d);this.subscribe("yt-remote-cast2-session-change",this.L)},Z7=function(a){return new Q7(a.B.getPlayerContextData())},Sza=function(a){(0,g.y)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(b){this.F.push(this.B.subscribe(b,g.Ra(this.IM,b),this))},a)},Tza=function(a){(0,g.y)(a.F,function(b){this.B.unsubscribeByKey(b)},a);
a.F.length=0},$7=function(a,b){var c=a.C;
50>c.o.length+c.u.length&&a.C.u.push(b)},b8=function(a,b,c){var d=Z7(a);
T7(d,c);-1E3!=d.playerState&&(d.playerState=b);a8(a,d)},c8=function(a,b,c){a.B.sendMessage(b,c)},a8=function(a,b){Tza(a);
a.B.setPlayerContextData(W7(b));Sza(a)},X7=function(a,b){a.A&&(a.A.removeUpdateListener(a.M),a.A.removeMediaListener(a.G),a.Tm(null));
a.A=b;a.A&&(h7("CP","Setting cast session: "+a.A.sessionId),a.A.addUpdateListener(a.M),a.A.addMediaListener(a.G),a.A.media.length&&a.Tm(a.A.media[0]))},Uza=function(a){var b=a.u.media,c=a.u.customData;
if(b&&c){var d=Z7(a);b.contentId!=d.videoId&&h7("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.playerState=c.playerState;T7(d,a.u.getEstimatedTime());a8(a,d)}else h7("CP","No cast media video. Ignoring state update.")},d8=function(a,b,c){return(0,g.x)(function(d){this.pc("Failed to "+b+" with cast v2 channel. Error code: "+d.code);
d.code!=chrome.cast.ErrorCode.TIMEOUT&&(this.pc("Retrying "+b+" using MDx browser channel."),c8(this,b,c))},a)},e8=function(a,b,c){g.O.call(this);
this.C=NaN;this.R=!1;this.H=this.G=this.M=this.L=NaN;this.T=[];this.B=this.F=this.A=this.bb=this.o=null;this.Z=a;this.T.push(g.hp(window,"beforeunload",(0,g.x)(this.dG,this)));this.u=[];this.bb=new Q7;this.U=b.id;this.o=Vza(this,c);this.o.subscribe("handlerOpened",this.RK,this);this.o.subscribe("handlerClosed",this.OK,this);this.o.subscribe("handlerError",this.PK,this);this.o.subscribe("handlerMessage",this.QK,this);hza(this.o,b.token);this.subscribe("remoteQueueChange",function(){var d=this.bb.videoId;
g.Ts()&&g.Qs("yt-remote-session-video-id",d)},this)},f8=function(a){h7("conn",a)},Vza=function(a,b){return new b7(e7(a.Z,"/bc"),b)},g8=function(a,b){a.S("proxyStateChange",b)},Wza=function(a){a.C=g.Lo((0,g.x)(function(){f8("Connecting timeout");
this.ek(1)},a),2E4)},h8=function(a){g.No(a.C);
a.C=NaN},i8=function(a){g.No(a.L);
a.L=NaN},Xza=function(a){j8(a);
a.M=g.Lo((0,g.x)(function(){k8(this,"getNowPlaying")},a),2E4)},j8=function(a){g.No(a.M);
a.M=NaN},Zza=function(a,b){b&&(h8(a),i8(a));
b==(c7(a.o)&&isNaN(a.C))?b&&(g8(a,1),k8(a,"getSubtitlesTrack")):b?(a.By()&&a.bb.reset(),g8(a,1),k8(a,"getNowPlaying"),Yza(a)):a.ek(1)},$za=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.bb.videoId&&(g.Pb(b.params)?a.bb.o=null:a.bb.o=b.params,a.S("remotePlayerChange"))},aAa=function(a,b){var c=b.params.videoId||b.params.video_id,d=parseInt(b.params.currentIndex,10);
a.bb.listId=b.params.listId||a.bb.listId;V7(a.bb,c,d);a.S("remoteQueueChange")},cAa=function(a,b){b.params=b.params||{};
aAa(a,b);bAa(a,b);a.S("autoplayDismissed")},bAa=function(a,b){var c=parseInt(b.params.currentTime||b.params.current_time,10);
T7(a.bb,isNaN(c)?0:c);c=parseInt(b.params.state,10);c=isNaN(c)?-1:c;-1==c&&-1E3==a.bb.playerState&&(c=-1E3);a.bb.playerState=c;c=Number(b.params.loadedTime);a.bb.M=isNaN(c)?0:c;c=Number(b.params.duration);a.bb.H=isNaN(c)?0:c;c=a.bb;var d=Number(b.params.liveIngestionTime);c.B=d;c.A=isNaN(d)?!1:!0;c=a.bb;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.C=isNaN(d)?0:d;c.u=isNaN(e)?0:e;1==a.bb.playerState?Xza(a):j8(a);a.S("remotePlayerChange")},dAa=function(a,b){if(-1E3!=
a.bb.playerState){var c=1085;
switch(parseInt(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.bb.playerState=c;c=parseInt(b.params.currentTime,10);T7(a.bb,isNaN(c)?0:c);a.S("remotePlayerChange")}},eAa=function(a,b){var c="true"==b.params.muted;
a.bb.volume=parseInt(b.params.volume,10);a.bb.muted=c;a.S("remotePlayerChange")},fAa=function(a,b){a.F=b.params.videoId;
a.S("nowAutoplaying",parseInt(b.params.timeout,10))},gAa=function(a,b){var c="true"==b.params.hasNext;
a.bb.eg="true"==b.params.hasPrevious;a.bb.hasNext=c;a.S("previousNextChange")},Yza=function(a){g.No(a.H);
a.H=g.Lo((0,g.x)(a.ek,a,1),864E5)},k8=function(a,b,c){c?f8("Sending: action="+b+", params="+g.Pk(c)):f8("Sending: action="+b);
a.o.sendMessage(b,c)},l8=function(a){l7.call(this,"ScreenServiceProxy");
this.Qd=a;this.o=[];this.o.push(this.Qd.$_s("screenChange",(0,g.x)(this.DP,this)));this.o.push(this.Qd.$_s("onlineScreenChange",(0,g.x)(this.mM,this)))},lAa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.L("MDX_CONFIG")||b;dya();o6();m8||(m8=new d7(b?b.loungeApiHost:void 0),lya()&&(m8.o="/api/loungedev"));n8||(n8=g.Ia("yt.mdx.remote.deferredProxies_")||[],g.Ga("yt.mdx.remote.deferredProxies_",n8,void 0));hAa();var c=o8();if(!c){var d=new u7(m8);g.Ga("yt.mdx.remote.screenService_",d,void 0);c=o8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);Mza(a,d,function(m){m?p8()&&P7(p8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){c6("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.Ia("yt.mdx.remote.initialized_")&&(g.Ga("yt.mdx.remote.initialized_",!0,void 0),q8("Initializing: "+g.Pk(b)),r8.push(g.So("yt-remote-cast2-availability-change",function(){c6("yt-remote-receiver-availability-change")})),r8.push(g.So("yt-remote-cast2-receiver-selected",function(){s8(null);
c6("yt-remote-auto-connect","cast-selector-receiver")})),r8.push(g.So("yt-remote-cast2-receiver-resumed",function(){c6("yt-remote-receiver-resumed","cast-selector-receiver")})),r8.push(g.So("yt-remote-cast2-session-change",iAa)),r8.push(g.So("yt-remote-connection-change",function(m){m?P7(p8(),"YouTube TV"):t8()||(P7(null,null),Pza())})),a=u8(),b.isAuto&&(a.id+="#dial"),g.Bo("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),q8(" -- with channel params: "+
g.Pk(a)),jAa(a),c.start(),p8()||kAa())},nAa=function(){var a=mAa();
M7()&&g.Rs("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},mAa=function(){var a=o8().Qd.$_gos();
var b=v8();b&&w8()&&(j6(a,b)||a.push(b));return cya(a)},x8=function(){var a=oAa();
!a&&M7()&&Oza()&&(a={key:"cast-selector-receiver",name:Oza()});return a},oAa=function(){var a=mAa(),b=v8();
b||(b=t8());return g.$a(a,function(c){return b&&f6(b,c.key)?!0:!1})},v8=function(){var a=p8();
if(!a)return null;var b=o8().ye();return k6(b,a)},iAa=function(a){q8("remote.onCastSessionChange_: "+g6(a));
if(a){var b=v8();b&&b.id==a.id?P7(b.id,"YouTube TV"):(b&&y8(),z8(a,1))}else w8()&&y8()},y8=function(){N7()?K7().stopSession():I7("stopSession called before API ready.");
var a=w8();a&&(a.disconnect(1),A8(null))},B8=function(){var a=w8();
return!!a&&3!=a.getProxyState()},q8=function(a){h7("remote",a)},o8=function(){if(!C8){var a=g.Ia("yt.mdx.remote.screenService_");
C8=a?new l8(a):null}return C8},p8=function(){return g.Ia("yt.mdx.remote.currentScreenId_")},pAa=function(a){g.Ga("yt.mdx.remote.currentScreenId_",a,void 0)},qAa=function(){return g.Ia("yt.mdx.remote.connectData_")},s8=function(a){g.Ga("yt.mdx.remote.connectData_",a,void 0)},w8=function(){return g.Ia("yt.mdx.remote.connection_")},A8=function(a){var b=w8();
s8(null);a||pAa("");g.Ga("yt.mdx.remote.connection_",a,void 0);n8&&((0,g.y)(n8,function(c){c(a)}),n8.length=0);
b&&!a?c6("yt-remote-connection-change",!1):!b&&a&&c6("yt-remote-connection-change",!0)},t8=function(){var a=g.Ts();
if(!a)return null;var b=o8();if(!b)return null;b=b.ye();return k6(b,a)},z8=function(a,b){p8();
v8()&&v8();if(D8)E8=a;else{pAa(a.id);var c=new e8(m8,a,u8());c.connect(b,qAa());c.subscribe("beforeDisconnect",function(d){c6("yt-remote-before-disconnect",d)});
c.subscribe("beforeDispose",function(){w8()&&(w8(),A8(null))});
A8(c)}},kAa=function(){var a=t8();
a?(q8("Resume connection to: "+g6(a)),z8(a,0)):(p6(),Pza(),q8("Skipping connecting because no session screen found."))},hAa=function(){var a=u8();
if(g.Pb(a)){a=n6();var b=g.Rs("yt-remote-session-name")||"",c=g.Rs("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.Ga("yt.mdx.remote.channelParams_",a,void 0)}},u8=function(){return g.Ia("yt.mdx.remote.channelParams_")||{}},jAa=function(a){a?(g.Qs("yt-remote-session-app",a.app),g.Qs("yt-remote-session-name",a.name)):(g.Ss("yt-remote-session-app"),g.Ss("yt-remote-session-name"));
g.Ga("yt.mdx.remote.channelParams_",a,void 0)},F8=function(a,b,c){g.z.call(this);
var d=this;this.module=a;this.J=b;this.Ua=c;this.events=new g.Ur(this);this.M=this.events.N(this.J,"onVolumeChange",this.xB);this.B=!1;this.suggestion=null;this.C=new g.MC(64);this.o=new g.I(this.eD,500,this);this.u=new g.I(this.fD,1E3,this);this.G=new t6(this.gP,0,this);this.A={};this.H=new g.I(this.KD,1E3,this);this.F=new u6(this.seekTo,1E3,this);this.L=g.Ja;g.A(this,this.events);this.events.N(b,"onCaptionsTrackListChanged",this.ML);this.events.N(b,"captionschanged",this.LK);this.events.N(b,"captionssettingschanged",
this.hD);this.events.N(b,"videoplayerreset",this.kq);this.events.N(b,"mdxautoplaycancel",function(){d.Ua.Px()});
a=this.Ua;a.ha();a.subscribe("proxyStateChange",this.RB,this);a.subscribe("remotePlayerChange",this.Xm,this);a.subscribe("remoteQueueChange",this.kq,this);a.subscribe("previousNextChange",this.NB,this);a.subscribe("nowAutoplaying",this.JB,this);a.subscribe("autoplayDismissed",this.gB,this);g.A(this,this.o);g.A(this,this.u);g.A(this,this.G);g.A(this,this.H);g.A(this,this.F);this.hD();this.kq();this.Xm()},rAa=function(a){a.ac(0);
a.o.stop();G8(a,new g.MC(64))},I8=function(a,b){if(H8(a)&&!a.B){var c=null;
b&&(c={style:a.J.getSubtitlesUserSettings()},g.Wb(c,b));a.Ua.WD(a.J.getVideoData(1).videoId,c);a.A=Z7(a.Ua).o}},J8=function(a,b){var c=a.J.getPlaylist();
if(c){var d=c.index;var e=c.listId.toString()}c=a.J.getVideoData(1);a.Ua.playVideo(c.videoId,b,d,e,c.playerParams,c.fg,Qxa(c));G8(a,new g.MC(1))},sAa=function(a,b){if(b){var c=a.J.getOption("captions","tracklist",{cz:1});
c&&c.length?(a.J.setOption("captions","track",b),a.B=!1):(a.J.loadModule("captions"),a.B=!0)}else a.J.setOption("captions","track",{})},H8=function(a){return Z7(a.Ua).videoId===a.J.getVideoData(1).videoId},G8=function(a,b){a.u.stop();
var c=a.C;if(!g.SC(c,b)){var d=g.U(b,2);d!==g.U(a.C,2)&&g.vT(a.J.app,d);a.C=b;tAa(a.module,c,b)}},K8=function(){g.W.call(this,{D:"div",
I:"ytp-mdx-manual-pairing-popup-dialog",P:{role:"dialog"},K:[{D:"div",I:"ytp-mdx-manual-pairing-popup-dialog-inner-content",K:[{D:"div",I:"ytp-mdx-manual-pairing-popup-title",W:"Em breve, n\u00e3o ser\u00e1 mais poss\u00edvel usar um c\u00f3digo na Web para conectar o YouTube \u00e0 sua TV"},{D:"div",I:"ytp-mdx-manual-pairing-popup-buttons",K:[{D:"button",X:["ytp-button","ytp-mdx-manual-pairing-popup-learn-more"],W:"Saiba mais"},{D:"button",X:["ytp-button","ytp-mdx-manual-pairing-popup-ok"],W:"OK"}]}]}]});
this.o=new g.PN(this,250);this.learnMoreButton=this.da("ytp-mdx-manual-pairing-popup-learn-more");this.okButton=this.da("ytp-mdx-manual-pairing-popup-ok");g.A(this,this.o);this.N(this.learnMoreButton,"click",this.u);this.N(this.okButton,"click",this.A)},L8=function(){g.W.call(this,{D:"div",
I:"ytp-mdx-popup-dialog",P:{role:"dialog"},K:[{D:"div",I:"ytp-mdx-popup-dialog-inner-content",K:[{D:"div",I:"ytp-mdx-popup-title",W:"Voc\u00ea n\u00e3o fez login"},{D:"div",I:"ytp-mdx-popup-description",W:"Os v\u00eddeos que voc\u00ea assistir poder\u00e3o ser adicionados ao hist\u00f3rico de visualiza\u00e7\u00e3o da TV e influenciar\u00e3o as recomenda\u00e7\u00f5es dela. Para evitar isso, cancele e fa\u00e7a login no YouTube em um computador."},{D:"div",I:"ytp-mdx-privacy-popup-buttons",K:[{D:"button",
X:["ytp-button","ytp-mdx-privacy-popup-cancel"],W:"Cancelar"},{D:"button",X:["ytp-button","ytp-mdx-privacy-popup-confirm"],W:"Confirmar"}]}]}]});this.o=new g.PN(this,250);this.cancelButton=this.da("ytp-mdx-privacy-popup-cancel");this.confirmButton=this.da("ytp-mdx-privacy-popup-confirm");g.A(this,this.o);this.N(this.cancelButton,"click",this.u);this.N(this.confirmButton,"click",this.A)},M8=function(a){g.W.call(this,{D:"div",
I:"ytp-remote",K:[{D:"div",I:"ytp-remote-display-status",K:[{D:"div",I:"ytp-remote-display-status-icon",K:[g.iN()]},{D:"div",I:"ytp-remote-display-status-text",W:"{{statustext}}"}]}]});this.api=a;this.o=new g.PN(this,250);g.A(this,this.o);this.N(a,"presentingplayerstatechange",this.u);uAa(this,g.tL(a))},uAa=function(a,b){if(3===a.api.getPresentingPlayerType()){var c={RECEIVER_NAME:a.api.getOption("remote","currentReceiver").name};
c=g.U(b,128)?g.KM("Erro em $RECEIVER_NAME",c):b.nb()||g.U(b,4)?g.KM("Reproduzindo em $RECEIVER_NAME",c):g.KM("Conectado a $RECEIVER_NAME",c);a.oa("statustext",c);a.o.show()}else a.o.hide()},N8=function(a,b){g.DP.call(this,"Reproduzir em",0,a,b);
this.J=a;this.ti={};this.N(a,"onMdxReceiversChange",this.B);this.N(a,"presentingplayerstatechange",this.B);this.B()},O8=function(a){g.ZL.call(this,a);
this.Bf={key:i6(),name:"Este computador"};this.qe=null;this.subscriptions=[];this.Vu=this.Ua=null;this.ti=[this.Bf];this.Dh=this.Bf;this.Pb=new g.MC(64);this.uz=0;this.kd=-1;this.Gk=null;this.Ym=this.rp=!1;this.Cj=this.kl=null;if(!g.ez(this.player.O())){a=this.player;var b=g.jC(a);b&&(b=b.Mm())&&(b=new N8(a,b),g.A(this,b));b=new M8(a);g.A(this,b);g.NL(a,b.element,4);this.kl=new L8;g.A(this,this.kl);g.NL(a,this.kl.element,4);g.P(this.player.O().experiments,"pair_servlet_deprecation_warning_enabled")&&
(this.Gk=new K8,g.A(this,this.Gk),g.NL(a,this.Gk.element,4));this.Ym=!!t8();this.rp=!!g.Rs("yt-remote-manual-pairing-warning-shown")}},P8=function(a){a.Cj&&(a.player.removeEventListener("presentingplayerstatechange",a.Cj),a.Cj=null)},tAa=function(a,b,c){a.Pb=c;
a.player.S("presentingplayerstatechange",new g.rH(c,b))},vAa=function(a,b,c){var d=!1;
1===b?d=!a.Ym:2===b&&(d=!a.rp);d&&g.tH(c,8)&&(a.player.pauseVideo(),P8(a))},Q8=function(a,b){if(b.key!==a.Dh.key)if(b.key===a.Bf.key)y8();
else{if(a.Gk&&!a.rp&&b!==a.Bf&&"cast-selector-receiver"!==b.key&&g.nz(a.player.O()))wAa(a);else{var c;(c=!g.P(a.player.O().experiments,"mdx_enable_privacy_disclosure_ui"))||(c=((c=g.L("PLAYER_CONFIG"))&&c.args&&void 0!==c.args.authuser?!0:!(!g.L("SESSION_INDEX")&&!g.L("LOGGED_IN")))||a.Ym||!a.kl);(c?0:g.nz(a.player.O())||g.rz(a.player.O()))&&xAa(a)}a.Dh=b;var d=a.player.getPlaylistId();c=a.player.getVideoData(1);var e=c.videoId;if(!d&&!e||(2===a.player.getAppState()||1===a.player.getAppState())&&
g.P(a.player.O().experiments,"should_clear_video_data_on_player_cued_unstarted"))c=null;else{var f=a.player.getPlaylist();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Da(l).videoId}else k=[e];f=a.player.getCurrentTime(1);d={videoIds:k,listId:d,videoId:e,playerParams:c.playerParams,clickTrackingParams:c.fg,index:Math.max(a.player.getPlaylistIndex(),0),currentTime:0===f?void 0:f};(c=Qxa(c))&&(d.locationInfo=c);c=d}q8("Connecting to: "+g.Pk(b));"cast-selector-receiver"==b.key?(s8(c||null),c=
c||null,N7()?K7().setLaunchParams(c):I7("setLaunchParams called before ready.")):!c&&B8()&&p8()==b.key?c6("yt-remote-connection-change",!0):(y8(),s8(c||null),c=o8().ye(),(c=k6(c,b.key))&&z8(c,1))}},xAa=function(a){g.tL(a.player).nb()?a.player.pauseVideo():(a.Cj=function(b){vAa(a,1,b)},a.player.addEventListener("presentingplayerstatechange",a.Cj));
a.kl&&a.kl.jc();w8()||(D8=!0)},wAa=function(a){g.tL(a.player).nb()?a.player.pauseVideo():(a.Cj=function(b){vAa(a,2,b)},a.player.addEventListener("presentingplayerstatechange",a.Cj));
a.Gk&&a.Gk.jc();w8()||(D8=!0)},Bya={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"\\u003C"},H6={"'":"\\'"},yAa={},Zxa={nQ:"atp",AT:"ska",kT:"que",yS:"mus",zT:"sus",zR:"dsp",sT:"seq"},q6,m6="",qya=mya("loadCastFramework")||mya("loadCastApplicationFramework"),Lza=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];/*

 Copyright The Closure Library Authors.
 SPDX-License-Identifier: Apache-2.0
*/
g.Ta(t6,g.z);g.h=t6.prototype;g.h.aG=function(a){this.B=arguments;this.o=!1;this.Ja?this.A=(0,g.C)()+this.Rd:this.Ja=g.$f(this.C,this.Rd)};
g.h.stop=function(){this.Ja&&(g.v.clearTimeout(this.Ja),this.Ja=null);this.A=null;this.o=!1;this.B=[]};
g.h.pause=function(){++this.u};
g.h.resume=function(){this.u&&(--this.u,!this.u&&this.o&&(this.o=!1,this.F.apply(null,this.B)))};
g.h.Y=function(){this.stop();t6.Tb.Y.call(this)};
g.h.bG=function(){this.A?(this.Ja=g.$f(this.C,this.A-(0,g.C)()),this.A=null):(this.Ja=null,this.u?this.o=!0:(this.o=!1,this.F.apply(null,this.B)))};g.r(u6,g.z);g.h=u6.prototype;g.h.Jz=function(a){this.A=arguments;this.Ja||this.u?this.o=!0:v6(this)};
g.h.stop=function(){this.Ja&&(g.v.clearTimeout(this.Ja),this.Ja=null,this.o=!1,this.A=null)};
g.h.pause=function(){this.u++};
g.h.resume=function(){this.u--;this.u||!this.o||this.Ja||(this.o=!1,v6(this))};
g.h.Y=function(){g.z.prototype.Y.call(this);this.stop()};x6.prototype.stringify=function(a){return g.v.JSON.stringify(a,void 0)};
x6.prototype.parse=function(a){return g.v.JSON.parse(a,void 0)};y6.prototype.o=null;y6.prototype.getOptions=function(){var a;(a=this.o)||(a={},uya(this)&&(a[0]=!0,a[1]=!0),a=this.o=a);return a};var R8;g.Ta(tya,y6);R8=new tya;g.h=z6.prototype;g.h.dj=null;g.h.Mf=!1;g.h.Cl=null;g.h.hw=null;g.h.pl=null;g.h.vl=null;g.h.yh=null;g.h.vi=null;g.h.Dj=null;g.h.bd=null;g.h.Bn=0;g.h.Qf=null;g.h.dr=null;g.h.Oh=null;g.h.om=-1;g.h.TC=!0;g.h.Ni=!1;g.h.kt=0;g.h.wq=null;var zya={},C6={};g.h=z6.prototype;g.h.setTimeout=function(a){this.C=a};
g.h.oO=function(a){a=a.target;var b=this.wq;b&&3==Q6(a)?b.Jz():this.TD(a)};
g.h.TD=function(a){try{if(a==this.bd)a:{var b=Q6(this.bd),c=this.bd.F,d=this.bd.getStatus();if(g.oe&&!g.Td(10)||g.qe&&!g.Sd("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Bh&&!S6(this.bd))break a;this.Ni||4!=b||7==c||(8==c||0>=d?this.o.Gf(3):this.o.Gf(2));J6(this);var e=this.bd.getStatus();this.om=e;var f=S6(this.bd);(this.Mf=200==e)?(4==b&&F6(this),this.F?(Aya(this,b,f),g.Bh&&this.Mf&&3==b&&(this.B.na(this.u,"tick",this.hO),this.u.start())):E6(this,f),this.Mf&&!this.Ni&&(4==b?this.o.Oo(this):(this.Mf=
!1,B6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.Oh=3,D6(13)):(this.Oh=0,D6(14)),F6(this),G6(this))}}catch(k){this.bd&&S6(this.bd)}finally{}};
g.h.hO=function(){var a=Q6(this.bd),b=S6(this.bd);this.Bn<b.length&&(J6(this),Aya(this,a,b),this.Mf&&4!=a&&B6(this))};
g.h.EN=function(a){I6((0,g.x)(this.DN,this,a),0)};
g.h.DN=function(a){this.Ni||(J6(this),E6(this,a),B6(this))};
g.h.aC=function(a){I6((0,g.x)(this.CN,this,a),0)};
g.h.CN=function(a){this.Ni||(F6(this),this.Mf=a,this.o.Oo(this),this.o.Gf(4))};
g.h.cancel=function(){this.Ni=!0;F6(this)};
g.h.MN=function(){this.Cl=null;var a=(0,g.C)();0<=a-this.hw?(2!=this.vl&&this.o.Gf(3),F6(this),this.Oh=2,D6(18),G6(this)):Dya(this,this.hw-a)};
g.h.getLastError=function(){return this.Oh};g.h=Gya.prototype;g.h.it=null;g.h.ke=null;g.h.xq=!1;g.h.My=null;g.h.xo=null;g.h.Pt=null;g.h.jt=null;g.h.Qe=null;g.h.Wg=-1;g.h.nm=null;g.h.Ql=null;g.h.connect=function(a){this.jt=a;a=L6(this.o,null,this.jt);D6(3);this.My=(0,g.C)();var b=this.o.H;null!=b?(this.nm=b[0],(this.Ql=b[1])?(this.Qe=1,Hya(this)):(this.Qe=2,N6(this))):($5(a,"MODE","init"),this.ke=new z6(this,void 0,void 0,void 0),this.ke.dj=this.it,A6(this.ke,a,!1,null,!0),this.Qe=0)};
g.h.aF=function(a){if(a)this.Qe=2,N6(this);else{D6(4);var b=this.o;b.dg=b.Bh.Wg;Z6(b,9)}a&&this.Gf(2)};
g.h.ts=function(a){return this.o.ts(a)};
g.h.abort=function(){this.ke&&(this.ke.cancel(),this.ke=null);this.Wg=-1};
g.h.Ly=function(){return!1};
g.h.SB=function(a,b){this.Wg=a.om;if(0==this.Qe)if(b){try{var c=this.u.parse(b)}catch(d){c=this.o;c.dg=this.Wg;Z6(c,2);return}this.nm=c[0];this.Ql=c[1]}else c=this.o,c.dg=this.Wg,Z6(c,2);else if(2==this.Qe)if(this.xq)D6(7),this.Pt=(0,g.C)();else if("11111"==b){if(D6(6),this.xq=!0,this.xo=(0,g.C)(),c=this.xo-this.My,!g.oe||g.Td(10)||500>c)this.Wg=200,this.ke.cancel(),D6(12),M6(this.o,this,!0)}else D6(8),this.xo=this.Pt=(0,g.C)(),this.xq=!1};
g.h.Oo=function(){this.Wg=this.ke.om;if(this.ke.Mf)0==this.Qe?this.Ql?(this.Qe=1,Hya(this)):(this.Qe=2,N6(this)):2==this.Qe&&((!g.oe||g.Td(10)?!this.xq:200>this.Pt-this.xo)?(D6(11),M6(this.o,this,!1)):(D6(12),M6(this.o,this,!0)));else{0==this.Qe?D6(9):2==this.Qe&&D6(10);var a=this.o;this.ke.getLastError();a.dg=this.Wg;Z6(a,2)}};
g.h.on=function(){return this.o.on()};
g.h.isActive=function(){return this.o.isActive()};
g.h.Gf=function(a){this.o.Gf(a)};g.Ta(O6,g.nf);var Mya=/^https?$/i,zAa=["POST","PUT"];g.h=O6.prototype;
g.h.send=function(a,b,c,d){if(this.o)throw Error("[goog.net.XhrIo] Object is active with another request="+this.M+"; newUri="+a);b=b?b.toUpperCase():"GET";this.M=a;this.B="";this.F=0;this.ea=b;this.Z=!1;this.A=!0;this.o=this.U?vya(this.U):vya(R8);this.T=this.U?this.U.getOptions():R8.getOptions();this.o.onreadystatechange=(0,g.x)(this.OB,this);try{b6(R6(this,"Opening Xhr")),this.ba=!0,this.o.open(b,String(a),!0),this.ba=!1}catch(f){b6(R6(this,"Error opening Xhr: "+f.message));Lya(this,f);return}a=
c||"";var e=this.headers.clone();d&&Vxa(d,function(f,k){e.set(k,f)});
d=g.$a(e.Oe(),Jya);c=g.v.FormData&&a instanceof g.v.FormData;!g.cb(zAa,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(f,k){this.o.setRequestHeader(k,f)},this);
this.fa&&(this.o.responseType=this.fa);"withCredentials"in this.o&&this.o.withCredentials!==this.aa&&(this.o.withCredentials=this.aa);try{Oya(this),0<this.G&&(this.R=Iya(this.o),b6(R6(this,"Will abort after "+this.G+"ms if incomplete, xhr2 "+this.R)),this.R?(this.o.timeout=this.G,this.o.ontimeout=(0,g.x)(this.Ny,this)):this.L=g.$f(this.Ny,this.G,this)),b6(R6(this,"Sending request")),this.H=!0,this.o.send(a),this.H=!1}catch(f){b6(R6(this,"Send error: "+f.message)),Lya(this,f)}};
g.h.Ny=function(){"undefined"!=typeof g.E1&&this.o&&(this.B="Timed out after "+this.G+"ms, aborting",this.F=8,R6(this,this.B),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.o&&this.A&&(R6(this,"Aborting"),this.A=!1,this.C=!0,this.o.abort(),this.C=!1,this.F=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),P6(this))};
g.h.Y=function(){this.o&&(this.A&&(this.A=!1,this.C=!0,this.o.abort(),this.C=!1),P6(this,!0));O6.Tb.Y.call(this)};
g.h.OB=function(){this.ha()||(this.ba||this.H||this.C?Nya(this):this.KM())};
g.h.KM=function(){Nya(this)};
g.h.isActive=function(){return!!this.o};
g.h.getStatus=function(){try{return 2<Q6(this)?this.o.status:-1}catch(a){return-1}};
g.h.getLastError=function(){return"string"===typeof this.B?this.B:String(this.B)};g.h=T6.prototype;g.h.fm=null;g.h.ce=null;g.h.yc=null;g.h.ht=null;g.h.Ao=null;g.h.ix=null;g.h.No=null;g.h.Sm=0;g.h.gK=0;g.h.Nd=null;g.h.Gh=null;g.h.Hg=null;g.h.Ti=null;g.h.Bh=null;g.h.Zq=null;g.h.Dk=-1;g.h.sz=-1;g.h.dg=-1;g.h.jk=0;g.h.Wj=0;g.h.Oi=8;var $6=new g.nf;g.Ta(Qya,g.Pe);g.Ta(Rya,g.Pe);g.Ta(Sya,g.Pe);g.h=T6.prototype;g.h.connect=function(a,b,c,d,e){D6(0);this.ht=b;this.fm=c||{};d&&void 0!==e&&(this.fm.OSID=d,this.fm.OAID=e);this.F?(I6((0,g.x)(this.Cx,this,a),100),Wya(this)):this.Cx(a)};
g.h.Cx=function(a){this.Bh=new Gya(this);this.Bh.it=null;this.Bh.u=this.C;this.Bh.connect(a)};
g.h.Ly=function(){return 0==this.o};
g.h.ZB=function(a){this.Gh=null;Zya(this,a)};
g.h.YB=function(){this.Hg=null;this.yc=new z6(this,this.A,"rpc",this.G);this.yc.dj=null;this.yc.kt=0;var a=this.ix.clone();Y5(a,"RID","rpc");Y5(a,"SID",this.A);Y5(a,"CI",this.Zq?"0":"1");Y5(a,"AID",this.Dk);U6(this,a);if(!g.oe||g.Td(10))Y5(a,"TYPE","xmlhttp"),A6(this.yc,a,!0,this.No,!1);else{Y5(a,"TYPE","html");var b=this.yc,c=!!this.No;b.vl=3;b.yh=Z5(a.clone());Cya(b,c)}};
g.h.SB=function(a,b){if(0!=this.o&&(this.yc==a||this.ce==a))if(this.dg=a.om,this.ce==a&&3==this.o)if(7<this.Oi){try{var c=this.C.parse(b)}catch(f){c=null}if(Array.isArray(c)&&3==c.length)if(0==c[0])a:{if(!this.Hg){if(this.yc)if(this.yc.pl+3E3<this.ce.pl)W6(this),this.yc.cancel(),this.yc=null;else break a;Y6(this);D6(19)}}else this.sz=c[1],0<this.sz-this.Dk&&37500>c[2]&&this.Zq&&0==this.Wj&&!this.Ti&&(this.Ti=I6((0,g.x)(this.HK,this),6E3));else Z6(this,11)}else b!=yAa.PQ.o&&Z6(this,11);else if(this.yc==
a&&W6(this),!g.lc(b)){c=this.C.parse(b);for(var d=0;d<c.length;d++){var e=c[d];this.Dk=e[0];e=e[1];2==this.o?"c"==e[0]?(this.A=e[1],this.No=e[2],e=e[3],null!=e?this.Oi=e:this.Oi=6,this.o=3,this.Nd&&this.Nd.yx(),this.ix=L6(this,this.on()?this.No:null,this.ht),$ya(this)):"stop"==e[0]&&Z6(this,7):3==this.o&&("stop"==e[0]?Z6(this,7):"noop"!=e[0]&&this.Nd&&this.Nd.xx(e),this.Wj=0)}}};
g.h.HK=function(){null!=this.Ti&&(this.Ti=null,this.yc.cancel(),this.yc=null,Y6(this),D6(20))};
g.h.Oo=function(a){if(this.yc==a){W6(this);this.yc=null;var b=2}else if(this.ce==a)this.ce=null,b=1;else return;this.dg=a.om;if(0!=this.o)if(a.Mf)1==b?(b=(0,g.C)()-a.pl,$6.dispatchEvent(new Rya($6,a.Dj?a.Dj.length:0,b,this.jk)),V6(this),this.B.length=0):$ya(this);else{var c=a.getLastError(),d;if(!(d=3==c||7==c||0==c&&0<this.dg)){if(d=1==b)this.ce||this.Gh||1==this.o||2<=this.jk?d=!1:(this.Gh=I6((0,g.x)(this.ZB,this,a),aza(this,this.jk)),this.jk++,d=!0);d=!(d||2==b&&Y6(this))}if(d)switch(c){case 1:Z6(this,
5);break;case 4:Z6(this,10);break;case 3:Z6(this,6);break;case 7:Z6(this,12);break;default:Z6(this,2)}}};
g.h.xF=function(a){if(!g.cb(arguments,this.o))throw Error("Unexpected channel state: "+this.o);};
g.h.ZO=function(a){a?D6(2):(D6(1),bza(this,8))};
g.h.ts=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new O6;a.aa=!1;return a};
g.h.isActive=function(){return!!this.Nd&&this.Nd.isActive(this)};
g.h.Gf=function(a){$6.dispatchEvent(new Sya($6,a))};
g.h.on=function(){return!(!g.oe||g.Td(10))};
g.h=cza.prototype;g.h.yx=function(){};
g.h.xx=function(){};
g.h.wx=function(){};
g.h.Yr=function(){};
g.h.iy=function(){return{}};
g.h.isActive=function(){return!0};g.h=dza.prototype;g.h.isEmpty=function(){return g.db(this.o)&&g.db(this.u)};
g.h.clear=function(){this.o=[];this.u=[]};
g.h.contains=function(a){return g.cb(this.o,a)||g.cb(this.u,a)};
g.h.remove=function(a){var b=this.o;var c=(0,g.Dsa)(b,a);0<=c?(g.fb(b,c),b=!0):b=!1;return b||g.gb(this.u,a)};
g.h.Yd=function(){for(var a=[],b=this.o.length-1;0<=b;--b)a.push(this.o[b]);var c=this.u.length;for(b=0;b<c;++b)a.push(this.u[b]);return a};g.Ta(a7,g.z);g.h=a7.prototype;g.h.xN=function(){this.Rd=Math.min(3E5,2*this.Rd);this.A();this.u&&this.start()};
g.h.start=function(){var a=this.Rd+15E3*Math.random();this.o.Za(a);this.u=(0,g.C)()+a};
g.h.stop=function(){this.o.stop();this.u=0};
g.h.isActive=function(){return this.o.isActive()};
g.h.reset=function(){this.o.stop();this.Rd=5E3};g.Ta(b7,cza);g.h=b7.prototype;g.h.subscribe=function(a,b,c){return this.A.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.A.unsubscribe(a,b,c)};
g.h.li=function(a){return this.A.ej(a)};
g.h.S=function(a,b){return this.A.S.apply(this.A,arguments)};
g.h.dispose=function(){this.Lb||(this.Lb=!0,g.Ne(this.A),gza(this),g.Ne(this.u),this.u=null)};
g.h.ha=function(){return this.Lb};
g.h.connect=function(a,b,c){if(!this.o||2!=this.o.o){this.M="";this.u.stop();this.C=a||null;this.B=b||0;a=this.L+"/test";b=this.L+"/bind";var d=new T6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.R),e=this.o;e&&(e.Nd=null);d.Nd=this;this.o=d;e?this.o.connect(a,b,this.F,e.A,e.Dk):c?this.o.connect(a,b,this.F,c.sessionId,c.arrayId):this.o.connect(a,b,this.F)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.Wb(c,b);this.u.isActive()||2==(this.o?this.o.o:0)?this.G.push(c):c7(this)&&Xya(this.o,c)};
g.h.yx=function(){this.u.reset();this.C=null;this.B=0;if(this.G.length){var a=this.G;this.G=[];for(var b=0,c=a.length;b<c;++b)Xya(this.o,a[b])}this.S("handlerOpened")};
g.h.wx=function(a){var b=2==a&&401==this.o.dg;4==a||b||this.u.start();this.S("handlerError",a)};
g.h.Yr=function(a){if(!this.u.isActive())this.S("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.G.push(d)}};
g.h.iy=function(){var a={v:2};this.M&&(a.gsessionid=this.M);0!=this.B&&(a.ui=""+this.B);0!=this.H&&(a.ui=""+this.H);this.C&&g.Wb(a,this.C);return a};
g.h.xx=function(a){"S"==a[0]?this.M=a[1]:"gracefulReconnect"==a[0]?(this.u.start(),Vya(this.o)):this.S("handlerMessage",new eza(a[0],a[1]))};
g.h.BO=function(){this.u.isActive();var a=this.o,b=0;a.yc&&b++;a.ce&&b++;0==b&&this.connect(this.C,this.B)};d7.prototype.B=function(a,b,c,d){b?a(d):a({text:c.responseText})};
d7.prototype.A=function(a,b){a(Error("Request error: "+b.status))};
d7.prototype.C=function(a){a(Error("request timed out"))};var oza=(0,g.C)(),g7=null,j7=Array(50),i7=-1,k7=!1;g.Ta(l7,g.O);l7.prototype.ye=function(){return this.screens};
l7.prototype.contains=function(a){return!!j6(this.screens,a)};
l7.prototype.get=function(a){return a?k6(this.screens,a):null};
l7.prototype.info=function(a){h7(this.F,a)};g.r(m7,g.O);g.h=m7.prototype;g.h.start=function(){!this.o&&isNaN(this.Ja)&&this.XD()};
g.h.stop=function(){this.o&&(this.o.abort(),this.o=null);isNaN(this.Ja)||(g.No(this.Ja),this.Ja=NaN)};
g.h.Y=function(){this.stop();g.O.prototype.Y.call(this)};
g.h.XD=function(){this.Ja=NaN;this.o=g.wq(e7(this.F,"/pairing/get_screen"),{method:"POST",yb:{pairing_code:this.B},timeout:5E3,onSuccess:(0,g.x)(this.BP,this),onError:(0,g.x)(this.AP,this),Ge:(0,g.x)(this.CP,this)})};
g.h.BP=function(a,b){this.o=null;var c=b.screen||{};c.dialId=this.C;c.name=this.A;this.S("pairingComplete",new e6(c))};
g.h.AP=function(a){this.o=null;a.status&&404==a.status?this.u>=AAa.length?this.S("pairingFailed",Error("DIAL polling timed out")):(a=AAa[this.u],this.Ja=g.Lo((0,g.x)(this.XD,this),a),this.u++):this.S("pairingFailed",Error("Server error "+a.status))};
g.h.CP=function(){this.o=null;this.S("pairingFailed",Error("Server not responding"))};
var AAa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.Ta(o7,l7);g.h=o7.prototype;g.h.start=function(){n7(this)&&this.S("screenChange");!g.Rs("yt-remote-lounge-token-expiration")&&sza(this);g.No(this.o);this.o=g.Lo((0,g.x)(this.start,this),1E4)};
g.h.add=function(a,b){n7(this);pza(this,a);p7(this,!1);this.S("screenChange");b(a);a.token||sza(this)};
g.h.remove=function(a,b){var c=n7(this);rza(this,a)&&(p7(this,!1),c=!0);b(a);c&&this.S("screenChange")};
g.h.Xq=function(a,b,c,d){var e=n7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,p7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.S("screenChange")};
g.h.Y=function(){g.No(this.o);o7.Tb.Y.call(this)};
g.h.lG=function(a){n7(this);var b=this.screens.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}p7(this,!b);b&&h7(this.F,"Missed "+b+" lounge tokens.")};
g.h.kG=function(a){h7(this.F,"Requesting lounge tokens failed: "+a)};g.r(r7,g.O);g.h=r7.prototype;g.h.start=function(){var a=parseInt(g.Rs("yt-remote-fast-check-period")||"0",10);(this.B=(0,g.C)()-144E5<a?0:a)?t7(this):(this.B=(0,g.C)()+3E5,g.Qs("yt-remote-fast-check-period",this.B),this.kv())};
g.h.isEmpty=function(){return g.Pb(this.o)};
g.h.update=function(){q7("Updating availability on schedule.");var a=this.F(),b=g.Db(this.o,function(c,d){return c&&!!k6(a,d)},this);
s7(this,b)};
g.h.Y=function(){g.No(this.A);this.A=NaN;this.u&&(this.u.abort(),this.u=null);g.O.prototype.Y.call(this)};
g.h.kv=function(){g.No(this.A);this.A=NaN;this.u&&this.u.abort();var a=vza(this);if(a6(a)){var b=e7(this.C,"/pairing/get_screen_availability");this.u=f7(this.C,b,{lounge_token:g.Jb(a).join(",")},(0,g.x)(this.hN,this,a),(0,g.x)(this.gN,this))}else s7(this,{}),t7(this)};
g.h.hN=function(a,b){this.u=null;var c=g.Jb(vza(this));if(g.wb(c,g.Jb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;s7(this,d);t7(this)}else this.pc("Changing Screen set during request."),this.kv()};
g.h.gN=function(a){this.pc("Screen availability failed: "+a);this.u=null;t7(this)};
g.h.pc=function(a){h7("OnlineScreenService",a)};g.Ta(u7,l7);g.h=u7.prototype;g.h.start=function(){this.u.start();this.o.start();this.screens.length&&(this.S("screenChange"),this.o.isEmpty()||this.S("onlineScreenChange"))};
g.h.add=function(a,b,c){this.u.add(a,b,c)};
g.h.remove=function(a,b,c){this.u.remove(a,b,c);this.o.update()};
g.h.Xq=function(a,b,c,d){this.u.contains(a)?this.u.Xq(a,b,c,d):(a="Updating name of unknown screen: "+a.name,h7(this.F,a),d(Error(a)))};
g.h.ye=function(a){return a?this.screens:g.kb(this.screens,(0,g.Be)(this.A,function(b){return!this.contains(b)},this))};
g.h.YD=function(){return(0,g.Be)(this.ye(!0),function(a){return!!this.o.o[a.id]},this)};
g.h.ZD=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new m7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.x)(function(k){g.Ne(f);d(v7(this,k))},this));
f.subscribe("pairingFailed",function(k){g.Ne(f);e(k)});
f.start();return(0,g.x)(f.stop,f)};
g.h.EP=function(a,b,c,d){g.wq(e7(this.C,"/pairing/get_screen"),{method:"POST",yb:{pairing_code:a},timeout:5E3,onSuccess:(0,g.x)(function(e,f){var k=new e6(f.screen||{});if(!k.name||zza(this,k.name)){a:{var l=k.name;for(var m=2,n=b(l,m);zza(this,n);){m++;if(20<m)break a;n=b(l,m)}l=n}k.name=l}c(v7(this,k))},this),
onError:(0,g.x)(function(e){d(Error("pairing request failed: "+e.status))},this),
Ge:(0,g.x)(function(){d(Error("pairing request timed out."))},this)})};
g.h.Y=function(){g.Ne(this.u);g.Ne(this.o);u7.Tb.Y.call(this)};
g.h.tG=function(){Aza(this);this.S("screenChange");this.o.update()};
u7.prototype.dispose=u7.prototype.dispose;g.Ta(x7,g.O);g.h=x7.prototype;g.h.getScreen=function(){return this.H};
g.h.jq=function(a){this.H=a;this.S("sessionScreen",this.H)};
g.h.Fe=function(a){this.ha()||(a&&y7(this,""+a),this.H=null,this.S("sessionScreen",null))};
g.h.info=function(a){h7(this.T,a)};
g.h.bE=function(){return null};
g.h.Bv=function(a){var b=this.u;a?(b.displayStatus=new chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;chrome.cast.setReceiverDisplayStatus(b,(0,g.x)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.x)(function(){y7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.Y=function(){this.Bv("");x7.Tb.Y.call(this)};g.Ta(z7,x7);g.h=z7.prototype;g.h.Av=function(a){if(this.o){if(this.o==a)return;y7(this,"Overriding cast sesison with new session object");this.o.removeUpdateListener(this.C);this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.o=a;this.o.addUpdateListener(this.C);this.o.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);Cza(this)};
g.h.Ek=function(a){this.info("launchWithParams no-op for Cast: "+g.Pk(a))};
g.h.stop=function(){this.o?this.o.stop((0,g.x)(function(){this.Fe()},this),(0,g.x)(function(){this.Fe(Error("Failed to stop receiver app."))},this)):this.Fe(Error("Stopping cast device witout session."))};
g.h.Bv=g.Ja;g.h.Y=function(){this.info("disposeInternal");g.No(this.A);this.A=0;this.o&&(this.o.removeUpdateListener(this.C),this.o.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.o=null;z7.Tb.Y.call(this)};
g.h.UN=function(a,b){if(!this.ha())if(b){var c=w6(b);if(g.Oa(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Pk(c));switch(d){case "mdxSessionStatus":Bza(this,c.screenId);break;default:y7(this,"Unknown youtube message: "+d)}}else y7(this,"Unable to parse message.")}else y7(this,"No data in message.")};
g.h.Dy=function(a,b,c,d){yza(this.M,this.u.label,a,this.u.friendlyName,(0,g.x)(function(e){e?b(e):0<=d?(y7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.Lo((0,g.x)(this.Dy,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.bE=function(){return this.o};
g.h.FP=function(a){this.ha()||a||(y7(this,"Cast session died."),this.Fe())};g.Ta(A7,x7);g.h=A7.prototype;g.h.Av=function(a){this.A=a;this.A.addUpdateListener(this.R)};
g.h.Ek=function(a){this.B=a;this.F()};
g.h.stop=function(){this.o();this.o=g.Ja;g.No(this.C);this.A?this.A.stop((0,g.x)(this.Fe,this,null),(0,g.x)(this.Fe,this,"Failed to stop DIAL device.")):this.Fe()};
g.h.Y=function(){this.o();this.o=g.Ja;g.No(this.C);this.A&&this.A.removeUpdateListener(this.R);this.A=null;A7.Tb.Y.call(this)};
g.h.IP=function(a){this.ha()||a||(y7(this,"DIAL session died."),this.o(),this.o=g.Ja,this.Fe())};
g.h.At=function(a){this.L=i6();if(this.B){var b=new chrome.cast.DialLaunchResponse(!0,Eza(this));a(b);Dza(this)}else this.F=(0,g.x)(function(){g.No(this.C);this.F=g.Ja;this.C=NaN;var c=new chrome.cast.DialLaunchResponse(!0,Eza(this));a(c);Dza(this)},this),this.C=g.Lo((0,g.x)(function(){this.F()},this),100)};
g.h.NG=function(a,b,c){yza(this.M,this.G.receiver.label,a,this.u.friendlyName,(0,g.x)(function(d){d&&d.token?(this.jq(d),b(new chrome.cast.DialLaunchResponse(!1))):this.At(b,c)},this),(0,g.x)(function(d){y7(this,"Failed to get DIAL screen: "+d);
this.At(b,c)},this))};g.Ta(B7,x7);B7.prototype.stop=function(){this.Fe()};
B7.prototype.Av=g.Ja;B7.prototype.Ek=function(){g.No(this.o);this.o=NaN;var a=k6(this.M.ye(),this.u.label);a?this.jq(a):this.Fe(Error("No such screen"))};
B7.prototype.Y=function(){g.No(this.o);this.o=NaN;B7.Tb.Y.call(this)};g.Ta(C7,g.O);g.h=C7.prototype;
g.h.init=function(a,b){chrome.cast.timeout.requestSession=3E4;var c=new chrome.cast.SessionRequest(this.G);this.H||(c.dialRequest=new chrome.cast.DialRequest("YouTube"));var d=chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:chrome.cast.DefaultActionPolicy.CREATE_SESSION,f=(0,g.x)(this.QM,this);c=new chrome.cast.ApiConfig(c,(0,g.x)(this.VB,this),f,d,e);c.customDialLaunchCallback=(0,g.x)(this.eL,this);chrome.cast.initialize(c,(0,g.x)(function(){this.ha()||
(chrome.cast.addReceiverActionListener(this.B),lza(),this.u.subscribe("onlineScreenChange",(0,g.x)(this.aE,this)),this.A=Gza(this),chrome.cast.setCustomReceivers(this.A,g.Ja,(0,g.x)(function(k){this.pc("Failed to set initial custom receivers: "+g.Pk(k))},this)),this.S("yt-remote-cast2-availability-change",E7(this)),b(!0))},this),(0,g.x)(function(k){this.pc("Failed to initialize API: "+g.Pk(k));
b(!1)},this))};
g.h.JO=function(a,b){D7("Setting connected screen ID: "+a+" -> "+b);if(this.o){var c=this.o.getScreen();if(!a||c&&c.id!=a)D7("Unsetting old screen status: "+this.o.u.friendlyName),F7(this,null)}if(a&&b){if(!this.o){c=k6(this.u.ye(),a);if(!c){D7("setConnectedScreenStatus: Unknown screen.");return}var d=Fza(this,c);d||(D7("setConnectedScreenStatus: Connected receiver not custom..."),d=new chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=chrome.cast.ReceiverType.CUSTOM,this.A.push(d),chrome.cast.setCustomReceivers(this.A,
g.Ja,(0,g.x)(function(e){this.pc("Failed to set initial custom receivers: "+g.Pk(e))},this)));
D7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);F7(this,new B7(this.u,d),!0)}this.o.Bv(b)}else D7("setConnectedScreenStatus: no screen.")};
g.h.KO=function(a){this.ha()?this.pc("Setting connection data on disposed cast v2"):this.o?this.o.Ek(a):this.pc("Setting connection data without a session")};
g.h.HP=function(){this.ha()?this.pc("Stopping session on disposed cast v2"):this.o?(this.o.stop(),F7(this,null)):D7("Stopping non-existing session")};
g.h.requestSession=function(){chrome.cast.requestSession((0,g.x)(this.VB,this),(0,g.x)(this.kN,this))};
g.h.Y=function(){this.u.unsubscribe("onlineScreenChange",(0,g.x)(this.aE,this));window.chrome&&chrome.cast&&chrome.cast.removeReceiverActionListener(this.B);var a=iza,b=g.Ia("yt.mdx.remote.debug.handlers_");g.gb(b||[],a);g.Ne(this.o);C7.Tb.Y.call(this)};
g.h.pc=function(a){h7("Controller",a)};
g.h.XB=function(a,b){this.o==a&&(b||F7(this,null),this.S("yt-remote-cast2-session-change",b))};
g.h.LM=function(a,b){if(!this.ha())if(a)switch(a.friendlyName=chrome.cast.unescape(a.friendlyName),D7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case chrome.cast.ReceiverAction.CAST:if(this.o)if(this.o.u.label!=a.label)D7("onReceiverAction_: Stopping active receiver: "+this.o.u.friendlyName),this.o.stop();else{D7("onReceiverAction_: Casting to active receiver.");this.o.getScreen()&&this.S("yt-remote-cast2-session-change",this.o.getScreen());break}switch(a.receiverType){case chrome.cast.ReceiverType.CUSTOM:F7(this,
new B7(this.u,a));break;case chrome.cast.ReceiverType.DIAL:F7(this,new A7(this.u,a,this.F));break;case chrome.cast.ReceiverType.CAST:F7(this,new z7(this.u,a));break;default:this.pc("Unknown receiver type: "+a.receiverType)}break;case chrome.cast.ReceiverAction.STOP:this.o&&this.o.u.label==a.label?this.o.stop():this.pc("Stopping receiver w/o session: "+a.friendlyName)}else this.pc("onReceiverAction_ called without receiver.")};
g.h.eL=function(a){if(this.ha())return Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=chrome.cast.ReceiverType.DIAL&&(this.pc("Not DIAL receiver: "+b.friendlyName),b.receiverType=chrome.cast.ReceiverType.DIAL);var c=this.o?this.o.u:null;if(!c||c.label!=b.label)return this.pc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=chrome.cast.ReceiverType.DIAL){if(this.o.getScreen())return D7("Reselecting dial screen."),
this.S("yt-remote-cast2-session-change",this.o.getScreen()),Promise.resolve(new chrome.cast.DialLaunchResponse(!1));this.pc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);F7(this,new A7(this.u,b,this.F))}b=this.o;b.G=a;return b.G.appState==chrome.cast.DialAppState.RUNNING?new Promise((0,g.x)(b.NG,b,(b.G.extraData||{}).screenId||null)):new Promise((0,g.x)(b.At,b))};
g.h.VB=function(a){if(!this.ha()){D7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=chrome.cast.ReceiverType.CUSTOM){if(!this.o)if(b.receiverType==chrome.cast.ReceiverType.CAST)D7("Got resumed cast session before resumed mdx connection."),b.friendlyName=chrome.cast.unescape(b.friendlyName),F7(this,new z7(this.u,b),!0);else{this.pc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.o.u,d=k6(this.u.ye(),c.label);d&&f6(d,b.label)&&
c.receiverType!=chrome.cast.ReceiverType.CAST&&b.receiverType==chrome.cast.ReceiverType.CAST&&(D7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Ne(this.o),this.o=new z7(this.u,b),this.o.subscribe("sessionScreen",(0,g.x)(this.XB,this,this.o)),this.o.Ek(null));this.o.Av(a)}}};
g.h.GP=function(){return this.o?this.o.bE():null};
g.h.kN=function(a){this.ha()||(this.pc("Failed to estabilish a session: "+g.Pk(a)),a.code!=chrome.cast.ErrorCode.CANCEL&&F7(this,null))};
g.h.QM=function(a){D7("Receiver availability updated: "+a);if(!this.ha()){var b=E7(this);this.C=a==chrome.cast.ReceiverAvailability.AVAILABLE;E7(this)!=b&&this.S("yt-remote-cast2-availability-change",E7(this))}};
g.h.aE=function(){this.ha()||(this.A=Gza(this),D7("Updating custom receivers: "+g.Pk(this.A)),chrome.cast.setCustomReceivers(this.A,g.Ja,(0,g.x)(function(){this.pc("Failed to set custom receivers.")},this)),this.S("yt-remote-cast2-availability-change",E7(this)))};
C7.prototype.setLaunchParams=C7.prototype.KO;C7.prototype.setConnectedScreenStatus=C7.prototype.JO;C7.prototype.stopSession=C7.prototype.HP;C7.prototype.getCastSession=C7.prototype.GP;C7.prototype.requestSession=C7.prototype.requestSession;C7.prototype.init=C7.prototype.init;C7.prototype.dispose=C7.prototype.dispose;var L7=[];g.h=Q7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";R7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.playerState=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.o=a.trackData,this.eg=a.hasPrevious,this.hasNext=a.hasNext,this.G=a.playerTime,this.F=a.playerTimeAt,this.C=a.seekableStart,this.u=a.seekableEnd,this.H=a.duration,this.M=a.loadedTime,this.B=a.liveIngestionTime,this.A=!isNaN(this.B))};
g.h.nb=function(){return 1==this.playerState};
g.h.isAdPlaying=function(){return 1081==this.playerState};
g.h.getDuration=function(){return this.A?this.H+S7(this):this.H};
g.h.clone=function(){return new Q7(W7(this))};g.r(Y7,g.O);g.h=Y7.prototype;g.h.play=function(){1==this.o?(this.u?this.u.play(null,g.Ja,d8(this,"play")):c8(this,"play"),b8(this,1,U7(Z7(this))),this.S("remotePlayerChange")):$7(this,this.play)};
g.h.pause=function(){1==this.o?(this.u?this.u.pause(null,g.Ja,d8(this,"pause")):c8(this,"pause"),b8(this,2,U7(Z7(this))),this.S("remotePlayerChange")):$7(this,this.pause)};
g.h.seekTo=function(a){if(1==this.o){if(this.u){var b=Z7(this),c=new chrome.cast.media.SeekRequest;c.currentTime=a;b.nb()||3==b.playerState?c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_START:c.resumeState=chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.u.seek(c,g.Ja,d8(this,"seekTo",{newTime:a}))}else c8(this,"seekTo",{newTime:a});b8(this,3,a);this.S("remotePlayerChange")}else $7(this,g.Ra(this.seekTo,a))};
g.h.stop=function(){if(1==this.o){this.u?this.u.stop(null,g.Ja,d8(this,"stopVideo")):c8(this,"stopVideo");var a=Z7(this);a.index=-1;a.videoId="";R7(a);a8(this,a);this.S("remotePlayerChange")}else $7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.o){var c=Z7(this);if(this.A){if(c.volume!=a){var d=Math.round(a)/100;this.A.setReceiverVolumeLevel(d,(0,g.x)(function(){h7("CP","set receiver volume: "+d)},this),(0,g.x)(function(){this.pc("failed to set receiver volume.")},this))}c.muted!=b&&this.A.setReceiverMuted(b,(0,g.x)(function(){h7("CP","set receiver muted: "+b)},this),(0,g.x)(function(){this.pc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);c8(this,"setVolume",e)}c.muted=b;c.volume=a;a8(this,c)}else $7(this,g.Ra(this.setVolume,a,b))};
g.h.WD=function(a,b){if(1==this.o){var c=Z7(this),d={videoId:a};b&&(c.o={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,kind:b.kind},d.style=g.Pk(b.style),g.Wb(d,c.o));c8(this,"setSubtitlesTrack",d);a8(this,c)}else $7(this,g.Ra(this.WD,a,b))};
g.h.setAudioTrack=function(a,b){if(1==this.o){var c=b.getLanguageInfo().getId();c8(this,"setAudioTrack",{videoId:a,audioTrackId:c});var d=Z7(this);d.audioTrackId=c;a8(this,d)}else $7(this,g.Ra(this.setAudioTrack,a,b))};
g.h.playVideo=function(a,b,c,d,e,f,k){var l=Z7(this);c=c||0;var m={videoId:a,currentIndex:c};V7(l,a,c);void 0!==b&&(T7(l,b),m.currentTime=b);void 0!==d&&(m.listId=d);null!=e&&(m.playerParams=e);null!=f&&(m.clickTrackingParams=f);null!=k&&(m.locationInfo=g.Pk(k));c8(this,"setPlaylist",m);d||a8(this,l)};
g.h.qq=function(a,b){if(1==this.o){if(a&&b){var c=Z7(this);V7(c,a,b);a8(this,c)}c8(this,"previous")}else $7(this,g.Ra(this.qq,a,b))};
g.h.nextVideo=function(a,b){if(1==this.o){if(a&&b){var c=Z7(this);V7(c,a,b);a8(this,c)}c8(this,"next")}else $7(this,g.Ra(this.nextVideo,a,b))};
g.h.Px=function(){1==this.o?c8(this,"dismissAutoplay"):$7(this,this.Px)};
g.h.dispose=function(){if(3!=this.o){var a=this.o;this.o=3;this.S("proxyStateChange",a,this.o)}g.O.prototype.dispose.call(this)};
g.h.Y=function(){Tza(this);this.B=null;this.C.clear();X7(this,null);g.O.prototype.Y.call(this)};
g.h.kw=function(a){if((a!=this.o||2==a)&&3!=this.o&&0!=a){var b=this.o;this.o=a;this.S("proxyStateChange",b,a);if(1==a)for(;!this.C.isEmpty();)b=a=this.C,g.db(b.o)&&(b.o=b.u,b.o.reverse(),b.u=[]),a.o.pop().apply(this);else 3==a&&this.dispose()}};
g.h.IM=function(a,b){this.S(a,b)};
g.h.NK=function(a){if(!a)this.Tm(null),X7(this,null);else if(this.A.receiver.volume){a=this.A.receiver.volume;var b=Z7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)h7("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,a8(this,b)}};
g.h.Tm=function(a){h7("CP","Cast media: "+!!a);this.u&&this.u.removeUpdateListener(this.H);if(this.u=a)this.u.addUpdateListener(this.H),Uza(this),this.S("remotePlayerChange")};
g.h.MK=function(a){a?(Uza(this),this.S("remotePlayerChange")):this.Tm(null)};
g.h.Qv=function(){c8(this,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.XK=function(){var a=Qza();a&&X7(this,a)};
g.h.pc=function(a){h7("CP",a)};g.r(e8,g.O);g.h=e8.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime,n=b.locationInfo;void 0!==m&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);n&&(l.locationInfo=n);f&&(l.clickTrackingParams=f);c&&(l.listId=c);void 0!==k&&(l.currentIndex=k);c&&(this.bb.listId=c);this.bb.videoId=d;this.bb.index=k||0;this.bb.state=3;T7(this.bb,m);this.B="UNSUPPORTED";f8("Connecting with setPlaylist and params: "+g.Pk(l));this.o.connect({method:"setPlaylist",
params:g.Pk(l)},a,gya())}else f8("Connecting without params"),this.o.connect({},a,gya());Wza(this)};
g.h.dispose=function(){this.ha()||(this.S("beforeDispose"),g8(this,3));g.O.prototype.dispose.call(this)};
g.h.Y=function(){h8(this);j8(this);i8(this);g.No(this.G);this.G=NaN;g.No(this.H);this.H=NaN;this.A=null;g.ip(this.T);this.T.length=0;this.o.dispose();g.O.prototype.Y.call(this);this.B=this.F=this.u=this.bb=this.o=null};
g.h.dG=function(){this.ek(2)};
g.h.RK=function(){f8("Channel opened");this.R&&(this.R=!1,i8(this),this.L=g.Lo((0,g.x)(function(){f8("Timing out waiting for a screen.");this.ek(1)},this),15E3));
kya(fza(this.o),this.U)};
g.h.OK=function(){f8("Channel closed");isNaN(this.C)?p6(!0):p6();this.dispose()};
g.h.PK=function(a){p6();isNaN(this.jm())?(f8("Channel error: "+a+" without reconnection"),this.dispose()):(this.R=!0,f8("Channel error: "+a+" with reconnection in "+this.jm()+" ms"),g8(this,2))};
g.h.QK=function(a){a.params?f8("Received: action="+a.action+", params="+g.Pk(a.params)):f8("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=w6(a.params.devices);this.u=(0,g.Jc)(a,function(c){return new d6(c)});
a=!!g.$a(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
Zza(this,a);break;case "loungeScreenDisconnected":g.ib(this.u,function(c){return"LOUNGE_SCREEN"==c.type});
Zza(this,!1);break;case "remoteConnected":var b=new d6(w6(a.params.device));g.$a(this.u,function(c){return b?c.id==b.id:!1})||Rxa(this.u,b);
break;case "remoteDisconnected":b=new d6(w6(a.params.device));g.ib(this.u,function(c){return b?c.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":aAa(this,a);break;case "nowPlaying":cAa(this,a);break;case "onStateChange":bAa(this,a);break;case "onAdStateChange":dAa(this,a);break;case "onVolumeChanged":eAa(this,a);break;case "onSubtitlesTrackChanged":$za(this,a);break;case "nowAutoplaying":fAa(this,a);break;case "autoplayDismissed":this.S("autoplayDismissed");break;case "autoplayUpNext":this.F=a.params.videoId||null;this.S("autoplayUpNext",this.F);break;case "onAutoplayModeChanged":this.B=
a.params.autoplayMode;this.S("autoplayModeChange",this.B);"DISABLED"==this.B&&this.S("autoplayDismissed");break;case "onHasPreviousNextChanged":gAa(this,a);break;case "requestAssistedSignIn":this.S("assistedSignInRequested",a.params.authCode);break;default:f8("Unrecognized action: "+a.action)}};
g.h.xO=function(){if(this.A){var a=this.A;this.A=null;this.bb.videoId!=a&&k8(this,"getNowPlaying")}};
g.h.UF=function(){var a=3;this.ha()||(a=0,isNaN(this.jm())?c7(this.o)&&isNaN(this.C)&&(a=1):a=2);return a};
g.h.ek=function(a){f8("Disconnecting with "+a);h8(this);this.S("beforeDisconnect",a);1==a&&p6();gza(this.o,a);this.dispose()};
g.h.SF=function(){var a=this.bb;this.A&&(a=this.bb.clone(),V7(a,this.A,a.index));return W7(a)};
g.h.LO=function(a){var b=new Q7(a);b.videoId&&b.videoId!=this.bb.videoId&&(this.A=b.videoId,g.No(this.G),this.G=g.Lo((0,g.x)(this.xO,this),5E3));var c=[];this.bb.listId==b.listId&&this.bb.videoId==b.videoId&&this.bb.index==b.index||c.push("remoteQueueChange");this.bb.playerState==b.playerState&&this.bb.volume==b.volume&&this.bb.muted==b.muted&&U7(this.bb)==U7(b)&&g.Pk(this.bb.o)==g.Pk(b.o)||c.push("remotePlayerChange");this.bb.reset(a);(0,g.y)(c,function(d){this.S(d)},this)};
g.h.By=function(){var a=this.o.F.id,b=g.$a(this.u,function(c){return"REMOTE_CONTROL"==c.type&&c.id!=a});
return b?b.id:""};
g.h.jm=function(){var a=this.o;return a.u.isActive()?a.u.u-(0,g.C)():NaN};
g.h.HF=function(){return this.B||"UNSUPPORTED"};
g.h.IF=function(){return this.F||""};
g.h.zP=function(){if(!isNaN(this.jm())){var a=this.o.u;g.yn(a.o);a.start()}};
g.h.FO=function(a,b){k8(this,a,b);Yza(this)};
e8.prototype.subscribe=e8.prototype.subscribe;e8.prototype.unsubscribeByKey=e8.prototype.li;e8.prototype.getProxyState=e8.prototype.UF;e8.prototype.disconnect=e8.prototype.ek;e8.prototype.getPlayerContextData=e8.prototype.SF;e8.prototype.setPlayerContextData=e8.prototype.LO;e8.prototype.getOtherConnectedRemoteId=e8.prototype.By;e8.prototype.getReconnectTimeout=e8.prototype.jm;e8.prototype.getAutoplayMode=e8.prototype.HF;e8.prototype.getAutoplayVideoId=e8.prototype.IF;e8.prototype.reconnect=e8.prototype.zP;
e8.prototype.sendMessage=e8.prototype.FO;g.r(l8,l7);g.h=l8.prototype;g.h.ye=function(a){return this.Qd.$_gs(a)};
g.h.contains=function(a){return!!this.Qd.$_c(a)};
g.h.get=function(a){return this.Qd.$_g(a)};
g.h.start=function(){this.Qd.$_st()};
g.h.add=function(a,b,c){this.Qd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.Qd.$_r(a,b,c)};
g.h.Xq=function(a,b,c,d){this.Qd.$_un(a,b,c,d)};
g.h.Y=function(){for(var a=0,b=this.o.length;a<b;++a)this.Qd.$_ubk(this.o[a]);this.o.length=0;this.Qd=null;l7.prototype.Y.call(this)};
g.h.DP=function(){this.S("screenChange")};
g.h.mM=function(){this.S("onlineScreenChange")};
u7.prototype.$_st=u7.prototype.start;u7.prototype.$_gspc=u7.prototype.EP;u7.prototype.$_gsppc=u7.prototype.ZD;u7.prototype.$_c=u7.prototype.contains;u7.prototype.$_g=u7.prototype.get;u7.prototype.$_a=u7.prototype.add;u7.prototype.$_un=u7.prototype.Xq;u7.prototype.$_r=u7.prototype.remove;u7.prototype.$_gs=u7.prototype.ye;u7.prototype.$_gos=u7.prototype.YD;u7.prototype.$_s=u7.prototype.subscribe;u7.prototype.$_ubk=u7.prototype.li;var E8=null,D8=!1,m8=null,n8=null,C8=null,r8=[];g.r(F8,g.z);g.h=F8.prototype;g.h.Y=function(){g.z.prototype.Y.call(this);this.o.stop();this.u.stop();this.G.stop();this.L();var a=this.Ua;a.unsubscribe("proxyStateChange",this.RB,this);a.unsubscribe("remotePlayerChange",this.Xm,this);a.unsubscribe("remoteQueueChange",this.kq,this);a.unsubscribe("previousNextChange",this.NB,this);a.unsubscribe("nowAutoplaying",this.JB,this);a.unsubscribe("autoplayDismissed",this.gB,this);this.Ua=this.module=null};
g.h.dA=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.Ua.o)if(H8(this)){if(!Z7(this.Ua).isAdPlaying()||"control_seek"!==a)switch(a){case "control_toggle_play_pause":Z7(this.Ua).nb()?this.Ua.pause():this.Ua.play();break;case "control_play":this.Ua.play();break;case "control_pause":this.Ua.pause();break;case "control_seek":this.F.Jz(c[0],c[1]);break;case "control_subtitles_set_track":I8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=
this.J.getCurrentTime();J8(this,0===c?void 0:c);break;case "control_seek":J8(this,c[0]);break;case "control_subtitles_set_track":I8(this,c[0]);break;case "control_set_audio_track":this.setAudioTrack(c[0])}};
g.h.LK=function(a){this.G.aG(a)};
g.h.gP=function(a){this.dA("control_subtitles_set_track",g.Pb(a)?null:a)};
g.h.hD=function(){var a=this.J.getOption("captions","track");g.Pb(a)||I8(this,a)};
g.h.ac=function(a){this.module.ac(a,this.J.getVideoData().lengthSeconds)};
g.h.xB=function(a){if(H8(this)){this.Ua.unsubscribe("remotePlayerChange",this.Xm,this);var b=Math.round(a.volume);a=!!a.muted;var c=Z7(this.Ua);if(b!==c.volume||a!==c.muted)this.Ua.setVolume(b,a),this.H.start();this.Ua.subscribe("remotePlayerChange",this.Xm,this)}};
g.h.ML=function(){g.Pb(this.A)||sAa(this,this.A);this.B=!1};
g.h.RB=function(a,b){this.u.stop();2===b&&this.fD()};
g.h.Xm=function(){if(H8(this)){this.o.stop();var a=Z7(this.Ua);switch(a.playerState){case 1080:case 1081:case 1084:case 1085:this.module.kd=1;break;case 1082:case 1083:this.module.kd=0;break;default:this.module.kd=-1}switch(a.playerState){case 1081:case 1:G8(this,new g.MC(8));this.eD();break;case 1085:case 3:G8(this,new g.MC(9));break;case 1083:case 0:G8(this,new g.MC(2));this.F.stop();this.ac(this.J.getVideoData().lengthSeconds);break;case 1084:G8(this,new g.MC(4));break;case 2:G8(this,new g.MC(4));
this.ac(U7(a));break;case -1:G8(this,new g.MC(64));break;case -1E3:G8(this,new g.MC(128,{errorCode:"mdx.remoteerror",errorMessage:"Este v\u00eddeo n\u00e3o est\u00e1 dispon\u00edvel para reprodu\u00e7\u00e3o remota."}))}a=Z7(this.Ua).o;var b=this.A;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.kind==b.kind:1)||(this.A=a,sAa(this,a));a=Z7(this.Ua);-1===a.volume||Math.round(this.J.getVolume())===a.volume&&this.J.isMuted()===a.muted||this.H.isActive()||
this.KD()}else rAa(this)};
g.h.NB=function(){this.J.S("mdxpreviousnextchange")};
g.h.kq=function(){H8(this)||rAa(this)};
g.h.JB=function(a){isNaN(a)||this.J.S("mdxnowautoplaying",a)};
g.h.gB=function(){this.J.S("mdxautoplaycanceled")};
g.h.setAudioTrack=function(a){H8(this)&&this.Ua.setAudioTrack(this.J.getVideoData(1).videoId,a)};
g.h.seekTo=function(a,b){-1===Z7(this.Ua).playerState?J8(this,a):b&&this.Ua.seekTo(a)};
g.h.KD=function(){if(H8(this)){var a=Z7(this.Ua);this.events.kb(this.M);a.muted?this.J.mute():this.J.unMute();this.J.setVolume(a.volume);this.M=this.events.N(this.J,"onVolumeChange",this.xB)}};
g.h.eD=function(){this.o.stop();if(!this.Ua.ha()){var a=Z7(this.Ua);a.nb()&&G8(this,new g.MC(8));this.ac(U7(a));this.o.start()}};
g.h.fD=function(){this.u.stop();this.o.stop();var a=this.Ua.B.getReconnectTimeout();2==this.Ua.o&&!isNaN(a)&&this.u.start()};g.r(K8,g.W);K8.prototype.jc=function(){this.o.show()};
K8.prototype.Pa=function(){this.o.hide()};
K8.prototype.u=function(){g.hO("https://support.google.com/youtube/answer/7640706")};
K8.prototype.A=function(){c6("mdx-manual-pairing-popup-ok");this.Pa()};g.r(L8,g.W);L8.prototype.jc=function(){this.o.show()};
L8.prototype.Pa=function(){this.o.hide()};
L8.prototype.u=function(){c6("mdx-privacy-popup-cancel");this.Pa()};
L8.prototype.A=function(){c6("mdx-privacy-popup-confirm");this.Pa()};g.r(M8,g.W);M8.prototype.u=function(a){uAa(this,a.state)};g.r(N8,g.DP);N8.prototype.B=function(){var a=this.J.getOption("remote","receivers");a&&1<a.length&&!this.J.getOption("remote","quickCast")?(this.ti=g.yb(a,this.o,this),g.FP(this,(0,g.Jc)(a,this.o)),a=this.J.getOption("remote","currentReceiver"),this.Jb(this.o(a)),this.enable(!0)):this.enable(!1)};
N8.prototype.o=function(a){return a.key};
N8.prototype.Ef=function(a){return"cast-selector-receiver"===a?"Elenco...":this.ti[a].name};
N8.prototype.Bd=function(a){g.DP.prototype.Bd.call(this,a);this.J.setOption("remote","currentReceiver",this.ti[a]);this.La.Pa()};g.r(O8,g.ZL);g.h=O8.prototype;
g.h.create=function(){lAa(g.Vy(this.player.O()));this.subscriptions.push(g.So("yt-remote-before-disconnect",this.JK,this));this.subscriptions.push(g.So("yt-remote-connection-change",this.RM,this));this.subscriptions.push(g.So("yt-remote-receiver-availability-change",this.PB,this));this.subscriptions.push(g.So("yt-remote-auto-connect",this.PM,this));this.subscriptions.push(g.So("yt-remote-receiver-resumed",this.OM,this));this.subscriptions.push(g.So("mdx-privacy-popup-confirm",this.lO,this));this.subscriptions.push(g.So("mdx-privacy-popup-cancel",
this.kO,this));this.subscriptions.push(g.So("mdx-manual-pairing-popup-ok",this.iH,this));this.PB()};
g.h.load=function(){this.player.cancelPlayback();g.ZL.prototype.load.call(this);this.qe=new F8(this,this.player,this.Ua);var a=(a=qAa())?a.currentTime:0;var b=B8()?new Y7(w8(),void 0):null;0==a&&b&&(a=U7(Z7(b)));0!==a&&this.ac(a);tAa(this,this.Pb,this.Pb);g.CT(this.player.app,6)};
g.h.unload=function(){this.player.S("mdxautoplaycanceled");this.Dh=this.Bf;g.Oe(this.qe,this.Ua);this.Ua=this.qe=null;g.ZL.prototype.unload.call(this);g.CT(this.player.app,5);P8(this)};
g.h.Y=function(){g.To(this.subscriptions);g.ZL.prototype.Y.call(this)};
g.h.rg=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.qe.dA.apply(this.qe,[a].concat(g.la(c)))};
g.h.getAdState=function(){return this.kd};
g.h.WF=function(){return this.loaded?this.qe.suggestion:null};
g.h.eg=function(){return this.Ua?Z7(this.Ua).eg:!1};
g.h.hasNext=function(){return this.Ua?Z7(this.Ua).hasNext:!1};
g.h.ac=function(a,b){this.uz=a||0;this.player.S("progresssync",a,b)};
g.h.getCurrentTime=function(){return this.uz};
g.h.getProgressState=function(){var a=Z7(this.Ua),b=this.player.getVideoData();return{allowSeeking:g.P(this.player.O().experiments,"web_player_mdx_allow_seeking_change_killswitch")?this.player.jd():!a.isAdPlaying()&&this.player.jd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.A?a.B+S7(a):a.B,isAtLiveHead:1>=(a.A?a.u+S7(a):a.u)-this.getCurrentTime(),loaded:a.M,seekableEnd:a.A?a.u+S7(a):a.u,seekableStart:0<a.C?a.C+
S7(a):a.C}};
g.h.nextVideo=function(){this.Ua&&this.Ua.nextVideo()};
g.h.qq=function(){this.Ua&&this.Ua.qq()};
g.h.JK=function(a){1===a&&(this.Vu=this.Ua?Z7(this.Ua):null)};
g.h.RM=function(){var a=B8()?new Y7(w8(),void 0):null;if(a){var b=this.Dh;this.loaded&&this.unload();this.Ua=a;this.Vu=null;b.key!==this.Bf.key&&(this.Dh=b,this.load())}else g.Ne(this.Ua),this.Ua=null,this.loaded&&(this.unload(),(a=this.Vu)&&a.videoId===this.player.getVideoData().videoId&&this.player.cueVideoById(a.videoId,U7(a)));this.player.S("videodatachange","newdata",this.player.getVideoData(),3)};
g.h.PB=function(){this.ti=[this.Bf].concat(nAa());var a=x8()||this.Bf;Q8(this,a);this.player.sa("onMdxReceiversChange")};
g.h.PM=function(){var a=x8();Q8(this,a)};
g.h.OM=function(){this.Dh=x8()};
g.h.lO=function(){this.Ym=!0;P8(this);D8=!1;E8&&z8(E8,1);E8=null};
g.h.kO=function(){this.Ym=!1;P8(this);Q8(this,this.Bf);this.Dh=this.Bf;D8=!1;E8=null;this.player.playVideo()};
g.h.iH=function(){this.rp=!0;P8(this);g.Qs("yt-remote-manual-pairing-warning-shown",!0,2592E3);D8=!1;E8&&z8(E8,1);E8=null};
g.h.fd=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.ti;case "currentReceiver":return b&&("cast-selector-receiver"===b.key?O7():Q8(this,b)),this.loaded?this.Dh:this.Bf;case "quickCast":return 2===this.ti.length&&"cast-selector-receiver"===this.ti[1].key?(b&&O7(),!0):!1}};
g.h.Qv=function(){this.Ua.Qv()};
g.h.Lf=function(){return!1};
g.h.getOptions=function(){return["casting","receivers","currentReceiver","quickCast"]};g.nM.remote=O8;})(_yt_player);
